Repository kubernetes/website, pull requests merged in 2018-08, with the labels that each got.

#9695 fix the command output
  content/en/docs/concepts/services-networking/connect-applications-service.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9697 fix the command output
  content/en/docs/tasks/configure-pod-container/assign-pods-nodes.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9670 Disable excludes when installing kube packages
  content/en/docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#9685 add link to nvidia gpu scheduling guide at end of device plugin document
  content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9700 Fix persistentVolumeClaim link
  content/en/docs/concepts/storage/volumes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9705 DamonSet typo
  content/en/docs/concepts/workloads/controllers/daemonset.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9704 config: Get mediaTypes config in line with the Hugo version
  config.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9668 fix the command output
  content/en/docs/setup/minikube.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9666 Add CSI and Flexvolume to glossary
  content/en/docs/reference/glossary/csi.md
  content/en/docs/reference/glossary/flexvolume.md
Labels: approved, cncf-cla: yes, lgtm, sig/storage, size/M

#9631 Update resource-usage-monitoring.md
  content/en/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9627 Adding patch command to forceful delete zombie stateful pod
  content/en/docs/tasks/run-application/force-delete-stateful-set-pod.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9711 Trivial: Update HPA description
  content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9638 kubeadm-init: update notes related to the configuration
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/S

#9726 Fix SubjectAccessReview example yaml
  content/en/docs/reference/access-authn-authz/authorization.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9724 change newline character to LF from CRLF
  content/en/docs/tutorials/k8s201.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#9702 Small typo in service.md
  content/en/docs/concepts/services-networking/service.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9701 Add instructions for Macports
  content/en/docs/tasks/tools/install-kubectl.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9691 update owners of minikube doc
  content/en/docs/setup/minikube.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#9662 Add ExpandInUsePersistentVolumes feature gate
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9703 Update to Hugo 0.46
  netlify.toml
  resources/_gen/assets/sass/cn/sass/styles.sass_8348eecb74b7f1dceadfa8f990b7802f.content
  resources/_gen/assets/sass/cn/sass/styles.sass_8348eecb74b7f1dceadfa8f990b7802f.json
  resources/_gen/assets/sass/cn/sass/styles.sass_a6e533854c4de092afe9278041939937.content
  resources/_gen/assets/sass/cn/sass/styles.sass_a6e533854c4de092afe9278041939937.json
  resources/_gen/assets/sass/cn/sass/styles.sass_cb957da2191fde4902dd41b139c8069d.content
  resources/_gen/assets/sass/cn/sass/styles.sass_cb957da2191fde4902dd41b139c8069d.json
  resources/_gen/assets/sass/sass/case_study_styles.sass_892df88c65b3b9097bc19fe132ab934f.content
  resources/_gen/assets/sass/sass/case_study_styles.sass_892df88c65b3b9097bc19fe132ab934f.json
  resources/_gen/assets/sass/sass/styles.sass_8348eecb74b7f1dceadfa8f990b7802f.content
  resources/_gen/assets/sass/sass/styles.sass_8348eecb74b7f1dceadfa8f990b7802f.json
  resources/_gen/assets/sass/sass/styles.sass_a6e533854c4de092afe9278041939937.content
  resources/_gen/assets/sass/sass/styles.sass_a6e533854c4de092afe9278041939937.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#9720 typo
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#9735 fix broken link for blog post
  content/en/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9714 Blog Post: Dynamically Expand Volume with CSI and Kubernetes
  content/en/blog/_posts/2018-08-02-dynamically-expand-volume-csi.md
  static/images/blog/2018-08-02-dynamically-expand-volume-csi/csi-diagram.png
  static/images/blog/2018-08-02-dynamically-expand-volume-csi/prometheus-grafana.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#9716 Blog Post: Out of the Clouds onto the Ground: How to Make Kubernetes Production Grade Anywhere
  content/en/blog/_posts/2018-08-03-make-kubernetes-production-grade-anywhere.md
  static/images/blog/2018-08-03-make-kubernetes-production-grade-anywhere/airplane.png
  static/images/blog/2018-08-03-make-kubernetes-production-grade-anywhere/api-server.png
  static/images/blog/2018-08-03-make-kubernetes-production-grade-anywhere/disaster-recovery.png
  static/images/blog/2018-08-03-make-kubernetes-production-grade-anywhere/dual-host-deployment.png
  static/images/blog/2018-08-03-make-kubernetes-production-grade-anywhere/kubernetes-components-ha.png
  static/images/blog/2018-08-03-make-kubernetes-production-grade-anywhere/single-host-deployment.png
  static/images/blog/2018-08-03-make-kubernetes-production-grade-anywhere/triple-host-deployment.png
  static/images/blog/2018-08-03-make-kubernetes-production-grade-anywhere/without-incidence.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#9750 Fixes #9078 by adding note and link to table
  content/en/docs/tasks/inject-data-application/define-command-argument-container.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9746 Update autocomplete instructions for Oh-My-Zsh
  content/en/docs/tasks/tools/install-kubectl.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9745 fix the command output
  content/en/docs/setup/multiple-zones.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9749 Fixed PID missmatch in zookeeper.md
  content/en/docs/tutorials/stateful-application/zookeeper.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9744 fix extended-resource-demo
  content/en/docs/tasks/configure-pod-container/extended-resource.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9741 Add missing newline to fix list display on website
  content/en/docs/reference/using-api/api-overview.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9742 Add Knitter to the list of network addons.
  content/en/docs/concepts/cluster-administration/addons.md
  content/en/docs/concepts/cluster-administration/networking.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9734 apply tutorial template (k8s201)
  content/en/docs/tutorials/k8s201.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9732 apply template
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9733 apply tutorial template (k8s101)
  content/en/docs/tutorials/k8s101.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9729 Add necessity of metrics-server for HPA
  content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9715 Add a section on interactions of Pod priority and QoS
  content/en/docs/concepts/configuration/pod-priority-preemption.md
Labels: approved, cncf-cla: yes, lgtm, sig/scheduling, size/S

#9752 Update service definition to bind to 127.0.0.1
  content/en/docs/setup/independent/setup-ha-etcd-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9684 Update kubelet Documentaion
  content/en/docs/reference/command-line-tools-reference/kubelet.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9698 Document the wire format for X-Remote-Extra- and Impersonate-Extra- keys
  content/en/docs/reference/access-authn-authz/authentication.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9510 Reorganize docs contrib guide
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  content/en/docs/contribute/_index.md
  content/en/docs/contribute/advanced.md
  content/en/docs/contribute/generate-ref-docs/_index.md
  content/en/docs/contribute/generate-ref-docs/federation-api.md
  content/en/docs/contribute/generate-ref-docs/kubectl.md
  content/en/docs/contribute/generate-ref-docs/kubernetes-api.md
  content/en/docs/contribute/generate-ref-docs/kubernetes-components.md
  content/en/docs/contribute/intermediate.md
  content/en/docs/contribute/localization.md
  content/en/docs/contribute/participating.md
  content/en/docs/contribute/start.md
  content/en/docs/contribute/style/_index.md
  content/en/docs/contribute/style/content-organization.md
  content/en/docs/contribute/style/hugo_shortcodes.md/example1.md
  content/en/docs/contribute/style/hugo_shortcodes.md/example2.md
  content/en/docs/contribute/style/hugo_shortcodes.md/index.md
  content/en/docs/contribute/style/hugo_shortcodes.md/podtemplate.json
  content/en/docs/contribute/style/page-templates.md
  content/en/docs/contribute/style/style-guide.md
  content/en/docs/contribute/style/write-new-topic.md
  content/en/docs/doc-contributor-tools/snippets/README.md
  content/en/docs/editdocs.md
  content/en/docs/home/contribute/_index.md
  content/en/docs/home/contribute/blog-post.md
  content/en/docs/home/contribute/create-pull-request.md
  content/en/docs/home/contribute/page-templates.md
  content/en/docs/home/contribute/participating.md
  content/en/docs/home/contribute/review-issues.md
  content/en/docs/reference/glossary/approver.md
  content/en/docs/reference/glossary/maintainer.md
  content/en/docs/test.md
  layouts/docs/baseof.html
  layouts/docs/list.html
  layouts/partials/docs/content_page.html
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/XXL, team/google

#9753 fix the command output
  content/en/docs/tasks/administer-cluster/dns-horizontal-autoscaling.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9707 Adding Learn More Links to Partner Page
  content/en/partners/_index.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9770 Add details of how to use https
  content/en/docs/tasks/administer-cluster/access-cluster-services.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9763 tasks/administer-cluster: fix typo in PNG image
  static/images/docs/ha-master-gce.png
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, sig/gcp, size/XS

#9743 add some step
  content/en/docs/tasks/configure-pod-container/configure-volume-storage.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9788 Escape capture template commands
  content/en/docs/contribute/style/page-templates.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9782 Updated CNCF logo and KubeCon China dates on homepage
  assets/sass/_base.sass
  content/en/_index.html
  static/images/cncf-color.png
Labels: approved, cncf-cla: yes, lgtm, size/S

#9781 Update README and Dockerfile
  Dockerfile
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9777 fix the command output
  content/en/docs/tasks/administer-cluster/declare-network-policy.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9776 Remove linefeed so that the page does not break
  content/en/docs/getting-started-guides/ubuntu/operational-considerations.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9775 Update expose-external-ip-address.md
  content/en/docs/tutorials/stateless-application/expose-external-ip-address.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9771 Minor corrections
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9667 Fix kubectl top for memory-demo pod
  content/en/docs/tasks/configure-pod-container/assign-memory-resource.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9601 Generically refer to container runtimes.
  content/en/docs/concepts/architecture/nodes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9768 Add comments to noindex mechanism
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9792 Add info about requesting access
  content/en/docs/contribute/advanced.md
  content/en/docs/contribute/participating.md
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/L

#9802 Update kubeadm HA etcd docs
  content/en/docs/setup/independent/setup-ha-etcd-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#9799 fix the command output
  content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9821 fix the command output
  content/en/docs/tasks/administer-federation/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9820 fix the command output
  content/en/docs/tasks/federation/federation-service-discovery.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9818 fix the command output
  content/en/docs/tasks/debug-application-cluster/logging-stackdriver.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9817 fix the command output
  content/en/docs/tasks/debug-application-cluster/debug-service.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9813 fix the command output
  content/en/docs/tasks/access-application-cluster/port-forward-access-application-cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9815 fix the command output
  content/en/docs/tasks/access-application-cluster/connecting-frontend-backend.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9812 fix the command output
  content/en/docs/tasks/job/fine-parallel-processing-work-queue.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9814 fix the command output
  content/en/docs/tasks/access-application-cluster/load-balance-access-application-cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9816 fix the command output
  content/en/docs/tasks/debug-application-cluster/debug-application-introspection.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9804 fix feature state snippet code block
  content/en/docs/setup/independent/kubelet-integration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9803 changed the link path to current path.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9840 Removes self-referential link
  content/en/docs/tasks/inject-data-application/define-command-argument-container.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9830 Fix malformed Markdown in release notes causing missing bullets.
  content/en/docs/imported/release/notes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9796 Update SIG Azure reviewers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, sig/azure, size/XS

#9800 Remove incorrect and not needed mention of etcd datadir
  content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9495 Improve the preview card when sharing to social media
  layouts/partials/head.html
Labels: approved, cncf-cla: yes, lgtm, size/S, team/google

#9850 modify kubelet-tls-bootstrapping
  content/en/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9852 update SlingTV case study
  content/en/case-studies/slingtv.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9859 fix the command output
  content/en/docs/tutorials/stateless-application/expose-external-ip-address.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9858 fix the command output
  content/en/docs/tutorials/hello-minikube.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9845 Bing search for China users
  assets/sass/_base.sass
  layouts/docs/search.html
  static/js/search.js
Labels: approved, cncf-cla: yes, lgtm, size/L

#9856 Apply code snippet style
  content/en/docs/tasks/configure-pod-container/pull-image-private-registry.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9862 fix the command output
  content/en/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9861 fix the command output
  content/en/docs/tutorials/stateful-application/basic-stateful-set.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9842 rebase certificates PR on Hugo master
  content/en/docs/setup/certificates.md
  content/en/docs/setup/independent/kubelet-integration.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#9860 fix the command output
  content/en/docs/tutorials/stateless-application/guestbook.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9881 Fix Custom Hugo Shortcodes link
  content/en/docs/contribute/start.md
  content/en/docs/contribute/style/content-organization.md
  content/en/docs/contribute/style/hugo-shortcodes/example1.md
  content/en/docs/contribute/style/hugo-shortcodes/example2.md
  content/en/docs/contribute/style/hugo-shortcodes/index.md
  content/en/docs/contribute/style/hugo-shortcodes/podtemplate.json
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9885 fix the default k8s version in kubeadm
  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9890 Insert commas between clauses for readability
  content/en/docs/concepts/workloads/pods/pod.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9755 Fix broken links
  content/cn/docs/tasks/access-application-cluster/connecting-frontend-backend.md
  content/cn/docs/tutorials/services/source-ip.md
  content/cn/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md
  content/en/docs/concepts/configuration/overview.md
  content/en/docs/concepts/services-networking/ingress.md
  content/en/docs/reference/federation/v1/definitions.html
  content/en/docs/setup/independent/troubleshooting-kubeadm.md
  content/en/docs/tasks/access-application-cluster/connecting-frontend-backend.md
  content/en/docs/tasks/access-application-cluster/create-external-load-balancer.md
  content/en/docs/tasks/federation/federation-service-discovery.md
  content/en/docs/tasks/federation/set-up-cluster-federation-kubefed.md
  content/en/docs/tutorials/services/source-ip.md
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/M

#9853 Fix 404 in Configure DNS Cluster
  content/en/docs/tasks/access-application-cluster/configure-dns-cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9895 Clean up feature state includes
  content/en/docs/tasks/administer-cluster/storage-object-in-use-protection.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9896 Fix indentation and Code of Conduct link in contribute section
  content/en/docs/concepts/workloads/pods/pod-lifecycle.md
  content/en/docs/contribute/intermediate.md
  content/en/docs/contribute/start.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9865 Update namespaces.md
  content/en/docs/tasks/administer-cluster/namespaces.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9811 Add kontena/k8s-client ruby library
  content/en/docs/reference/using-api/client-libraries.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9751 Add permalinks to in-page headings
  layouts/docs/baseof.html
  static/css/custom-jekyll/tags.css
Labels: approved, cncf-cla: yes, lgtm, size/S, team/google

#9913 Update the URL for "Create a Documentation PR"
  data/user-personas/contributors/docs-contributor.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9915 Redirect /docs/contribute/foundational/ to /start
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9919 Update the content under versioning.
  content/en/docs/contribute/style/style-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9917 Fix sentence style capitalization
  content/en/docs/setup/minikube.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9916 Refactor Setup and Imported sections
  content/en/docs/community/_index.md
  content/en/docs/community/devel.md
  content/en/docs/community/guide.md
  content/en/docs/community/keps.md
  content/en/docs/community/mentoring.md
  content/en/docs/home/_index.md
  content/en/docs/imported/_index.md
  content/en/docs/imported/community/_index.md
  content/en/docs/reference/_index.md
  content/en/docs/setup/_index.md
  content/en/docs/setup/cluster-large.md
  content/en/docs/setup/custom-cloud/_index.md
  content/en/docs/setup/independent/_index.md
  content/en/docs/setup/multiple-zones.md
  content/en/docs/setup/on-premises-vm/_index.md
  content/en/docs/setup/pick-right-solution.md
  content/en/docs/setup/release/_index.md
  content/en/docs/setup/release/notes.md
  content/en/docs/setup/salt.md
  content/en/docs/setup/turnkey/_index.md
  update-imported-docs/community.yml
  update-imported-docs/release.yml
Labels: approved, cncf-cla: yes, lgtm, size/M, team/google

#9914 Fix Documentation link in nav back to Home
  content/en/docs/_index.md
  content/en/docs/home/_index.md
  layouts/partials/header.html
Labels: approved, cncf-cla: yes, lgtm, size/XS, team/google

#9887 Verify Google Analytics client is accessible before sending events
  static/js/user-journeys/home.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#9904 Add note about cron job suspend behavior
  content/en/docs/tasks/job/automated-tasks-with-cron-jobs.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9808 kubeadm-init: remove the deprecated --skip-preflight-checks
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#9866 Update status of aggregator in API overview doc
  content/en/docs/concepts/overview/kubernetes-api.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9810 Flag --show-all has been deprecated
  content/en/docs/tasks/job/automated-tasks-with-cron-jobs.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9793 create-cluster-kubeadm: update notes about flannel
  content/en/docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, sig/network, size/XS

#9897 Fixibmcloudname
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9165 Update advice on pinning output version of 'kubectl get'
  content/en/docs/reference/kubectl/conventions.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/XS

#9754 Missing code formatting
  content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9929 Applied Note Formatting
  content/en/docs/tasks/debug-application-cluster/debug-pod-replication-controller.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9795 Fix links in API reference docs
  static/docs/reference/generated/kubernetes-api/v1.11/index.html
  static/docs/reference/generated/kubernetes-api/v1.11/navData.js
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#9928 Reorganized and copy-edited the content
  content/en/docs/concepts/workloads/controllers/deployment.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9925 Applied note formatting
  content/en/docs/tasks/access-application-cluster/connecting-frontend-backend.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9927 Note Formatting Correction
  content/en/docs/tasks/access-application-cluster/create-external-load-balancer.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9926 fixed a typo in kubebuilder blogpost
  content/en/blog/_posts/2018-08-10-introducing-kubebuilder.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9504 add Dynatrace Kubernetes monitoring
  content/en/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/M

#9922 Fix sentence style capitalization in title
  content/en/docs/tasks/job/automated-tasks-with-cron-jobs.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9846 Update configure-pod-configmap.md
  content/en/docs/tasks/configure-pod-container/configure-pod-configmap.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9921 Minor grammar edit
  content/en/docs/tasks/run-application/run-stateless-application-deployment.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9874 Fixes #9787. Be explicit with page name for Hugo to find section
  content/en/docs/tutorials/kubernetes-basics/_index.html
  content/en/docs/tutorials/kubernetes-basics/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9876 assign-pod-node: pod affinity can't apply to all namespaces
  content/en/docs/concepts/configuration/assign-pod-node.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9797 cni networking plugin now support portmapping and bandwidth
  content/en/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9930 Applied Note Formatting
  content/en/docs/tasks/debug-application-cluster/debug-service.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9909 Fix code snippets and tweak a heading
  content/en/docs/tasks/tls/managing-tls-in-a-cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9920 Added shortcode callouts and removed future tense
  content/en/docs/concepts/architecture/nodes.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9936 The Kubernetes Basics link title is confusing
  content/en/docs/tutorials/kubernetes-basics/_index.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9932 Added Note Formatting
  content/en/docs/tasks/debug-application-cluster/logging-stackdriver.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9906 Fix inline YAML in resource quota
  content/en/docs/concepts/policy/resource-quotas.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#9903 Change the way to create ConfigMap
  content/en/docs/tutorials/configuration/configure-redis-using-configmap.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9931 Applied Note Formatting
  content/en/docs/tasks/debug-application-cluster/logging-elasticsearch-kibana.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9933 Added Note Formatting
  content/en/docs/tasks/debug-application-cluster/debug-application.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9934 Minor Fixes - Style Guide, Numbered Lists
  content/en/docs/tutorials/stateful-application/cassandra.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9912 update link to metrics-server repo
  content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
Labels: approved, cncf-cla: yes, lgtm, sig/instrumentation, size/XS

#9937 Fix position of Home in subnav
  content/en/docs/home/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, team/google

#9938 Minor changes
  content/en/docs/contribute/start.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9900 --previous flag example added to the cheatsheet
  content/en/docs/reference/kubectl/cheatsheet.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9901 Pin busybox to 1.28
  content/en/examples/admin/dns/busybox.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9886 Add pod list in all namespaces example
  content/en/docs/setup/turnkey/clc.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9940 Added Note Formatting
  content/en/docs/tasks/federation/set-up-cluster-federation-kubefed.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9857 fix gc documentation
  content/en/docs/concepts/workloads/controllers/garbage-collection.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9969 fix the command output
  content/en/docs/concepts/workloads/controllers/deployment.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9965 fix the command output
  content/en/docs/concepts/workloads/controllers/replicaset.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9952 fix the command output
  content/en/docs/reference/access-authn-authz/authentication.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9946 fix the command output
  content/en/docs/tutorials/stateful-application/cassandra.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9949 fix the command output
  content/en/docs/tutorials/stateful-application/zookeeper.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9950 fix the command output
  content/en/docs/tutorials/clusters/apparmor.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9951 fix the command output
  content/en/docs/tutorials/services/source-ip.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9851 Prevent hugo's wrong yaml rendering
  content/en/docs/concepts/policy/resource-quotas.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9956 fix the command output
  content/en/docs/concepts/cluster-administration/logging.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9957 fix the command output
  content/en/docs/concepts/containers/images.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
