Repository kubernetes/website, pull requests merged in 2018-09, with the labels that each got.

#10179 Update jobs link
  content/en/docs/tasks/job/parallel-processing-expansion.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9626 docs update to promote TaintNodesByCondition to beta
  content/en/docs/concepts/architecture/nodes.md
  content/en/docs/concepts/configuration/taint-and-toleration.md
  content/en/docs/concepts/workloads/controllers/daemonset.md
  content/en/docs/reference/command-line-tools-reference/cloud-controller-manager.md
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
  content/en/docs/reference/command-line-tools-reference/federation-apiserver.md
  content/en/docs/reference/command-line-tools-reference/kube-apiserver.md
  content/en/docs/reference/command-line-tools-reference/kube-controller-manager.md
  content/en/docs/reference/command-line-tools-reference/kube-proxy.md
  content/en/docs/reference/command-line-tools-reference/kube-scheduler.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8757 HPA Specificity Improvements
  content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
  content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/L

#10180 Indicate QuickAssist support in Intel Device plugin repo
  content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10176 Update assign-cpu-resource.md
  content/en/docs/tasks/configure-pod-container/assign-cpu-resource.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10109 Fix description and update command output
  content/en/docs/tasks/administer-cluster/change-default-storage-class.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10107 use new api version of scheduling.k8s.io
  content/en/docs/concepts/configuration/pod-priority-preemption.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10087 fix url for 1.11 docs
  content/en/docs/tasks/administer-cluster/kubelet-config-file.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10136 fix the suffix in the system-reserved example
  content/en/docs/tasks/administer-cluster/reserve-compute-resources.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10198 Add an OWNERS file to /resources/
  resources/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10197 keep consistency with the kubectl commands
  content/en/docs/tasks/configure-pod-container/assign-memory-resource.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10204 column STORAGECLASS is missed
  content/en/docs/tasks/administer-cluster/change-pv-reclaim-policy.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10196 Fixed typo that combined two separate sentences without a period
  content/en/docs/concepts/containers/images.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10049 adjust docs for pod ready++
  content/en/docs/concepts/workloads/pods/pod-lifecycle.md
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10093 Improve `--requestheader-client-ca-file` warning
  content/en/docs/reference/access-authn-authz/authentication.md
  content/en/docs/reference/command-line-tools-reference/kube-apiserver.md
  content/en/docs/tasks/access-kubernetes-api/configure-aggregation-layer.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10214 Add google site verification for k8s.io DNS
  static/google2a9463bd6a902e34.html
Labels: cncf-cla: yes, size/XS

#10212 rbac: add information on unauthenticated discovery roles
  content/en/docs/reference/access-authn-authz/rbac.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10047 Updating docs to include IKS in various places
  content/en/docs/concepts/cluster-administration/cloud-providers.md
  content/en/docs/concepts/containers/images.md
  content/en/docs/setup/pick-right-solution.md
  content/en/includes/partner-script.js
  data/setup.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#10233 Add GCE PD limit link and update wording
  content/en/docs/concepts/storage/storage-limits.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10224 update storage-limits doc with Azure disk part
  content/en/docs/concepts/storage/storage-limits.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10222 Update kubelet-config-file.md
  content/en/docs/tasks/administer-cluster/kubelet-config-file.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10023 Remove --cadvisor-port - has been deprecated since v1.10
  content/en/docs/reference/command-line-tools-reference/kubelet.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
  content/en/docs/setup/custom-cloud/node.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, sig/cluster-lifecycle, sig/node, size/S

#9948 Add Documentation for Snapshot Feature
  content/en/docs/concepts/storage/persistent-volumes.md
  content/en/docs/concepts/storage/volume-snapshot-classes.md
  content/en/docs/concepts/storage/volume-snapshots.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#10033 Dry run feature documentation 1.12
  content/en/docs/reference/using-api/api-concepts.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, sig/api-machinery, sig/docs, size/M

#10062 kubeadm-init: Update the offline support section
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/M

#10157 Say bye to `DynamicProvisioningScheduling`
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10229 Update ResourceQuota per PriorityClass state for 1.12
  content/en/docs/concepts/configuration/pod-priority-preemption.md
  content/en/docs/concepts/policy/resource-quotas.md
Labels: approved, cncf-cla: yes, lgtm, sig/scheduling, size/XS

#10244 fix a trivial misspelling
  content/en/blog/_posts/2015-07-00-How-Did-Quake-Demo-From-Dockercon-Work.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10243 Fix cassandra-statefulset.yaml indent level
  content/en/examples/application/cassandra/cassandra-statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10208 Mention minimum etcd versions
  content/en/docs/setup/scratch.md
  content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10250 fix 404 error
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10190 Small verb tweak
  content/en/docs/concepts/overview/what-is-kubernetes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10200 Orient dns-autoscale toward CoreDNS
  content/en/docs/tasks/administer-cluster/dns-horizontal-autoscaling.md
  content/en/examples/admin/dns/dns-horizontal-autoscaler.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#9996 Promote ShareProcessNamespace to beta in docs
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
  content/en/docs/tasks/configure-pod-container/share-process-namespace.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10155 Add AnchorJS logic for header links
  assets/sass/_base.sass
  layouts/docs/baseof.html
  layouts/partials/head.html
  resources/_gen/assets/sass/sass/case_study_styles.sass_cb957da2191fde4902dd41b139c8069d.content
  resources/_gen/assets/sass/sass/case_study_styles.sass_cb957da2191fde4902dd41b139c8069d.json
  resources/_gen/assets/sass/sass/styles.sass_a6e533854c4de092afe9278041939937.content
  resources/_gen/assets/sass/sass/styles.sass_a6e533854c4de092afe9278041939937.json
  resources/_gen/assets/sass/sass/styles.sass_cb957da2191fde4902dd41b139c8069d.content
  resources/_gen/assets/sass/sass/styles.sass_cb957da2191fde4902dd41b139c8069d.json
  static/css/custom-jekyll/tags.css
  static/js/anchor-4.1.1.min.js
  static/js/script.js
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#10254 fix broken link in kubefed.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-init.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-join.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-options.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-unjoin.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-version.md
  content/en/docs/reference/setup-tools/kubefed/kubefed.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9827 Update version for the X-Remote-Extra- and Impersonate-Extra- key fixes
  content/en/docs/reference/access-authn-authz/authentication.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10168 fix typo
  content/en/docs/setup/independent/setup-ha-etcd-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10252 fix typos
  content/en/docs/reference/command-line-tools-reference/kubelet.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10253 fix description of contribute guide
  content/en/docs/contribute/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10219 Relocate some yaml files to the proper directory (1.10)
  content/en/docs/tasks/administer-cluster/quota-objects-pvc-2.yaml
  content/en/docs/tasks/administer-cluster/quota-objects-pvc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10220 Relocate some yaml files to the proper directory (1.11)
  content/en/docs/tasks/administer-cluster/quota-objects-pvc-2.yaml
  content/en/docs/tasks/administer-cluster/quota-objects-pvc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9780 HPA Algorithm Information Improvements
  content/en/docs/reference/glossary/quantity.md
  content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
  content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, sig/autoscaling, size/L

#10102 RuntimeClass documentation
  content/en/docs/concepts/containers/runtime-class.md
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#10048 Add documentation for Scheduler performance tuning
  content/en/docs/concepts/configuration/scheduler-perf-tuning.md
Labels: approved, cncf-cla: yes, lgtm, sig/scheduling, size/L

#10064 TTL controller for cleaning up finished resources
  content/en/docs/concepts/workloads/controllers/jobs-run-to-completion.md
  content/en/docs/concepts/workloads/controllers/ttlafterfinished.md
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, sig/apps, size/L

#10217 Bump quota configuration api version
  content/en/docs/concepts/policy/resource-quotas.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10280 Fixes from #10278
  content/en/docs/setup/independent/setup-ha-etcd-with-kubeadm.md
  content/en/docs/setup/scratch.md
  content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9923 docs update to promote ScheduleDaemonSetPods to beta
  content/en/docs/concepts/workloads/controllers/daemonset.md
  content/en/docs/reference/command-line-tools-reference/cloud-controller-manager.md
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
  content/en/docs/reference/command-line-tools-reference/kube-apiserver.md
  content/en/docs/reference/command-line-tools-reference/kube-controller-manager.md
  content/en/docs/reference/command-line-tools-reference/kube-proxy.md
  content/en/docs/reference/command-line-tools-reference/kube-scheduler.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10211 Dynamic volume limit updates for 1.12
  content/en/docs/concepts/storage/storage-limits.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9888 Add "MayRunAs" value among other GroupStrategies
  content/en/docs/concepts/policy/pod-security-policy.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10228 Add CoreDNS details to the customize DNS doc
  content/en/docs/tasks/administer-cluster/dns-custom-nameservers.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#10056 Fix secrets docs in 1.12 branch
  content/en/docs/concepts/configuration/secret.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10276 Add Katacoda Embedded Live Environment
  content/en/docs/contribute/style/style-guide.md
  content/en/docs/test.md
  layouts/shortcodes/kat-button
Labels: approved, cncf-cla: yes, lgtm, size/M, team/google

#10285 fix the command output
  content/en/docs/setup/multiple-zones.md
Labels: approved, cncf-cla: yes, lgtm, sig/cli, size/XS

#10282 Fixing example text typo
  content/en/docs/concepts/workloads/pods/pod-lifecycle.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10301 Add tfogo to OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10071 Make the home page into reusable and translatable blocks
  assets/sass/_base.sass
  assets/sass/_desktop.sass
  config.toml
  content/en/_common-resources/images/blocks.png
  content/en/_common-resources/images/flower.png
  content/en/_common-resources/images/kub_video_banner_homepage.jpg
  content/en/_common-resources/images/scalable.png
  content/en/_common-resources/images/suitcase.png
  content/en/_common-resources/index.md
  content/en/_index.html
  content/en/blog/_index.md
  content/en/case-studies/_index.html
  content/en/docs/community/_index.md
  content/en/docs/concepts/configuration/manage-compute-resources-container.md
  content/en/docs/concepts/configuration/secret.md
  content/en/docs/concepts/services-networking/service.md
  content/en/docs/concepts/storage/persistent-volumes.md
  content/en/docs/concepts/workloads/controllers/deployment.md
  content/en/docs/concepts/workloads/controllers/jobs-run-to-completion.md
  content/en/docs/concepts/workloads/controllers/replicationcontroller.md
  content/en/docs/home/_index.md
  content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
  content/en/docs/tutorials/hello-minikube.md
  content/en/docs/tutorials/kubernetes-basics/_index.html
  content/no/_common-resources/index.md
  content/no/_index.html
  content/no/case-studies/_index.md
  i18n/en.toml
  i18n/no.toml
  layouts/_default/baseof.html
  layouts/blog/baseof.html
  layouts/case-studies/single-baseof.html
  layouts/docs/baseof.html
  layouts/index.html
  layouts/partials/docs/top-menu.html
  layouts/partials/footer.html
  layouts/partials/header.html
  layouts/shortcodes/blocks/__common.html
  layouts/shortcodes/blocks/case-studies.html
  layouts/shortcodes/blocks/feature.html
  layouts/shortcodes/blocks/kubernetes-features.html
  layouts/shortcodes/blocks/section.html
  resources/_gen/assets/sass/cn/sass/styles.sass_a6e533854c4de092afe9278041939937.content
  resources/_gen/assets/sass/cn/sass/styles.sass_a6e533854c4de092afe9278041939937.json
  resources/_gen/assets/sass/sass/case_study_styles.sass_cb957da2191fde4902dd41b139c8069d.content
  resources/_gen/assets/sass/sass/case_study_styles.sass_cb957da2191fde4902dd41b139c8069d.json
  resources/_gen/assets/sass/sass/styles.sass_cb957da2191fde4902dd41b139c8069d.content
  resources/_gen/assets/sass/sass/styles.sass_cb957da2191fde4902dd41b139c8069d.json
  static/js/script.js
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#10119 Change requestheader-allowed-names to be consistent with kubeadm and other deployment tools
  content/en/docs/tasks/access-kubernetes-api/configure-aggregation-layer.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#10319 Revert CoreDNS Docs
  content/en/docs/tasks/administer-cluster/dns-custom-nameservers.md
  content/en/docs/tasks/administer-cluster/dns-debugging-resolution.md
  content/en/docs/tasks/administer-cluster/dns-horizontal-autoscaling.md
  content/en/examples/admin/dns/dns-horizontal-autoscaler.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#10318 remove duplicate stack overflow icon
  layouts/partials/footer.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10089 Adding a back button on last module
  content/en/docs/tutorials/kubernetes-basics/update/update-interactive.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9889 Cilium CNI docs for kubeadm quickstart guide
  content/en/docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, sig/docs, sig/network, size/S

#10299 Add CRI installation instructions page
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
  content/en/docs/setup/cri.md
  content/en/docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, sig/docs, size/L

#10162 Add use ipvs to kubeadm-init doc
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/XS

#10329 Linkerd 2.0 post
  content/en/blog/_posts/2018-09-18-2018-linkerd-2.0.md
  static/images/blog/2018-09-18-2018-linkerd-2.0/1-dashboard.png
  static/images/blog/2018-09-18-2018-linkerd-2.0/2-web-overview.png
  static/images/blog/2018-09-18-2018-linkerd-2.0/3-web-detail.png
  static/images/blog/2018-09-18-2018-linkerd-2.0/4-web-top.png
  static/images/blog/2018-09-18-2018-linkerd-2.0/5-web-tap.png
  static/images/blog/2018-09-18-2018-linkerd-2.0/6-grafana.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#10283 kubeadm: update API types documentation for 1.12
  content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
  content/en/docs/setup/independent/control-plane-flags.md
  content/en/docs/setup/independent/kubelet-integration.md
  content/en/docs/setup/independent/setup-ha-etcd-with-kubeadm.md
  content/en/docs/setup/independent/troubleshooting-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/L

#10251 fix 1.11 release note format
  content/en/docs/setup/release/notes.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#10295 TokenRequest feature documentation
  content/en/docs/tasks/configure-pod-container/configure-service-account.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#10156 AdvancedAuditing is now GA
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
  content/en/docs/tasks/debug-application-cluster/audit.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10332 update runtime-class.md
  content/en/docs/concepts/containers/runtime-class.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10338 Fix minor typo in 'Debugging Kubernetes nodes with crictl
  content/en/docs/tasks/debug-application-cluster/crictl.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10339 fixed link for godoc.org kublet componentconfig
  content/en/docs/setup/independent/kubelet-integration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10314 fix a 404 error page in ingress.md
  content/en/docs/tasks/administer-federation/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10346 Call out CRDs in default discovery roles
  content/en/docs/reference/access-authn-authz/rbac.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10347 Remove extra spacing in high-availability.md
  content/en/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#10300 Fix the wrong link address in kubectl-plugins.md
  content/en/docs/tasks/extend-kubectl/kubectl-plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10273 Add info about feature gates, fix formatting problem
  content/en/docs/contribute/intermediate.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9214 Fix out-of-date dns doc
  content/en/docs/tasks/administer-cluster/dns-custom-nameservers.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, sig/node, size/XS

#10099 Fix inline markup in headers, links
  content/en/docs/tasks/run-application/force-delete-stateful-set-pod.md
  content/en/docs/tasks/run-application/scale-stateful-set.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9911 add AllowedProcMountTypes and ProcMountType to docs
  content/en/docs/concepts/policy/pod-security-policy.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10306 kubeadm: add new command line reference
  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_renew.md
  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_renew_all.md
  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_renew_apiserver-etcd-client.md
  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_renew_apiserver-kubelet-client.md
  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_renew_apiserver.md
  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_renew_etcd-healthcheck-client.md
  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_renew_etcd-peer.md
  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_renew_etcd-server.md
  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_renew_front-proxy-client.md
  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_kubelet_config_annotate-cri.md
  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_experimental-control-plane.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-alpha.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-upgrade.md
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/M

#10279 Documenting SCTP support in Kubernetes
  content/en/docs/concepts/cluster-administration/proxies.md
  content/en/docs/concepts/services-networking/network-policies.md
  content/en/docs/concepts/services-networking/service.md
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#10320 Fixed anchor link for vsphereVolume session.
  content/en/docs/concepts/storage/volumes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10341 Update daemonset.md
  content/en/docs/concepts/workloads/controllers/daemonset.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10321 Replace kubernetes-users mailing list links with discuss forum link
  content/en/docs/setup/scratch.md
  content/en/docs/setup/turnkey/gce.md
  content/en/docs/tasks/debug-application-cluster/debug-service.md
  content/en/docs/tasks/debug-application-cluster/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10312 fix Dockerfile
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10313 update URL, add screenshot
  content/en/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
  static/images/docs/dynatrace.png
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10289 Fix a command error in configure-service-account.md file
  content/en/docs/tasks/configure-pod-container/configure-service-account.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10271 add a link to CCM
  content/en/docs/concepts/architecture/cloud-controller.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10232 TLS Bootstrap and Server Cert Rotation feature documentation
  content/en/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#9975 Fix Markdown on documentation for install-kubectl
  content/en/docs/tasks/tools/install-kubectl.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10258 fix broken link in content/en/docs/setup/release/notes.md
  content/en/docs/setup/release/notes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10296 Add clarifications for volume snapshots
  content/en/docs/concepts/storage/volume-snapshots.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10264 Update kubadm ha installation for 1.12
  content/en/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/L

#10343 add IBM, NAIC and Ocado case studies
  content/en/case-studies/ibm/ibm_featured_logo.png
  content/en/case-studies/ibm/index.html
  content/en/case-studies/naic/index.html
  content/en/case-studies/naic/naic_featured_logo.png
  content/en/case-studies/ocado/index.html
  content/en/case-studies/ocado/ocado_featured_logo.png
  static/images/CaseStudy_ibm_banner1.jpg
  static/images/CaseStudy_ibm_banner3.jpg
  static/images/CaseStudy_ibm_banner4.jpg
  static/images/CaseStudy_naic_banner1.jpg
  static/images/CaseStudy_naic_banner3.jpg
  static/images/CaseStudy_naic_banner4.jpg
  static/images/CaseStudy_ocado_banner1.jpg
  static/images/CaseStudy_ocado_banner3.jpg
  static/images/CaseStudy_ocado_banner4.jpg
  static/images/ibm_logo.png
  static/images/naic_logo.png
  static/images/ocado_logo.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#10357 Document how to run in-tree cloud providers with kubeadm
  content/en/docs/concepts/cluster-administration/cloud-providers.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/M

#10284 Updating docs around default ImagePullPolicy
  content/en/docs/concepts/configuration/overview.md
  content/en/docs/concepts/containers/images.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#10248 remove the left bits of salt
  content/en/docs/concepts/cluster-administration/cluster-administration-overview.md
  content/en/docs/setup/scratch.md
  content/en/examples/debug/fluentd-gcp-configmap.yaml
  data/setup.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#10123 Rework tool/doc for updating reference docs
  content/en/docs/contribute/generate-ref-docs/kubernetes-components.md
  content/en/docs/contribute/start.md
  update-imported-docs/README.md
  update-imported-docs/reference.yml
  update-imported-docs/update-imported-docs
  update-imported-docs/update-imported-docs-linux
  update-imported-docs/update-imported-docs-macos
  update-imported-docs/update-imported-docs.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#10163 Update kubespray documents
  content/en/docs/setup/custom-cloud/kubespray.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10364 Update overview.md
  content/en/docs/concepts/configuration/overview.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10374 add missing instruction for ha guide
  content/en/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10340 kubeadm - Ha upgrade updates
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-ha.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/L

#10368 update calico instructions
  content/en/docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#10315 The fix clicks the error hyperlink that 'here' appears
  content/en/blog/_posts/2016-03-00-Building-Highly-Available-Applications-Using-Kubernetes-New-Multi-Zone-Clusters-A.K.A-Ubernetes-Lite.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9784 Add default enabled admission control plugins
  content/en/docs/reference/access-authn-authz/admission-controllers.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/S

#9825 Update weave-network-policy.md -- fixing typo.
  content/en/docs/tasks/administer-cluster/network-policy-provider/weave-network-policy.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9841 Add HAProxy and istio ingress controller
  content/en/docs/concepts/services-networking/ingress.md
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/XS

#10378 Removing Okta reference
  content/en/docs/reference/access-authn-authz/authentication.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10311 Update persistent-volumes.md
  content/en/docs/concepts/storage/persistent-volumes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10034 add new turnkey cloud solution to setup: ICP on multiple clouds
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10205 update KubeletPluginsWatcher feature gate
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10358 Removing raw and endraw tags
  content/en/docs/contribute/style/page-templates.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10379 Building Multi-arch images with Manifests
  content/en/docs/concepts/containers/images.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10152 Remove unused scripts
  .travis.yml
  skip_title_check.txt
  skip_toc_check.txt
  verify-docs-format.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#10260 Make Setup Landing Page More Useful
  content/en/docs/setup/_index.md
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#10344 Upgrade docs for v1.12
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-12.md
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-8.md
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-9.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, sig/docs, size/XL

#10395 Fix typo: speficied -> specified
  content/en/docs/concepts/configuration/assign-pod-node.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10396 Update config.toml
  config.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10259 update plugin documentation under docs>tasks>extend-kubectl
  content/en/docs/tasks/extend-kubectl/kubectl-plugins.md
Labels: approved, cncf-cla: yes, lgtm, sig/cli, sig/docs, size/L

#10402 Blog post
  content/en/blog/_posts/2018-09-27-kubernetes-1.12-release-announcement.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#10403 update link location
  content/en/docs/reference/kubernetes-api/index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10410 fix typo
  content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10414 You remove the extra 'If'
  content/en/blog/_posts/2017-02-00-Postgresql-Clusters-Kubernetes-Statefulsets.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10426 Update kubectl command ref docs for 1.12.
  static/docs/reference/generated/kubectl/diff-kubectl-cmds-1.11-1.12
  static/docs/reference/generated/kubectl/kubectl-commands.html
  static/docs/reference/generated/kubectl/navData.js
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#10405 Add link to 1.12 API docs in reference index
  content/en/docs/reference/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
