Repository kubernetes/website, pull requests merged in 2018-11, with the labels that each got.

#10800 Fix secondary nav to use Home
  content/en/docs/home/_index.md
  layouts/partials/header.html
Labels: approved, cncf-cla: yes, lgtm, size/XS, team/google

#10809 Allow subfolders to inherit OWNERS from parent folders
  content/en/blog/OWNERS
  content/en/case-studies/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10781 Updated broken link to Issue Template
  content/en/docs/reference/issues-security/security.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10703 Update default 'image-gc-high-threshold'
  content/en/docs/concepts/cluster-administration/kubelet-garbage-collection.md
Labels: Needs Tech Review, approved, cncf-cla: yes, language/en, lgtm, size/XS

#10683 Add markthink to Chinese review/approver teams
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10802 Update version of Calico/Canal in kubeadm docs
  content/en/docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10799 Update naming for Azure Kubernetes Service (AKS)
  content/en/docs/setup/turnkey/azure.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10772 remove node condition ConfigOK
  content/en/docs/concepts/architecture/nodes.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10790 Describe what file to edit
  content/en/docs/getting-started-guides/fedora/fedora_manual_config.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10793 Update install-minikube.md
  content/en/docs/tasks/tools/install-minikube.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10765 docs update to promote TaintBasedEvictions to beta
  content/en/docs/concepts/configuration/taint-and-toleration.md
  content/en/docs/concepts/workloads/controllers/daemonset.md
  content/en/docs/reference/command-line-tools-reference/cloud-controller-manager.md
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
  content/en/docs/reference/command-line-tools-reference/federation-apiserver.md
  content/en/docs/reference/command-line-tools-reference/kube-apiserver.md
  content/en/docs/reference/command-line-tools-reference/kube-controller-manager.md
  content/en/docs/reference/command-line-tools-reference/kube-proxy.md
  content/en/docs/reference/command-line-tools-reference/kube-scheduler.md
  content/en/docs/reference/command-line-tools-reference/kubelet.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/scheduling, size/M

#10811 Add i18n/OWNERS
  i18n/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#10753 Update tools.md
  content/zh/docs/reference/tools.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#10768 Modified into appropriate words
  content/en/docs/setup/independent/kubelet-integration.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, language/en, lgtm, size/XS

#10611 Add i18n strings for Korean translation
  i18n/ko.toml
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10690 Translate concepts/overview/what-is-kubernetes in Korean
  content/ko/docs/concepts/overview/what-is-kubernetes.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#10883 Fix typo in word repositories
  content/en/docs/contribute/advanced.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10819 add note informing users of env var updates
  content/en/docs/tasks/extend-kubectl/kubectl-plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10877 Fix typo
  content/en/blog/_posts/2017-10-00-Five-Days-Of-Kubernetes-18.md
  content/en/blog/_posts/2018-01-00-Extensible-Admission-Is-Beta.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10884 fix word err in Disruption
  content/en/docs/concepts/workloads/pods/disruptions.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10786 Tutorial cleanup: Delete K8s 101 and 201
  content/en/docs/tutorials/k8s101.md
  content/en/docs/tutorials/k8s201.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L, team/google

#10873 clean-up minikube toc
  content/en/docs/setup/minikube.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#10797 Update tutorial to work with Katacoda, No Install
  content/en/docs/tutorials/hello-minikube.md
Labels: approved, cncf-cla: yes, lgtm, size/L, team/google

#10886 Revert "Add i18n/OWNERS"
  i18n/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S, team/google

#10892 Typo fix in docker-cli-kubectl.md
  content/zh/docs/user-guide/docker-cli-to-kubectl.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10897 fix err for kubectl: '-output' -> '--output'
  content/en/docs/reference/kubectl/overview.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10794 Update HAProxy ingress line
  content/en/docs/concepts/services-networking/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10899 Typo fix in kubeadm/implementation-details.md
  content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10882 Translate concepts/overview/components in Korean
  content/ko/docs/concepts/overview/components.md
  content/ko/docs/reference/glossary/controller.md
  content/ko/docs/reference/glossary/etcd.md
  content/ko/docs/reference/glossary/kube-apiserver.md
  content/ko/docs/reference/glossary/kube-controller-manager.md
  content/ko/docs/reference/glossary/kube-scheduler.md
  content/ko/docs/reference/glossary/kubelet.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#10773 Translate concepts/overview/kubernetes-api in Korean
  content/ko/docs/concepts/overview/kubernetes-api.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#10719 First Korean l10n work for dev-1.13
  content/ko/docs/concepts/overview/components.md
  content/ko/docs/concepts/overview/kubernetes-api.md
  content/ko/docs/concepts/overview/what-is-kubernetes.md
  content/ko/docs/reference/glossary/controller.md
  content/ko/docs/reference/glossary/etcd.md
  content/ko/docs/reference/glossary/kube-apiserver.md
  content/ko/docs/reference/glossary/kube-controller-manager.md
  content/ko/docs/reference/glossary/kube-scheduler.md
  content/ko/docs/reference/glossary/kubelet.md
  content/ko/docs/setup/independent/create-cluster-kubeadm.md
  content/ko/docs/setup/independent/high-availability.md
  content/ko/docs/setup/independent/install-kubeadm.md
  content/ko/docs/setup/minikube.md
  content/ko/docs/setup/multiple-zones.md
  content/ko/docs/setup/pick-right-solution.md
  content/ko/docs/setup/scratch.md
  content/ko/docs/tutorials/hello-minikube.md
  content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
  content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
  content/ko/examples/minikube/Dockerfile
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/XL

#10901 Fix formatting of Kubernetes Meets High Performance blog post
  content/en/blog/_posts/2017-08-00-Kubernetes-Meets-High-Performance.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10792 Update officially supported client libraries
  content/en/docs/reference/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10891 add "grpc load balancing on kubernetes without tears" blog post
  content/en/blog/_posts/grpc-load-balancing-with-linkerd.md
  static/images/blog/grpc-load-balancing-with-linkerd/Linkerd-8df1031c-cdd1-4164-8e91-00f2d941e93f.io.png
  static/images/blog/grpc-load-balancing-with-linkerd/Mono-8d2e53ef-b133-4aa0-9551-7e36a880c553.png
  static/images/blog/grpc-load-balancing-with-linkerd/Screenshot2018-11-0116-24b8ee81-144c-4eac-b73d-871bbf0ea22e.57.42.png
  static/images/blog/grpc-load-balancing-with-linkerd/Screenshot2018-11-0116-c4d86100-afc1-4a08-a01c-16da391756dd.34.36.png
  static/images/blog/grpc-load-balancing-with-linkerd/Screenshot2018-11-0212-15ed0448-5424-4e47-9828-20032de868b5.08.38.png
  static/images/blog/grpc-load-balancing-with-linkerd/Stereo-09aff9d7-1c98-4a0a-9184-9998ed83a531.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#10921 Fix some typos
  content/zh/docs/tasks/manage-gpus/scheduling-gpus.md
  content/zh/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10919 Correct formatting of note on creating a secret.
  content/en/docs/tasks/inject-data-application/distribute-credentials-secure.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10915 Update outdated l10n(ko) contents
  content/ko/docs/concepts/overview/kubernetes-api.md
  content/ko/docs/home/_index.md
  content/ko/docs/setup/independent/troubleshooting-kubeadm.md
  content/ko/docs/setup/multiple-zones.md
  content/ko/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10294 Added feature-gates deprecation guidelines and policy as per discussi…
  content/en/docs/reference/using-api/deprecation-policy.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/architecture, size/M

#10920 Remove redundant "Note:" prefixes
  content/en/docs/concepts/workloads/controllers/deployment.md
  content/ko/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#10918 kubectl overview, toc clean-up
  content/en/docs/reference/kubectl/overview.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#10907 Rename experimental-bootstrap-token-auth to enable-bootstrap-token-auth
  content/en/docs/reference/access-authn-authz/authentication.md
  content/zh/docs/admin/bootstrap-tokens.md
  content/zh/docs/admin/kube-apiserver.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10908 Update Kompose version
  content/en/docs/tasks/configure-pod-container/translate-compose-kubernetes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10905 Fix wrong parameters
  content/en/docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10874 Add blog post for l10n update
  content/en/blog/_posts/2018-11-08-kubernetes-docs-update-i18n.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#10887 Fix numbered lists
  content/en/docs/tutorials/hello-minikube.md
Labels: approved, cncf-cla: yes, lgtm, size/L, team/google

#10925 Fix typos: functionizing -> functionalizing
  content/en/docs/sitemap.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10933 Remove redundant feature state
  content/en/docs/concepts/configuration/pod-priority-preemption.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10916 Translate main menu for l10n(ko) docs
  content/ko/case-studies/_index.html
  content/ko/docs/_index.md
  content/ko/docs/reference/_index.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/M

#10900 This PR adds VMware Cloud PKS to the list of hosted solutions, and a link to documentation to the list of IaaS Providers.
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10947 Fix typos: kubele -> kubelet
  content/zh/docs/concepts/architecture/master-node-communication.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#10943 Fix issues in content
  content/en/docs/concepts/policy/pod-security-policy.md
  content/en/docs/tasks/extend-kubectl/kubectl-plugins.md
  content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
Labels: approved, cncf-cla: yes, language/en, language/zh, lgtm, size/XS

#10745 zh_trans_docs_concepts_index_1.10
  content/zh/docs/concepts/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#10746 zh_trans_docs_concepts_index_1.11
  content/zh/docs/concepts/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#10747 zh-trans_docs_concepts_index_1.12
  content/zh/docs/concepts/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#10744 zh_trans_docs_concepts_index
  content/zh/docs/concepts/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#10724 Disable line wrapping of base64 output
  content/en/docs/reference/kubectl/cheatsheet.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10909 Update for clarity
  content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10952 add missing images in the Chinese homepage
  content/zh/_index.html
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#10959 kubeadm: update the configuration docs to v1beta1
  content/en/docs/concepts/cluster-administration/cloud-providers.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
  content/en/docs/setup/independent/control-plane-flags.md
  content/en/docs/setup/independent/high-availability.md
  content/en/docs/setup/independent/setup-ha-etcd-with-kubeadm.md
  content/en/docs/setup/independent/troubleshooting-kubeadm.md
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-ha.md
  content/ko/docs/setup/independent/control-plane-flags.md
  content/ko/docs/setup/independent/high-availability.md
  content/ko/docs/setup/independent/setup-ha-etcd-with-kubeadm.md
  content/ko/docs/setup/independent/troubleshooting-kubeadm.md
Labels: approved, cncf-cla: yes, kind/cleanup, language/en, language/ko, lgtm, priority/important-soon, sig/cluster-lifecycle, size/L

#10977 Modify top comment in zh.toml
  i18n/zh.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10976 Add Chinese language alternatives setting
  config.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10988 kubeadm: add small v1beta1 related updates
  content/en/docs/setup/independent/high-availability.md
  content/ko/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/bug, language/en, language/ko, lgtm, sig/cluster-lifecycle, size/M

#10967 Corrected a minor issue in linking to Slack
  content/en/docs/contribute/participating.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10924 Use absolute URLs and avoid aliases in the tutorial
  content/en/docs/tutorials/kubernetes-basics/_index.html
  content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
  content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
  content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
  content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
  content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
  content/en/docs/tutorials/kubernetes-basics/explore/explore-intro.html
  content/en/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
  content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html
  content/en/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
  content/en/docs/tutorials/kubernetes-basics/scale/scale-intro.html
  content/en/docs/tutorials/kubernetes-basics/update/update-intro.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#10885 Rename 'Reusing Docker' section for minikube documentation
  content/en/docs/setup/minikube.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10912 Fix the link to repo kubernetes/cloud-provider
  content/en/docs/tasks/administer-cluster/developing-cloud-controller-manager.md
  content/en/docs/tasks/administer-cluster/running-cloud-controller.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10941 Remove unnecessary kubelet as upgraded package
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-12.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10895 Mark ‘rkt’ as deprecated for '--container-runtime'
  content/en/docs/reference/command-line-tools-reference/kubelet.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10810 Fix Makefile and README for make docker-serve on Windows
  Makefile
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10760 Update debug-service.md
  content/en/docs/tasks/debug-application-cluster/debug-service.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11002 Fix instructions to start minikube with RBAC
  content/en/docs/setup/minikube.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10939 clean up conventions toc
  content/en/docs/reference/kubectl/conventions.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10993 Fix typo in website documention
  content/en/docs/concepts/workloads/controllers/deployment.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10991 Add KodeKloud online training for CKAD Preparation course
  content/en/docs/tutorials/online-training/overview.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10990 Minor change
  content/en/docs/contribute/style/page-templates.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10983 Kubernetes Repository URL HTTPS
  content/en/docs/tasks/tools/install-kubectl.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10982 Fix missing selector subcommand
  content/en/docs/concepts/overview/object-management-kubectl/imperative-command.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10731 Fix 3 links that were pointing at blog.kubernetes.io
  content/en/blog/_posts/2018-07-18-11-ways-not-to-get-hacked.md
  content/en/docs/concepts/workloads/pods/pod-overview.md
  content/zh/docs/concepts/services-networking/connect-applications-service.md
  content/zh/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume.md
Labels: approved, cncf-cla: yes, language/en, language/zh, lgtm, size/XS

#11009 Update 2016-07-00-Cross-Cluster-Services.md，fix 404
  content/en/blog/_posts/2016-07-00-Cross-Cluster-Services.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11008 cleanup k8s101/201 resource left
  content/en/docs/user-journeys/users/application-developer/foundational.md
  content/en/docs/user-journeys/users/cluster-operator/foundational.md
  data/tutorials.yml
  static/_redirects
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#11003 Copy-edit based on the style guide
  content/en/docs/contribute/style/hugo-shortcodes/index.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10963 fix bad request for community file
  data/user-personas/contributors/code-contributor.yaml
  data/user-personas/contributors/community-contributor.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10966 Copy-edit
  content/en/docs/contribute/_index.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10970 Update NVIDIA GPU instructions for GCP
  content/en/docs/tasks/manage-gpus/scheduling-gpus.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10992 Update kubespray.md
  content/en/docs/setup/custom-cloud/kubespray.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10996 Add Korean language alternatives setting
  config.toml
Labels: approved, cncf-cla: yes, lgtm, size/S

#10948 Adding name arguement in kubeadm-config.yaml
  content/en/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11021 Minor updates
  content/en/docs/tutorials/hello-minikube.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#11020 Fix an error in custom-resources.md
  content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11025 fix typo error: Paricipate -> Participate
  content/en/blog/_posts/2015-03-00-Participate-In-Kubernetes-User.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#9970 fix advanced audit config format
  content/en/docs/tasks/debug-application-cluster/audit.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10531 Fix customized CSS for case study
  static/css/style_amadeus.css
  static/css/style_ancestry.css
  static/css/style_blablacar.css
  static/css/style_blackrock.css
  static/css/style_box.css
  static/css/style_buffer.css
  static/css/style_crowdfire.css
  static/css/style_golfnow.css
  static/css/style_haufegroup.css
  static/css/style_huawei.css
  static/css/style_peardeck.css
  static/css/style_wink.css
  static/css/style_zalando.css
Labels: approved, cncf-cla: yes, kind/bug, kind/design, language/en, lgtm, size/XL

#10561 Remove resources folder from Git
  .gitignore
  resources/_gen/assets/sass/cn/sass/styles.sass_a6e533854c4de092afe9278041939937.content
  resources/_gen/assets/sass/cn/sass/styles.sass_a6e533854c4de092afe9278041939937.json
  resources/_gen/assets/sass/sass/styles.sass_a6e533854c4de092afe9278041939937.content
  resources/_gen/assets/sass/sass/styles.sass_a6e533854c4de092afe9278041939937.json
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XXL

#11010 Fix some errors in kubelet.md
  content/en/docs/reference/command-line-tools-reference/kubelet.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10938 Added documentation about stringData
  content/en/docs/concepts/configuration/secret.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L

#10923 Update documentation on CoreDNS
  content/en/docs/concepts/services-networking/connect-applications-service.md
  content/en/docs/setup/independent/troubleshooting-kubeadm.md
  content/en/docs/setup/turnkey/gce.md
  content/en/docs/tasks/administer-cluster/coredns.md
  content/en/docs/tasks/administer-cluster/dns-custom-nameservers.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10958 rewrite of ingress
  content/en/docs/concepts/services-networking/ingress.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L

#10625 Rename blog entries as workaround for content types
  content/en/blog/_posts/2016-03-00-Building-Highly-Available-Applications-Using-Kubernetes-New-Multi-Zone-Clusters-aka-Ubernetes-Lite.md
  content/en/blog/_posts/2016-03-00-Kubernetes-1-2-And-Simplifying-Advanced-Networking-With-Ingress.md
  content/en/blog/_posts/2016-03-00-Kubernetes-1-2-Even-More-Performance-Upgrades-Plus-Easier-Application-Deployment-And-Management-.md
  content/en/blog/_posts/2016-07-00-Five-Days-Of-Kubernetes-1-3.md
  content/en/blog/_posts/2016-07-00-Kubernetes-1-3-Bridging-Cloud-Native-And-Enterprise-Workloads.md
  content/en/blog/_posts/2016-09-00-Kubernetes-1-4-Making-It-Easy-To-Run-On-Kuberentes-Anywhere.md
  content/en/blog/_posts/2016-10-00-Production-Kubernetes-Dashboard-UI-1-4-improvements_3.md
  content/en/blog/_posts/2016-12-00-Cluster-Federation-In-Kubernetes-1-5.md
  content/en/blog/_posts/2016-12-00-Five-Days-Of-Kubernetes-1-5.md
  content/en/blog/_posts/2016-12-00-Kubernetes-1-5-Supporting-Production-Workloads.md
  content/en/blog/_posts/2017-03-00-Five-Days-Of-Kubernetes-1-6.md
  content/en/blog/_posts/2017-03-00-Kubernetes-1-6-Multi-User-Multi-Workloads-At-Scale.md
  content/en/blog/_posts/2017-03-00-Scalability-Updates-In-Kubernetes-1-6.md
  content/en/blog/_posts/2017-06-00-Kubernetes-1-7-Security-Hardening-Stateful-Application-Extensibility-Updates.md
  content/en/blog/_posts/2018-03-26-kubernetes-1-10-stabilizing-storage-security-networking.md
  content/en/blog/_posts/2018-05-04-Announcing-Kubeflow-0-1.md
  content/en/blog/_posts/2018-06-26-kubernetes-1-11-release-announcement.md
  content/en/blog/_posts/2018-07-16-kubernetes-1-11-release-interview.md
  content/en/blog/_posts/2018-09-18-2018-linkerd-2-0.md
  content/en/blog/_posts/2018-09-27-kubernetes-1-12-release-announcement.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10714 update ol ul li bullet to disc
  content/en/docs/setup/independent/high-availability.md
  sass/_base.sass
  static/css/case-study-styles.css
  static/css/styles.css
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XXL

#11031 ADD content/zh/docs/reference/setup-tools/kubeadm/kubeadm.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md
  content/zh/docs/reference/setup-tools/kubeadm/kubeadm.md
Labels: cncf-cla: yes, language/zh, lgtm, size/L

#11011 Change `ReplicationController` to `ReplicaSets`
  content/zh/docs/concepts/services-networking/service.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#11034 kubeadm reference two file
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md
  content/zh/docs/reference/setup-tools/kubeadm/kubeadm.md
Labels: cncf-cla: yes, language/zh, lgtm, size/L

#10817 ZTE-SH-CN-delete-stateful-set
  content/zh/docs/tasks/run-application/delete-stateful-set.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11036 Typo fix "availabe" -> "available"
  content/en/blog/_posts/2016-11-00-Bringing-Kubernetes-Support-To-Azure.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11057 zh_trans: add job/_index.md
  content/zh/docs/tasks/job/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11055 zh_trans: add federation/_index.md
  content/zh/docs/tasks/federation/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11052 zh_trans: add configure-pod-container/_index.md
  content/zh/docs/tasks/configure-pod-container/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11056 zh_trans: add inject-data-application/_index.md
  content/zh/docs/tasks/inject-data-application/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S, tide/squash

#11051 zh_trans: add dminister-federation/_index.md
  content/zh/docs/tasks/administer-federation/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S, tide/squash

#11038 Update download and extraction notes
  content/en/docs/setup/scratch.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11054 zh_trans: add debug-application-cluster/_index.md
  content/zh/docs/tasks/debug-application-cluster/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S, tide/squash

#10583 add examples using "rollout"
  content/en/docs/reference/kubectl/cheatsheet.md
Labels: Needs Tech Review, approved, cncf-cla: yes, language/en, lgtm, size/S

#10541 Fixing yaml
  content/en/docs/tasks/manage-hugepages/scheduling-hugepages.md
Labels: Needs Tech Review, approved, cncf-cla: yes, language/en, lgtm, size/XS

#10594 Redirect to decoding a secret
  content/en/docs/tasks/administer-cluster/encrypt-data.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, language/en, lgtm, size/XS

#10606 Use hugo in Travis CI pipeline
  .travis.yml
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#11061 zh_trans:kubeadm_alpha_phase_addon.md
  content/cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_addon.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#11067 zh_trans:kubeadm_alpha_phase_kubeconfig_user.md
  content/cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_kubeconfig_user.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11071 Revert "zh_trans_kubeadm_alpha_phase_selfhosting.md"
  content/cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_selfhosting.md
Labels: cncf-cla: yes, size/M

#11072 Revert "zh_trans:kubeadm_alpha_phase_addon.md"
  content/cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_addon.md
Labels: cncf-cla: yes, size/M

#11073 Manual revert 11067
  content/cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_kubeconfig_user.md
Labels: cncf-cla: yes, size/L

#11049 zh_trans: add network-policy-provider/_index.md
  content/zh/docs/tasks/administer-cluster/network-policy-provider/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11075 Fix some errors in certificates.md
  content/en/docs/concepts/cluster-administration/certificates.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11044 zh-trans:Add manage-resources/memory-default-namespace.md
  content/zh/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
  content/zh/examples/admin/resource/memory-defaults-pod-2.yaml
  content/zh/examples/admin/resource/memory-defaults-pod-3.yaml
  content/zh/examples/admin/resource/memory-defaults-pod.yaml
  content/zh/examples/admin/resource/memory-defaults.yaml
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L, tide/squash

#11043 zh-trans: Add manage-resources/cpu-default-namespace.md
  content/zh/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace.md
  content/zh/examples/admin/resource/cpu-defaults-pod-2.yaml
  content/zh/examples/admin/resource/cpu-defaults-pod-3.yaml
  content/zh/examples/admin/resource/cpu-defaults-pod.yaml
  content/zh/examples/admin/resource/cpu-defaults.yaml
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L, tide/squash

#10743 Doc updates for volume scheduling GA
  content/en/docs/concepts/storage/storage-classes.md
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10699 Document nodelease feature
  content/en/docs/concepts/architecture/nodes.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/node, size/S

#10722 add a missing step in kubeadm-upgrade flow.
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-ha.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/XS

#11066 making list of hosts under TLS more explicit
  content/en/docs/concepts/services-networking/ingress.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11028 fix typo and update punctuation
  content/en/blog/_posts/2015-04-00-Weekly-Kubernetes-Community-Hangout_11.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#11032 Reorder concepts sections
  content/en/docs/concepts/cluster-administration/_index.md
  content/en/docs/concepts/configuration/_index.md
  content/en/docs/concepts/containers/_index.md
  content/en/docs/concepts/extend-kubernetes/_index.md
  content/en/docs/concepts/policy/_index.md
  content/en/docs/concepts/services-networking/_index.md
  content/en/docs/concepts/storage/_index.md
  content/en/docs/concepts/workloads/_index.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10203 advanced audit doc for ModeBlockingStrict
  content/en/docs/tasks/debug-application-cluster/audit.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11081 zh-trans: add overview/_index.md
  content/zh/docs/concepts/overview/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11078 zh-trans: add api-extension/_index.md
  content/zh/docs/concepts/extend-kubernetes/api-extension/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11077 zh-trans: add extend-kubernetes/_index.md
  content/zh/docs/concepts/extend-kubernetes/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11079 zh-trans: add compute-storage-net/_index.md
  content/zh/docs/concepts/extend-kubernetes/compute-storage-net/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11096 fix typo ref contrib
  content/en/docs/contribute/generate-ref-docs/kubernetes-components.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#11083 zh-trans: add object-management-kubectl/_index.md
  content/zh/docs/concepts/overview/object-management-kubectl/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11088 zx-trans: add workloads/_index.md
  content/zh/docs/concepts/workloads/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11090 zx-trans: add pods/_index.md
  content/zh/docs/concepts/workloads/pods/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11097 zh_trans:kubeadm_alpha_phase_controlplane.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_controlplane.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#11086 zh-trans: add services-networking/_index.md
  content/zh/docs/concepts/services-networking/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S, tide/squash

#11089 zh-trans: add workloads/controllers/_index
  content/zh/docs/concepts/workloads/controllers/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11087 zh-trans: add storage/_index.md
  content/zh/docs/concepts/storage/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11042 zh-trans: Add manage-resources/cpu-constraint-namespace.md
  content/zh/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace.md
  content/zh/examples/admin/resource/cpu-constraints-pod-2.yaml
  content/zh/examples/admin/resource/cpu-constraints-pod-3.yaml
  content/zh/examples/admin/resource/cpu-constraints-pod-4.yaml
  content/zh/examples/admin/resource/cpu-constraints-pod.yaml
  content/zh/examples/admin/resource/cpu-constraints.yaml
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XL, tide/squash

#11102 Improve overall sentence clearness and understanding
  content/en/docs/concepts/services-networking/service.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11080 [zh][dev-1.13] Rename EncryptionConfig to EncryptionConfiguration
  content/zh/docs/tasks/administer-cluster/encrypt-data.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11058 zh_trans: add automated-tasks-with-cron-jobs.md
  content/zh/docs/tasks/job/automated-tasks-with-cron-jobs.md
  content/zh/examples/application/job/cronjob.yaml
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11105 yaml code formatting fix for v1.12.0-rc.1 changelog
  content/en/docs/setup/release/notes.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L

#11099 zh-trans content/en/docs/setup/independent/install-kubeadm.md
  content/zh/docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11045 zh-trans: add memory-constraint-namespace.md
  content/zh/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace.md
  content/zh/examples/admin/resource/memory-constraints-pod-2.yaml
  content/zh/examples/admin/resource/memory-constraints-pod-3.yaml
  content/zh/examples/admin/resource/memory-constraints-pod-4.yaml
  content/zh/examples/admin/resource/memory-constraints-pod.yaml
  content/zh/examples/admin/resource/memory-constraints.yaml
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XL, tide/squash
