Repository kubernetes/website, pull requests merged in 2018-06, with the labels that each got.

#8714 Regional PD documentation
  content/en/docs/concepts/storage/storage-classes.md
  content/en/docs/concepts/storage/volumes.md
  test/examples_test.go
Labels: Docs LGTM, Tech Review LGTM, approved, cncf-cla: yes, lgtm, size/M

#8806 Changing Homepage Images for Upcoming KubeCon
  content/en/_index.html
  static/css/styles.css
  static/images/KubeCon_EU_Community.jpg
  static/images/kub_video_banner_box.jpg
  static/images/kub_video_banner_homepage.jpg
Labels: approved, cncf-cla: yes, lgtm, size/S

#8617 kubeadm-upgrade.md: include a generated page about 'diff' and adjust notes
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-upgrade.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/XS

#8867 Removes unnecessary SkyDNS references in preparation for CoreDNS change.
  content/en/docs/concepts/cluster-administration/cluster-administration-overview.md
  content/en/docs/concepts/services-networking/connect-applications-service.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8831 Fix: unifying .spec spelling in concepts/workloads/pods
  content/en/docs/concepts/workloads/pods/disruptions.md
  content/en/docs/concepts/workloads/pods/init-containers.md
  content/en/docs/concepts/workloads/pods/podpreset.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8733 [mod] API overview link is dead
  content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
  content/en/docs/concepts/overview/what-is-kubernetes.md
  content/en/docs/reference/_index.md
  content/en/docs/reference/using-api/client-libraries.md
  content/en/docs/reference/using-api/deprecation-policy.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8734 [mod] Client library link is dead
  content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
  content/en/docs/concepts/overview/working-with-objects/kubernetes-objects.md
  content/en/docs/getting-started-guides/clc.md
  content/en/docs/reference/_index.md
  content/en/docs/reference/using-api/api-overview.md
  content/en/docs/tasks/access-application-cluster/access-cluster.md
  content/en/docs/tasks/administer-cluster/access-cluster-api.md
  content/en/docs/user-journeys/users/application-developer/advanced.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8737 StorageOS example dead link
  content/en/docs/concepts/storage/volumes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8741 kube-router document is moved (dead link)
  content/en/docs/tasks/administer-cluster/network-policy-provider/kube-router-network-policy.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8771 Update the version of echoserver
  content/en/docs/getting-started-guides/minikube.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8849 Remove legacy syntax from federation-current-state.md
  content/en/includes/federation-current-state.md
Labels: Needs Docs Review, approved, cncf-cla: yes, lgtm

#8870 update 1.11 --server-print info
  content/en/docs/reference/kubectl/overview.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8375 Fix command to install weavenet plugin
  content/en/docs/setup/independent/create-cluster-kubeadm.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/XS

#8376 Mention this guide requires only 1 master node
  content/en/docs/setup/independent/create-cluster-kubeadm.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/XS

#8869 Update dind link on reviewing content
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8859 Link to Profiling_with_tools was 404
  content/en/docs/tutorials/clusters/apparmor.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8854 fix direct link in docs/concepts/configuration/pod-priority-preemption
  content/en/docs/concepts/configuration/pod-priority-preemption.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8847 change section position to make it alphabetical
  content/en/docs/concepts/cluster-administration/networking.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8832 Typo fix: propogating -> propagating
  static/docs/reference/generated/kubectl/scroll.js
  static/docs/reference/generated/kubernetes-api/v1.10/scroll.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8785 fix a collapsed sentence
  layouts/docs/docsportal_home.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8778 Mark ExpandPersistentVolumes feature to beta
  config.toml
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8876 Space inside href text resembles a period on "scale-intro" page
  content/en/docs/tutorials/kubernetes-basics/scale/scale-intro.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8879 fix wrong redirect of the admission-webhook
  content/en/docs/reference/access-authn-authz/extensible-admission-controllers.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8882 Remove quota for service type.
  content/en/docs/concepts/services-networking/service.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8540 Fix errors in configure-multiple-schedulers.md
  content/en/docs/tasks/administer-cluster/configure-multiple-schedulers.md
  content/en/docs/tasks/administer-cluster/my-scheduler.yaml
  test/examples_test.go
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, sig/scheduling, size/S

#8887 remove kubectl overview link repeat
  content/en/docs/user-guide/walkthrough/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8884 Typo fix: contraints -> constraints
  content/en/docs/getting-started-guides/ubuntu/operational-considerations.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8797 Fix some issues with ToC
  layouts/partials/templates/blocks.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8656 Typo fix: DeamonSets->DaemonSets/kubeclt->kubectl/hopefuly->hopefully
  content/en/blog/_posts/2015-11-00-Monitoring-Kubernetes-With-Sysdig.md
  content/en/blog/_posts/2015-12-00-Creating-Raspberry-Pi-Cluster-Running.md
  content/en/blog/_posts/2016-11-00-Kubernetes-Containers-Logging-Monitoring-With-Sematext.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8899 Hugo: Fix getting-started-guides/scratch.md
  content/en/docs/getting-started-guides/scratch.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8746 fix some unsatisfied.
  content/en/docs/tasks/run-application/mysql-deployment.yaml
  content/en/docs/tasks/run-application/mysql-pv.yaml
  content/en/docs/tasks/run-application/run-single-instance-stateful-application.md
  test/examples_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8830 add date blog metadata for indexing
  content/en/blog/_posts/2018-03-26-kubernetes-1.10-stabilizing-storage-security-networking.md
  content/en/blog/_posts/2018-04-11-migrating-the-kubernetes-blog.md
  content/en/blog/_posts/2018-04-24-kubernetes-application-survey-results-2018.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8748 update kubectl convert link
  content/en/blog/_posts/2018-01-00-Core-Workloads-Api-Ga.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8598 Add figure shortcode example to smoke tests
  content/en/docs/test.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/S

#8861 Format invalid date in blog posts
  content/en/blog/_posts/2018-03-26-kubernetes-1.10-stabilizing-storage-security-networking.md
  content/en/blog/_posts/2018-04-11-migrating-the-kubernetes-blog.md
  content/en/blog/_posts/2018-04-24-kubernetes-application-survey-results-2018.md
  content/en/blog/_posts/2018-05-24-kubernetes-containerd-integration-goes-ga.md
  content/en/blog/_posts/2018-05-30-say-hello-to-discuss-kubernetes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, triage/duplicate

#8722 update openebs logo for partner page
  static/images/square-logos/openebs.png
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8891 replace deprecated TOC style (#8890)
  content/en/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
  content/en/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8850 SupportIPVSProxyMode is GA
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8906 Rescheduler Doc changes
  content/en/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8611 uses file path not url when creating configmap
  content/en/docs/tasks/configure-pod-container/configmap/kubectl/game-env-file.properties
  content/en/docs/tasks/configure-pod-container/configmap/kubectl/ui-env-file.properties
  content/en/docs/tasks/configure-pod-container/configure-pod-configmap.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8885 Remove code blocks from h2 subject
  content/en/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8610 Fix responsive around sidebar on blog
  layouts/blog/baseof.html
  static/css/blog.css
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/M

#8866 Fix duplicated blog post file and move it to the proper directory
  content/en/blog/_posts/2018-05-04-Announcing-Kubeflow-0.1.md
  content/en/blog/_posts/2018-05-04-announcing-kubeflow-0.1.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8742 "Getting started gce" deadlink
  content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8728 kubeadm: update info about CoreDNS in kubeadm-init.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/S

#8839 Fix: some direct link in docs/concepts/configuration/secret
  content/en/docs/concepts/configuration/secret.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8829 kubeadm: update implementation-details.md about CoreDNS
  content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/S

#8935 4 Years of K8s Blog Post
  content/en/blog/_posts/2018-06-06-4-years-of-k8s.md
  static/images/blog/2018-06-06-4-years-of-k8s/k8s-first-commit.png
Labels: approved, cncf-cla: yes, lgtm, size/S

#8865 Blog Post: Dynamic Ingress in Kubernetes
  content/en/blog/_posts/2018-06-01-dynamic-ingress-kubernetes.md
  static/images/blog/2018-06-01-dynamic-ingress-kubernetes/kubeflow-ambassador.png
  static/images/blog/2018-06-01-dynamic-ingress-kubernetes/kubeflow.png
Labels: approved, cncf-cla: yes, lgtm, size/M

#8933 Move walkthroughs from user-guide to tutorials.
  content/en/docs/tutorials/deployment-update.yaml
  content/en/docs/tutorials/deployment.yaml
  content/en/docs/tutorials/k8s101.md
  content/en/docs/tutorials/k8s201.md
  content/en/docs/tutorials/pod-nginx-with-label.yaml
  content/en/docs/tutorials/pod-nginx.yaml
  content/en/docs/tutorials/pod-redis.yaml
  content/en/docs/tutorials/pod-with-http-healthcheck.yaml
  content/en/docs/tutorials/pod-with-tcp-socket-healthcheck.yaml
  content/en/docs/tutorials/service.yaml
  content/en/docs/user-guide/OWNERS
  content/en/docs/user-guide/_index.md
  content/en/docs/user-guide/walkthrough/OWNERS
  static/_redirects
  test/examples_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8712 Fix personal-data description is not displayed
  layouts/docs/docsportal_home.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8765 Remove GCE references from service-access-application-cluster.md
  content/en/docs/tasks/access-application-cluster/service-access-application-cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8954 Fix video overlay bug and other CSS issues with case studies
  content/en/case-studies/blablacar.html
  content/en/case-studies/newyorktimes.html
  static/css/style_blablacar.css
  static/css/style_case_studies.css
Labels: approved, cncf-cla: yes, lgtm, size/XL

#8824 Add a SECURITY_CONTACTS file
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#8820 Make path more explicit for blog images
  content/en/docs/home/contribute/blog-post.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8622 Fix list examples and CSS
  content/en/docs/test.md
  static/css/styles.css
Labels: Needs Tech Review, approved, cncf-cla: yes, lgtm, size/L

#8631 Fix column rendering in Browse section of /docs/home/
  layouts/partials/docs/browse.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8895 Update block device support for 1.11
  content/en/docs/concepts/storage/persistent-volumes.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8908 Updating KubeCon banners on Community page
  layouts/community/list.html
  static/images/kubecon_china_ad_2.jpg
  static/images/kubecon_na_ad_2.jpg
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8809 Auto-assign blog PRs to kbarnard10
  content/en/blog/OWNERS
  content/en/case-studies/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8928 update squarespace case study
  content/en/case-studies/squarespace.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8754 Fix typos and remove spelling suggestions in Gardener blog
  content/en/blog/_posts/2018-05-17-gardener-the-kubernetes-botanist.md
  static/images/blog/2018-05-17-gardener-the-kubernetes-botanist/architecture.png
Labels: approved, blog-needs-review, cncf-cla: yes, lgtm, size/XS

#8957 Fix typo 'fiber channel'
  content/en/docs/concepts/storage/persistent-volumes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8955 Update contribute button on footer
  layouts/partials/footer.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8962 Fixing Date Format on Blog Post
  content/en/blog/_posts/2018-06-07-dynamic-ingress-kubernetes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8960 kubeadm-upgrade: add the 'node [config]' sub-command
  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node.md
  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_config.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-upgrade.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/S

#8949 fix the spastic buttons
  static/css/style_user_journeys.css
Labels: approved, cncf-cla: yes, lgtm, size/S

#8966 fix id about joining-your-nodes in create-cluster-kubeadm page(rebase new master)
  content/en/docs/getting-started-guides/windows/_index.md
  content/en/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8936 Move tools to reference section.
  content/en/docs/reference/tools.md
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/S

#8983 Typo: you -> your
  content/en/docs/home/contribute/create-pull-request.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8947 Add HTML Open Graph tags
  layouts/partials/head.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8986 Add kubeadm docs to config file.
  update-imported-docs/reference.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8958 kubeadm-init: update the example for the MasterConfiguration
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/cluster-lifecycle, size/L

#8948 Move on-prem vm from g-s-guides to setup.
  content/en/docs/setup/on-premises-vm/_index.md
  content/en/docs/setup/on-premises-vm/cloudstack.md
  content/en/docs/setup/on-premises-vm/dcos.md
  content/en/docs/setup/on-premises-vm/ovirt.md
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8998 Fix tocs and template in docs/home/contribute
  content/en/docs/home/contribute/content-organization.md
  content/en/docs/home/contribute/localization.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8729 service catalog: add doc fixes
  content/en/docs/concepts/extend-kubernetes/service-catalog.md
  content/en/docs/tasks/service-catalog/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8663 Fix list formatting in kubeadm setup tutorial
  content/en/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8541 Issue #8493 - Missing instructions in "Creating HA clusters with kube…
  content/en/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8917 kubeadm: update section about CA certs in high-availability.md
  content/en/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#8910 kubeadm: add a notice on architecture different nodes
  content/en/docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#9005 Fix destination paths.
  update-imported-docs/reference.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#8918 Update CRD subresources doc for 1.11
  content/en/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8979 fix max container back off cap
  content/en/docs/concepts/workloads/controllers/jobs-run-to-completion.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8999 Fix docs/tasks page TOC
  content/en/docs/tasks/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8995 Apply concept template to extend-k8s and configuration concepts
  content/en/docs/concepts/configuration/assign-pod-node.md
  content/en/docs/concepts/configuration/secret.md
  content/en/docs/concepts/configuration/taint-and-toleration.md
  content/en/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
  content/en/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases.md
  content/en/docs/concepts/services-networking/connect-applications-service.md
  content/en/docs/concepts/services-networking/ingress.md
  content/en/docs/concepts/services-networking/network-policies.md
  content/en/docs/concepts/services-networking/service.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#8896 Add docs for volume expansion and online resizing
  content/en/docs/concepts/storage/persistent-volumes.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8826 Update exec plugin docs with TLS credentials
  content/en/docs/reference/access-authn-authz/authentication.md
Labels: Docs LGTM, Needs Tech Review, approved, cncf-cla: yes, lgtm, size/M

#8837 Update determine-reason-pod-failure.md
  content/en/docs/tasks/debug-application-cluster/determine-reason-pod-failure.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8851 Add Gardener as turnkey solution
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8873 Add details about cloud provider node name computation
  content/en/docs/concepts/cluster-administration/cloud-providers.md
Labels: approved, cncf-cla: yes, lgtm, sig/aws, sig/azure, sig/docs, sig/gcp, sig/openstack, size/M

#8875 document volume scheduler role
  content/en/docs/reference/access-authn-authz/rbac.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8844 Add a note regarding escaping characters
  content/en/docs/concepts/configuration/secret.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8888 Fix kubectl in centos default not install bash-completion
  content/en/docs/tasks/tools/install-kubectl.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8952 Move 2 topics from g-s-guides to setup.
  content/en/docs/setup/minikube.md
  content/en/docs/setup/scratch.md
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8942 Fix:change direct link to relative and not the redirect link
  content/en/docs/concepts/configuration/manage-compute-resources-container.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8911 NodeRestriction admission prevents kubelet taint removal
  content/en/docs/reference/access-authn-authz/admission-controllers.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8900 dns-custom-namerserver: break down the page into mutliple sections
  content/en/docs/tasks/administer-cluster/dns-custom-nameservers.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/L

#9028 Update kubeadm troubleshooting guide
  content/en/docs/setup/independent/troubleshooting-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#8898 PodSecurityPolicy readOnly hostpath
  content/en/docs/concepts/policy/pod-security-policy.md
Labels: Needs Docs Review, approved, cncf-cla: yes, lgtm, size/S

#8880 Add documentation for crictl
  content/en/docs/tasks/debug-application-cluster/crictl.md
  content/en/docs/tasks/debug-application-cluster/debug-application-introspection.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/L

#8835 Feature Gate VolumeSubpathEnvExpansion
  content/en/docs/concepts/storage/volumes.md
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/M

#9038 remove two extra asterisks in note tag example
  content/en/docs/home/contribute/style-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9036 wrap contents by capture tags
  content/en/docs/reference/issues-security/security.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9023 use note short tags
  content/en/docs/tasks/access-application-cluster/list-all-running-container-images.md
  content/en/docs/tasks/access-application-cluster/load-balance-access-application-cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9013 Added "by" in line 48
  content/en/docs/concepts/workloads/pods/podpreset.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8992 Pods cannot serve traffic while their are shutting down
  content/en/docs/concepts/workloads/pods/pod.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8827 Note that Heapster is deprecated
  content/en/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods.md
  content/en/docs/tasks/configure-pod-container/assign-cpu-resource.md
  content/en/docs/tasks/configure-pod-container/assign-memory-resource.md
  content/en/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
  content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
  content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
  content/en/docs/user-journeys/users/cluster-operator/intermediate.md
  static/images/docs/influx.png
  static/images/docs/monitoring-architecture.png
Labels: Docs LGTM, Needs Tech Review, approved, cncf-cla: yes, lgtm, sig/instrumentation, size/L

#8988 Fix `spec: replicas` -> `.spec.replicas`
  content/en/docs/concepts/workloads/controllers/deployment.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9041 change premise to premises, fixed heading
  content/en/docs/concepts/cluster-administration/networking.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9035 Fix:direct link in storage/storage-class
  content/en/docs/concepts/storage/storage-classes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9057 fix shortcode to troubleshoot deploy
  content/en/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8766 update dynamic kubelet config docs for v1.11
  content/en/docs/tasks/administer-cluster/reconfigure-kubelet.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#8981 Overall cleanup for kubeadm setup guide.
  OWNERS_ALIASES
  content/en/docs/setup/independent/create-cluster-kubeadm.md
  content/en/docs/tasks/administer-cluster/kubeadm/_index.md
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-8.md
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-9.md
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-ha.md
  content/en/docs/tasks/administer-cluster/upgrade-downgrade/_index.md
  content/en/docs/tasks/administer-cluster/upgrade-downgrade/kubeadm-upgrade-1-7.md
  content/en/docs/tasks/administer-cluster/upgrade-downgrade/upgrade-1-6.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/L

#9040 Container > containers
  content/en/docs/home/contribute/style-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9065 fix 'Kubernetes Basics' contents order
  content/en/docs/tutorials/kubernetes-basics/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9061 Clarification in dynamic Kubelet config doc
  content/en/docs/tasks/administer-cluster/reconfigure-kubelet.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9049 fix typo
  content/en/docs/setup/independent/troubleshooting-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9039 Typo in authentication.md
  content/en/docs/reference/access-authn-authz/authentication.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8937 Move turnkey topics to setup/turnkey.
  content/en/docs/setup/turnkey/_index.md
  content/en/docs/setup/turnkey/alibaba-cloud.md
  content/en/docs/setup/turnkey/aws.md
  content/en/docs/setup/turnkey/azure.md
  content/en/docs/setup/turnkey/clc.md
  content/en/docs/setup/turnkey/gce.md
  content/en/docs/setup/turnkey/stackpoint.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8804 Promote sysctls to Beta
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
  content/en/docs/tasks/administer-cluster/sysctl-cluster.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/M

#9080 kubectl reference docs for 1.11
  static/docs/reference/generated/kubectl/kubectl-commands.html
  static/docs/reference/generated/kubectl/navData.js
  static/docs/reference/generated/kubectl/scroll.js
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#9031 update to include sudo for various commands in documentation
  content/en/docs/tasks/tools/install-kubectl.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8752 Update high-availability.md
  content/en/docs/setup/independent/high-availability.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#8959 Updated Partner Page Design
  content/en/includes/partner-style.css
  content/en/partners/_index.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#9010 notice api permissions about mirror pods
  content/en/docs/tasks/administer-cluster/static-pod.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9068 wrap by warning tags
  content/en/docs/tasks/administer-cluster/reconfigure-kubelet.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9064 Update Federation API ref docs for 1.11.
  content/en/docs/reference/federation/extensions/v1beta1/definitions.html
  content/en/docs/reference/federation/extensions/v1beta1/operations.html
  content/en/docs/reference/federation/v1/definitions.html
  content/en/docs/reference/federation/v1/operations.html
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/L

#9074 Revert "fix max container back off cap (#8979)"
  content/en/docs/concepts/workloads/controllers/jobs-run-to-completion.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8970 Fix coredns chart value
  content/en/docs/tasks/federation/Values.yaml
  content/en/docs/tasks/federation/set-up-coredns-provider-federation.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9020 [css] Remove bullet styling from "tab-nav" components.
  src/sass/styles.sass
  static/css/styles.css
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9096 Minor modification for concepts/services-networking/service.md
  content/en/docs/concepts/services-networking/service.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9052 fix dead links in connect-applications-service.md
  content/en/docs/concepts/services-networking/connect-applications-service.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9075 Update scratch.md
  content/en/docs/setup/scratch.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9114 wrap by warning shortcodes
  content/en/docs/concepts/overview/object-management-kubectl/imperative-config.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9072 apply shortcodes and change code fencing style
  content/en/docs/concepts/overview/object-management-kubectl/declarative-config.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9058 remove out-of-date HA content
  content/en/docs/admin/high-availability/OWNERS
  content/en/docs/admin/high-availability/building.md
  content/en/docs/admin/high-availability/default-kubelet
  content/en/docs/admin/high-availability/etcd.yaml
  content/en/docs/admin/high-availability/kube-apiserver.yaml
  content/en/docs/admin/high-availability/kube-controller-manager.yaml
  content/en/docs/admin/high-availability/kube-scheduler.yaml
  content/en/docs/admin/high-availability/monit-docker
  content/en/docs/admin/high-availability/monit-kubelet
  content/en/docs/admin/high-availability/podmaster.yaml
  static/_redirects
  test/examples_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#9088 Improvements to etcd set up
  content/en/docs/tasks/administer-cluster/setup-ha-etcd-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/L

#9121 Remove yaml files that are no longer used.
  content/en/docs/admin/limitrange/OWNERS
  content/en/docs/admin/limitrange/invalid-pod.yaml
  content/en/docs/admin/limitrange/limits.yaml
  content/en/docs/admin/limitrange/namespace.yaml
  content/en/docs/admin/limitrange/valid-pod.yaml
  test/examples_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8834 CRD versioning Public Documentation
  content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
  content/en/docs/tasks/access-kubernetes-api/configure-aggregation-layer.md
  content/en/docs/tasks/access-kubernetes-api/custom-resources/_index.md
  content/en/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning.md
  content/en/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions.md
  content/en/docs/tasks/access-kubernetes-api/custom-resources/migrate-third-party-resource.md
  content/en/docs/tasks/access-kubernetes-api/http-proxy-access-api.md
  content/en/docs/tasks/access-kubernetes-api/setup-extension-api-server.md
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/L

#8927 CSI documentation update for raw block volume support
  content/en/docs/concepts/storage/volumes.md
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#9141 Fix Initial User Journey
  static/js/user-journeys/home.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9135 Remove unused yaml files.
  content/en/docs/admin/multiple-schedulers/OWNERS
  content/en/docs/admin/multiple-schedulers/pod1.yaml
  content/en/docs/admin/multiple-schedulers/pod2.yaml
  content/en/docs/admin/multiple-schedulers/pod3.yaml
  content/en/docs/admin/resourcequota/OWNERS
  content/en/docs/admin/resourcequota/best-effort.yaml
  content/en/docs/admin/resourcequota/compute-resources.yaml
  content/en/docs/admin/resourcequota/limits.yaml
  content/en/docs/admin/resourcequota/namespace.yaml
  content/en/docs/admin/resourcequota/not-best-effort.yaml
  content/en/docs/admin/resourcequota/object-counts.yaml
  test/examples_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#9090 Add two new reviewers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9094 Update kubectl component ref page for 1.11.
  content/en/docs/reference/kubectl/kubectl.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9012 Example: Deploying PHP Guestbook application with Redis: Missing deployment labels
  content/en/docs/tutorials/stateless-application/guestbook/frontend-deployment.yaml
  content/en/docs/tutorials/stateless-application/guestbook/redis-master-deployment.yaml
  content/en/docs/tutorials/stateless-application/guestbook/redis-slave-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9097 [docs] Add Tabs List component to smoke test page.
  content/en/docs/test.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#9140 Remove or move topics under docs/admin.
  content/en/docs/admin/OWNERS
  content/en/docs/admin/_index.md
  content/en/docs/admin/kubelet-authentication-authorization.md
  content/en/docs/admin/kubelet-tls-bootstrapping.md
  content/en/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
  content/en/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
  content/en/docs/setup/cluster-large.md
  content/en/docs/setup/multiple-zones.md
  content/en/docs/setup/node-conformance.md
  content/en/docs/setup/salt.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#9138 Update kubeadm-init.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9130 Fix broken link to kube-dns README
  content/en/docs/tasks/administer-cluster/dns-debugging-resolution.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9142 Fix nits in CRD versioning docs
  content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
  content/en/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning.md
Labels: approved, cncf-cla: yes, lgtm, size/S
