Repository kubernetes/website, pull requests merged in 2018-05, with the labels that each got.

#8230 Adding Blog Post: Zero-downtime Deployment in Kubernetes with Jenkins
  blog/_posts/2018-04-30-zero-downtime-deployment-kubernetes-jenkins.md
  images/blog/2018-04-30-zero-downtime-deployment-kubernetes-jenkins/deployment-process.png
  images/blog/2018-04-30-zero-downtime-deployment-kubernetes-jenkins/jenkins-pipeline.png
  images/blog/2018-04-30-zero-downtime-deployment-kubernetes-jenkins/resources.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#8193 Adding Blog Post: Developing on Kubernetes
  blog/_posts/2018-05-01-developing-on-kubernetes.md
  images/blog/2018-05-01-developing-on-kubernetes/dok-architecture_preview.png
  images/blog/2018-05-01-developing-on-kubernetes/dok-devmodes_preview.png
  images/blog/2018-05-01-developing-on-kubernetes/dok-ksync_preview.png
  images/blog/2018-05-01-developing-on-kubernetes/dok-minikube-localdev_preview.png
  images/blog/2018-05-01-developing-on-kubernetes/dok-skaffold_preview.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#8198 Use enable-admission-plugins flag for >=1.10
  docs/admin/admission-controllers.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8278 Use octal instead of decimal in examples
  docs/concepts/configuration/secret.md
  docs/concepts/storage/volumes.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8234 Route controller is not GCE specific
  docs/concepts/architecture/cloud-controller.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8284 Adding New Blog Post: Current State of Policy in Kubernetes
  blog/_posts/2018-04-30-zero-downtime-deployment-kubernetes-jenkins.md
  blog/_posts/2018-05-02-policy-in-kubernetes.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8148 Update kubeadm-alpha.md
  docs/reference/setup-tools/kubeadm/kubeadm-alpha.md
Labels: Docs Review: Open Issues, Needs Tech Review, approved, cncf-cla: yes, lgtm, size/XS

#8283 Refresh kube-component reference docs
  docs/reference/generated/cloud-controller-manager.md
  docs/reference/generated/kube-apiserver.md
  docs/reference/generated/kube-controller-manager.md
  docs/reference/generated/kube-proxy.md
  docs/reference/generated/kube-scheduler.md
  docs/reference/generated/kubelet.md
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#8311 Announcing Kubeflow 0.1 blog post
  blog/_posts/http/2018-05-04-Announcing-Kubeflow-0.1.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#8217 document pod downwardAPI fieldRef values
  docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
Labels: Docs LGTM, approved, cncf-cla: yes, lgtm, size/M

#8309 typo fix Boostrap -->Bootstrap
  docs/reference/setup-tools/kubeadm/implementation-details.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8307 delete duplicated line
  docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8306 Fix wrong pod name
  docs/tasks/administer-cluster/configure-multiple-schedulers.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8310 PSP: clarify the case with pod update
  docs/concepts/policy/pod-security-policy.md
Labels: Needs Tech Review, approved, cncf-cla: yes, lgtm, size/XS

#8320 Blog post: Hugo migration
  content/en/blog/_posts/2018-05-05-hugo-migration.md
Labels: cncf-cla: yes, size/M

#8334 Fix links to github view and edit pages
  content/en/docs/editdocs.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8335 Fix markdown issues (Write the Docs writing day)
  content/en/docs/user-journeys/users/application-developer/foundational.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8323 Update Hugo parser description
  content/en/blog/_posts/2018-05-05-hugo-migration.md
Labels: cncf-cla: yes, lgtm, size/XS

#8344 Fixed #8076
  content/en/docs/tutorials/stateless-application/hello-minikube.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8337 #4500: Split out tasks in cron jobs docs
  content/en/docs/concepts/workloads/controllers/cron-jobs.md
  content/en/docs/tasks/job/automated-tasks-with-cron-jobs.md
  content/en/docs/tasks/job/cronjob.yaml
  data/tasks.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#8341 More readable fix for issue #7957
  content/en/docs/reference/kubectl/jsonpath.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/S

#8351 Update load-balance-access-application-cluster.md
  content/en/docs/tasks/access-application-cluster/load-balance-access-application-cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8353 [Issue #8336] Added a # symbol to What's next
  content/en/docs/tasks/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8347 FIxing broken link
  content/en/docs/user-guide/walkthrough/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8365 Update _redirects to fix doc contrib 404
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8368 Fix link opening in new window
  content/en/docs/home/contribute/create-pull-request.md
  content/en/docs/home/contribute/review-issues.md
  content/en/docs/home/contribute/stage-documentation-changes.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8352 #8346 HTML syntax instead of MD in HTML blocks
  content/en/docs/user-journeys/users/application-developer/foundational.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8360 Style guide updates
  content/en/docs/user-guide/walkthrough/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8374 Add fix for error in kubeadm ref pages
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-join.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-reset.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-version.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8401 Restoring blog images folder
  content/en/blog/_posts/2018-05-04-announcing-kubeflow-0.1.md
  static/images/blog/2018-04-30-zero-downtime-deployment-kubernetes-jenkins/deployment-process.png
  static/images/blog/2018-04-30-zero-downtime-deployment-kubernetes-jenkins/jenkins-pipeline.png
  static/images/blog/2018-04-30-zero-downtime-deployment-kubernetes-jenkins/resources.png
  static/images/blog/2018-05-01-developing-on-kubernetes/dok-architecture_preview.png
  static/images/blog/2018-05-01-developing-on-kubernetes/dok-devmodes_preview.png
  static/images/blog/2018-05-01-developing-on-kubernetes/dok-ksync_preview.png
  static/images/blog/2018-05-01-developing-on-kubernetes/dok-minikube-localdev_preview.png
  static/images/blog/2018-05-01-developing-on-kubernetes/dok-skaffold_preview.png
Labels: approved, cncf-cla: yes, lgtm, size/M

#8422 Re-add kubefed to setup tools reference
  content/en/docs/reference/setup-tools/_index.md
  content/en/docs/reference/setup-tools/kubeadm/_index.md
  content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-alpha.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-config.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-join.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-reset.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-token.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-upgrade.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-version.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm.md
  content/en/docs/reference/setup-tools/kubefed/_index.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-init.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-join.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-options.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-unjoin.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-version.md
  content/en/docs/reference/setup-tools/kubefed/kubefed.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#8435 Put Kubernetes API ref docs in the left nav.
  content/en/docs/reference/kubernetes-api/_index.md
  content/en/docs/reference/kubernetes-api/index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8443 Fix markdown issues
  content/en/blog/_posts/2018-05-01-developing-on-kubernetes.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8462 Fixes for reference/kubectl/overview.md
  content/en/docs/reference/kubectl/overview.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8463 Fix for kubctl/conventions
  content/en/docs/reference/kubectl/conventions.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8459 Fix concepts/api-extension/custom-resources.md
  content/en/docs/concepts/api-extension/custom-resources.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8452 Fix link to Flux
  content/en/blog/_posts/2018-05-01-developing-on-kubernetes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8458 add Nordstrom case study
  content/en/case-studies/_index.html
  content/en/case-studies/nordstrom.html
  static/images/CaseStudy_nordstrom_banner1.jpg
  static/images/CaseStudy_nordstrom_banner3.jpg
  static/images/CaseStudy_nordstrom_banner4.jpg
  static/images/case_studies/nordstrom_feature.png
  static/images/nordstrom_logo.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#8446 Adding Rancher 2. 0 and RKE as K8s solutions
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8468 Indents added to fix formatting
  content/en/docs/tutorials/stateless-application/expose-external-ip-address.md
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/S

#8436 Update to Hugo 0.40.3
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8465 Add F5 Ingress controller to ingress concept
  content/en/docs/concepts/services-networking/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8430 Copy kubectl command ref docs to Hugo site.
  content/en/docs/reference/kubectl/overview.md
  static/docs/reference/generated/kubectl/kubectl-commands.html
  static/docs/reference/generated/kubectl/navData.js
  static/docs/reference/generated/kubectl/node_modules/bootstrap/dist/css/bootstrap.min.css
  static/docs/reference/generated/kubectl/node_modules/font-awesome/css/font-awesome.min.css
  static/docs/reference/generated/kubectl/node_modules/highlight.js/styles/default.css
  static/docs/reference/generated/kubectl/node_modules/jquery.scrollto/jquery.scrollTo.min.js
  static/docs/reference/generated/kubectl/node_modules/jquery/dist/jquery.min.js
  static/docs/reference/generated/kubectl/scroll.js
  static/docs/reference/generated/kubectl/stylesheet.css
  static/docs/reference/generated/kubectl/tabvisibility.js
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#8478 Copy kubectl binary ref page to Hugo site.
  content/en/docs/reference/kubectl/kubectl.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8475 Update images with specified width to use figure shortcode
  content/en/docs/concepts/workloads/pods/pod-overview.md
  content/en/docs/concepts/workloads/pods/pod.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8472 Fix lists in application-developer/advanced
  content/en/docs/user-journeys/users/application-developer/advanced.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8460 kubeadm-init: update missing links and add kube-proxy info
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/S

#8301 Adds a task for HA etcd kubeadm
  content/en/docs/tasks/administer-cluster/setup-ha-etcd-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/L

#8497 fix an image link
  content/en/docs/concepts/workloads/pods/pod.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8502 Put kubectl commands in left nav.
  content/en/docs/reference/kubectl/kubectl-cmds.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8480 Hugo: Fix /admin/accessing-the-api
  content/en/docs/admin/accessing-the-api.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8481 Hugo: Fix admin/admission-controllers
  content/en/docs/admin/admission-controllers.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8504 Redirect command-line ref docs.
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/S

#8501 Fix typo in style-guide
  content/en/docs/home/contribute/style-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8445 clarified roleref in rolebinding
  content/en/docs/admin/authorization/rbac.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8366 Container Linux doc fixes
  content/en/docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8370 Fix spacing so CLI samples render properly
  content/en/docs/tasks/tools/install-kubectl.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8373 Users should choose network plugin before initializing cluster
  content/en/docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8500 Hugo: Update rbac.md
  content/en/docs/admin/authorization/rbac.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#8474 Fix application-developer/intermediate issues
  content/en/docs/user-journeys/users/application-developer/intermediate.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8471 Fix toc in user-guide/walkthrough/k8s201.md
  content/en/docs/user-guide/walkthrough/k8s201.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8391 Update create-cluster-kubeadm.md
  content/en/docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8432 Document kubeadm etcd serverCertSANs/peerCertSANs
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8479 typo
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-version.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8505 Fix broken link to local storage class
  content/en/docs/concepts/storage/volumes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8382 Fix broken link to Centos 7 RPMs
  content/en/docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8509 Redirect kubefed ref pages to Hugo locations.
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8434 improve configure-projected-volume-storage.md
  content/en/docs/tasks/configure-pod-container/configure-projected-volume-storage.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8510 Update .gitignore to ignore vscode stuffs
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8496 Fix tab titles in install-kubectl.md
  content/en/docs/tasks/tools/install-kubectl.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8517 Get Service Catalog topic into left nav.
  content/en/docs/concepts/service-catalog.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8536 Move Install kubeadm topic under Install Tools.
  content/en/docs/tasks/tools/install-kubeadm.md
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8515 Change H4 to H2 so TOC will appear.
  content/en/docs/concepts/overview/what-is-kubernetes.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8406 update link to kube-router documentation
  content/en/docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8555 Add Misty to approvers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8557 Fix up Tutorials landing page and Tutorials left nav.
  content/en/docs/tutorials/Dockerfile
  content/en/docs/tutorials/_index.md
  content/en/docs/tutorials/clusters/_index.md
  content/en/docs/tutorials/configuration/_index.md
  content/en/docs/tutorials/hello-minikube.md
  content/en/docs/tutorials/kubernetes-basics/_index.md
  content/en/docs/tutorials/kubernetes-basics/create-cluster/_index.md
  content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
  content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
  content/en/docs/tutorials/kubernetes-basics/deploy-app/_index.md
  content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
  content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
  content/en/docs/tutorials/kubernetes-basics/explore/_index.md
  content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
  content/en/docs/tutorials/kubernetes-basics/explore/explore-intro.html
  content/en/docs/tutorials/kubernetes-basics/expose/_index.md
  content/en/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
  content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html
  content/en/docs/tutorials/kubernetes-basics/index.html
  content/en/docs/tutorials/kubernetes-basics/scale/_index.md
  content/en/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
  content/en/docs/tutorials/kubernetes-basics/scale/scale-intro.html
  content/en/docs/tutorials/kubernetes-basics/update/_index.md
  content/en/docs/tutorials/kubernetes-basics/update/update-interactive.html
  content/en/docs/tutorials/kubernetes-basics/update/update-intro.html
  content/en/docs/tutorials/online-training/_index.md
  content/en/docs/tutorials/server.js
  content/en/docs/tutorials/services/_index.md
  content/en/docs/tutorials/stateful-application/_index.md
  content/en/docs/tutorials/stateful-application/basic-stateful-set.md
  content/en/docs/tutorials/stateful-application/cassandra.md
  content/en/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md
  content/en/docs/tutorials/stateful-application/zookeeper.md
  content/en/docs/tutorials/stateless-application/_index.md
  content/en/docs/tutorials/stateless-application/expose-external-ip-address.md
  content/en/docs/tutorials/stateless-application/guestbook.md
  static/_redirects
  static/example-templates/example-tutorial-template.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#8349 Create initial smoke test page
  content/en/docs/test.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#8319 Remove double head tag
  layouts/partials/head.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#8539 fix an error in example yaml file
  content/en/docs/admin/authorization/rbac.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8524 Typo fix: some word error
  content/en/docs/reference/command-line-tools-reference/kubelet.md
  content/en/docs/tasks/administer-cluster/setup-ha-etcd-with-kubeadm.md
  content/en/docs/tasks/federation/set-up-cluster-federation-kubefed.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8560 Update missing kubever on weave network
  content/en/docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8543 custom resources: explain declarative API
  content/en/docs/concepts/api-extension/custom-resources.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8542 unifying .spec.selector spelling
  content/en/docs/concepts/workloads/controllers/daemonset.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8527 Revert lost environment variables
  content/en/docs/tasks/tools/install-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8520 fix crd output example
  content/en/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8564 Typo fix: writeable->writable
  content/en/docs/concepts/policy/pod-security-policy.md
  content/en/docs/tasks/administer-cluster/reconfigure-kubelet.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8562 Update kubeadm-init.md for broken url
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8569 Arrange the Extending Kubernetes section in the Concepts TOC
  content/en/docs/concepts/api-extension/_index.md
  content/en/docs/concepts/extend-kubernetes/_index.md
  content/en/docs/concepts/extend-kubernetes/api-extension/_index.md
  content/en/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md
  content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
  content/en/docs/concepts/extend-kubernetes/compute-storage-net/_index.md
  content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
  content/en/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
  content/en/docs/concepts/extend-kubernetes/extend-cluster.md
  content/en/docs/concepts/extend-kubernetes/service-catalog.md
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/S

#8573 Remove step numbers in kubeadm create cluster docs
  content/en/docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8546 Blog post: Project Gardener
  content/en/blog/_posts/2018-05-17-gardener-the-kubernetes-botanist.md
  static/images/blog/2018-05-17-gardener-the-kubernetes-botanist/architecture.png
  static/images/blog/2018-05-17-gardener-the-kubernetes-botanist/dashboard.gif
Labels: approved, cncf-cla: yes, lgtm, size/L

#8580 fixTocIndent
  content/en/docs/setup/building-from-source.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8439 Update extend-api-custom-resource-definitions.md
  content/en/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8579 Fixed misleading text in out-of-resources.md
  content/en/docs/tasks/administer-cluster/out-of-resource.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8371 Add missing bash identifier
  content/en/docs/tasks/tools/install-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8379 Updated jobs-run-to-completion.md
  content/en/docs/concepts/workloads/controllers/jobs-run-to-completion.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8411 Remove Photon references
  content/cn/docs/concepts/policy/pod-security-policy.md
  content/en/docs/concepts/storage/persistent-volumes.md
  content/en/docs/concepts/storage/storage-classes.md
  content/en/docs/getting-started-guides/scratch.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8444 high-availability.md: fix missing parameter values
  content/en/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8372 Remove GKE specific content from this page
  content/en/docs/concepts/architecture/master-node-communication.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8601 Set weights for topics under Tasks > Inject Data.
  content/en/docs/tasks/inject-data-application/_index.md
  content/en/docs/tasks/inject-data-application/define-command-argument-container.md
  content/en/docs/tasks/inject-data-application/define-environment-variable-container.md
  content/en/docs/tasks/inject-data-application/distribute-credentials-secure.md
  content/en/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
  content/en/docs/tasks/inject-data-application/environment-variable-expose-pod-information.md
  content/en/docs/tasks/inject-data-application/podpreset.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8384 Fix code blocks in set-up-cluster-federation-kubefed
  content/en/docs/tasks/federation/set-up-cluster-federation-kubefed.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8508 troubleshooting-kubeadm: add note about kubeadm-reset block
  content/en/docs/setup/independent/troubleshooting-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8490 Hugo: Fix broken lists in windows start guide
  content/en/docs/getting-started-guides/windows/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8522 Fix url to etcd binary
  content/en/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8588 Fix sections in install-kubectl
  content/en/docs/tasks/tools/install-kubectl.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8529 Fix no title elements in HTML fo all pages
  layouts/partials/head.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8423 Adding KTPs and new KCSP partners
  content/en/includes/partner-script.js
  content/en/includes/partner-style.css
  content/en/partners/_index.html
  static/images/square-logos/banzai.png
  static/images/square-logos/giant_swarm.png
  static/images/square-logos/giantswarm.png
  static/images/square-logos/kontena.png
  static/images/square-logos/lf-training.png
  static/images/square-logos/newcontext.png
  static/images/square-logos/nttdata.png
  static/images/square-logos/octo.png
  static/images/square-logos/wise2c.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#8388 Restore gate jobs
  .travis.yml
  test/examples_test.go
  test/glossary_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#8621 remove test/glossary_test.go
  test/glossary_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8577 Fix link to kubectl command reference.
  content/en/docs/concepts/overview/object-management-kubectl/overview.md
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8619 Fix bullet list for Hugo
  content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8623 Add weights and move files under Tasks > Jobs.
  content/en/docs/tasks/job/_index.md
  content/en/docs/tasks/job/automated-tasks-with-cron-jobs.md
  content/en/docs/tasks/job/coarse-parallel-processing-work-queue.md
  content/en/docs/tasks/job/fine-parallel-processing-work-queue.md
  content/en/docs/tasks/job/parallel-processing-expansion.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8615 Trivial: fix typo "evictions are be allowed"
  content/en/docs/tasks/run-application/configure-pdb.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8633 Hugo: Added toc_hide=true flag to file frontmatter
  content/en/docs/concepts/example-concept-template.md
  content/en/docs/tasks/example-task-template.md
  content/en/docs/user-journeys/users/cluster-operator/_advanced.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8626 Remove extra '$' char from 'kubectl patch' example
  content/en/docs/tasks/run-application/update-api-object-kubectl-patch.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8585 fix a link miss bug in volume description
  content/en/docs/concepts/storage/volumes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8635 Add weights, move files: Tasks>AdminClust>MemCPU
  content/en/docs/tasks/administer-cluster/_index.md
  content/en/docs/tasks/administer-cluster/manage-resources/_index.md
  content/en/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace.md
  content/en/docs/tasks/administer-cluster/manage-resources/cpu-constraints-pod-2.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/cpu-constraints-pod-3.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/cpu-constraints-pod-4.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/cpu-constraints-pod.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/cpu-constraints.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace.md
  content/en/docs/tasks/administer-cluster/manage-resources/cpu-defaults-pod-2.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/cpu-defaults-pod-3.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/cpu-defaults-pod.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/cpu-defaults.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace.md
  content/en/docs/tasks/administer-cluster/manage-resources/memory-constraints-pod-2.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/memory-constraints-pod-3.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/memory-constraints-pod-4.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/memory-constraints-pod.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/memory-constraints.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
  content/en/docs/tasks/administer-cluster/manage-resources/memory-defaults-pod-2.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/memory-defaults-pod-3.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/memory-defaults-pod.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/memory-defaults.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/quota-mem-cpu-pod-2.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/quota-mem-cpu-pod.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/quota-mem-cpu.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace.md
  content/en/docs/tasks/administer-cluster/manage-resources/quota-objects-pvc-2.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/quota-objects-pvc.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/quota-pod-deployment.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/quota-pod-namespace.md
  content/en/docs/tasks/administer-cluster/manage-resources/quota-pod.yaml
  content/en/docs/tasks/administer-cluster/manage-resources/quota-pvc-2.yaml
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/S

#8625 Add weighs and move files under Tasks > Access App.
  content/en/docs/tasks/access-application-cluster/_index.md
  content/en/docs/tasks/access-application-cluster/access-cluster.md
  content/en/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume.md
  content/en/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
  content/en/docs/tasks/access-application-cluster/configure-cloud-provider-firewall.md
  content/en/docs/tasks/access-application-cluster/configure-dns-cluster.md
  content/en/docs/tasks/access-application-cluster/connecting-frontend-backend.md
  content/en/docs/tasks/access-application-cluster/create-external-load-balancer.md
  content/en/docs/tasks/access-application-cluster/list-all-running-container-images.md
  content/en/docs/tasks/access-application-cluster/load-balance-access-application-cluster.md
  content/en/docs/tasks/access-application-cluster/port-forward-access-application-cluster.md
  content/en/docs/tasks/access-application-cluster/service-access-application-cluster.md
  content/en/docs/tasks/access-application-cluster/web-ui-dashboard.md
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/S

#8634 Add weights, move files: Tasks>AdminClust>NetPol.
  content/en/docs/tasks/administer-cluster/_index.md
  content/en/docs/tasks/administer-cluster/network-policy-provider/_index.md
  content/en/docs/tasks/administer-cluster/network-policy-provider/calico-network-policy.md
  content/en/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md
  content/en/docs/tasks/administer-cluster/network-policy-provider/kube-router-network-policy.md
  content/en/docs/tasks/administer-cluster/network-policy-provider/romana-network-policy.md
  content/en/docs/tasks/administer-cluster/network-policy-provider/weave-network-policy.md
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/S

#8590 fix-typo: accomodate->accommodate
  static/css/blog.css
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8582 Improve left nav for Tasks.
  content/en/docs/tasks/configure-pod-container/_index.md
  content/en/docs/tasks/configure-pod-container/assign-cpu-resource.md
  content/en/docs/tasks/configure-pod-container/assign-memory-resource.md
  content/en/docs/tasks/configure-pod-container/assign-pods-nodes.md
  content/en/docs/tasks/configure-pod-container/attach-handler-lifecycle-event.md
  content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-probes.md
  content/en/docs/tasks/configure-pod-container/configure-persistent-volume-storage.md
  content/en/docs/tasks/configure-pod-container/configure-pod-configmap.md
  content/en/docs/tasks/configure-pod-container/configure-pod-initialization.md
  content/en/docs/tasks/configure-pod-container/configure-projected-volume-storage.md
  content/en/docs/tasks/configure-pod-container/configure-service-account.md
  content/en/docs/tasks/configure-pod-container/configure-volume-storage.md
  content/en/docs/tasks/configure-pod-container/extended-resource.md
  content/en/docs/tasks/configure-pod-container/pull-image-private-registry.md
  content/en/docs/tasks/configure-pod-container/quality-service-pod.md
  content/en/docs/tasks/configure-pod-container/security-context.md
  content/en/docs/tasks/configure-pod-container/share-process-namespace.md
  content/en/docs/tasks/configure-pod-container/translate-compose-kubernetes.md
  content/en/docs/tasks/tools/_index.md
  content/en/docs/tasks/tools/install-kubeadm.md
  content/en/docs/tasks/tools/install-kubectl.md
  content/en/docs/tasks/tools/install-minikube.md
  content/en/docs/tools/kompose/_index.md
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/M

#8597 Fix link to kubectl command reference.
  content/en/docs/reference/kubectl/overview.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8602 Add weights for topics under Tasks > Run App.
  content/en/docs/tasks/run-application/_index.md
  content/en/docs/tasks/run-application/configure-pdb.md
  content/en/docs/tasks/run-application/delete-stateful-set.md
  content/en/docs/tasks/run-application/force-delete-stateful-set-pod.md
  content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
  content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
  content/en/docs/tasks/run-application/rolling-update-replication-controller.md
  content/en/docs/tasks/run-application/run-replicated-stateful-application.md
  content/en/docs/tasks/run-application/run-single-instance-stateful-application.md
  content/en/docs/tasks/run-application/run-stateless-application-deployment.md
  content/en/docs/tasks/run-application/scale-stateful-set.md
  content/en/docs/tasks/run-application/update-api-object-kubectl-patch.md
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/S

#8599 Fix link to Admission Webhooks section.
  content/en/docs/concepts/extend-kubernetes/extend-cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8644 Last batch change approvers to reviewers
  content/en/docs/reference/api-concepts.md
  content/en/docs/reference/api-overview.md
  content/en/docs/reference/client-libraries.md
  content/en/docs/reference/deprecation-policy.md
  content/en/docs/reference/kubectl/cheatsheet.md
  content/en/docs/reference/kubectl/conventions.md
  content/en/docs/reference/kubectl/docker-cli-to-kubectl.md
  content/en/docs/reference/kubectl/overview.md
  content/en/docs/reference/security.md
  content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-alpha.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-config.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-join.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-reset.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-token.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-upgrade.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-version.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm.md
  content/en/docs/tasks/administer-cluster/dns-debugging-resolution.md
  content/en/docs/tasks/administer-cluster/kms-provider.md
  content/en/docs/tasks/administer-cluster/storage-object-in-use-protection.md
  content/en/docs/tasks/configure-pod-container/share-process-namespace.md
  content/en/docs/tasks/configure-pod-container/translate-compose-kubernetes.md
  content/en/docs/tools/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#8652 Update debug-service.md --- add ipvs part on kube-proxy
  content/en/docs/tasks/debug-application-cluster/debug-service.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8660 Fix codeblock formatting for kubeadm install
  content/en/docs/tasks/tools/install-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8581 Fix: Change direct link to relative link
  content/en/docs/tasks/tools/install-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8641 Add configure link description
  content/en/docs/tasks/access-application-cluster/configure-dns-cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8649 FixRestartPolicyLink
  content/cn/docs/concepts/workloads/controllers/deployment.md
  content/en/docs/concepts/workloads/controllers/deployment.md
  content/en/docs/concepts/workloads/controllers/replicaset.md
  content/en/docs/concepts/workloads/controllers/replicationcontroller.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8676 Remove the useless TOC
  content/en/docs/reference/labels-annotations-taints.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8507 Fix nodeSelector for local volumes in blog post
  content/en/blog/_posts/2018-04-13-local-persistent-volumes-beta.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8291 StorageObjectInUseProtection is GA
  content/en/docs/reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8674 Typo fix: some spelling errors
  content/en/docs/concepts/storage/volumes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8642 Fixed a small grammar mistake
  content/en/_index.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8647 Hugo api-overview alpha bullet fix
  content/en/docs/reference/api-overview.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8686 Update references to proper subdirectory in queue docs
  content/en/docs/tasks/job/coarse-parallel-processing-work-queue.md
  content/en/docs/tasks/job/fine-parallel-processing-work-queue.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8566 Hugo: Fix kubernetes-api.md
  content/en/docs/concepts/overview/kubernetes-api.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8604 Update style-guide.md
  content/en/docs/home/contribute/style-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8567 Hugo: fix device-plugins
  content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#8608 fix link of extened-resources
  content/en/docs/concepts/policy/resource-quotas.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8683 Update safely-drain-node.md
  content/en/docs/tasks/administer-cluster/safely-drain-node.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8664 Fix etcd installation command in kubeadm tutorial
  content/en/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#8662 Update patch versions in config
  config.toml
Labels: approved, cncf-cla: yes, lgtm, size/S

#8643 install-kubeadm: update the recommended Docker version
  content/en/docs/tasks/tools/install-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, sig/node, size/XS

#8696 fixTocIndent
  content/en/docs/concepts/cluster-administration/kubelet-garbage-collection.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8694 Fix guestbooks tutorial
  content/en/docs/tutorials/stateless-application/guestbook.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#8650 Fix: remove useless or
  content/en/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8651 fix page of kubectl
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8682 Adding Kubevirt blog post
  content/en/blog/_posts/2018-05-22-getting-to-know-kubevirt.md
  static/images/blog/2018-05-22-getting-to-know-kubevirt/kubevirt-components.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#8665 CRIContainerLogRotation is Beta in 1.11
  content/en/docs/concepts/configuration/pod-priority-preemption.md
  content/en/docs/reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
