Repository kubernetes/website, pull requests merged in 2018-12, with the labels that each got.

#11416 Remove references to etcd2 in content/ko
  content/ko/docs/setup/custom-cloud/master.yaml
  content/ko/docs/setup/custom-cloud/node.yaml
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#11402 zh-trans: update docs/reference/kubectl/kubectl.md
  content/zh/docs/reference/kubectl/kubectl.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XL

#11438 Resolve conflicts against master for /ko contents
  content/ko/docs/setup/independent/control-plane-flags.md
  content/ko/docs/setup/independent/create-cluster-kubeadm.md
  content/ko/docs/setup/independent/high-availability.md
  content/ko/docs/setup/independent/install-kubeadm.md
  content/ko/docs/setup/independent/setup-ha-etcd-with-kubeadm.md
  content/ko/docs/setup/independent/troubleshooting-kubeadm.md
  content/ko/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/XXL

#11439 Resolve conflicts against dev-1.13 for /ko contents
  content/ko/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#11440 Final Korean l10n work for dev-1.13
  content/ko/docs/setup/custom-cloud/master.yaml
  content/ko/docs/setup/custom-cloud/node.yaml
  content/ko/docs/setup/independent/control-plane-flags.md
  content/ko/docs/setup/independent/create-cluster-kubeadm.md
  content/ko/docs/setup/independent/high-availability.md
  content/ko/docs/setup/independent/install-kubeadm.md
  content/ko/docs/setup/independent/setup-ha-etcd-with-kubeadm.md
  content/ko/docs/setup/independent/troubleshooting-kubeadm.md
  content/ko/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/XXL

#11458 zh-trans: copy pod/_index.md
  content/zh/docs/concepts/workloads/pods/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#11335 zh-trans: add network-policy.md
  content/zh/docs/reference/glossary/network-policy.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11368 zh-trans: add aggregation-layer.md
  content/zh/docs/reference/glossary/aggregation-layer.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11428 zh-trans: add developer.md
  content/zh/docs/reference/glossary/developer.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11377 ADD content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init.md
  content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XL

#11433 zh-trans: add name.md
  content/zh/docs/reference/glossary/name.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11461 fix Minikube 404 error.
  content/en/includes/task-tutorial-prereqs.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11443 zh-trans: add init-container.md
  content/zh/docs/reference/glossary/init-container.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11479 zh_trans: add run-application/rolling-update-replication-controller.md
  content/zh/docs/tasks/run-application/rolling-update-replication-controller.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11481 zh-trans: add examples/podpreset/ examples/pods/{config,inject,probe,…
  content/zh/examples/podpreset/allow-db-merged.yaml
  content/zh/examples/podpreset/allow-db.yaml
  content/zh/examples/podpreset/configmap.yaml
  content/zh/examples/podpreset/conflict-pod.yaml
  content/zh/examples/podpreset/conflict-preset.yaml
  content/zh/examples/podpreset/merged.yaml
  content/zh/examples/podpreset/multi-merged.yaml
  content/zh/examples/podpreset/pod.yaml
  content/zh/examples/podpreset/preset.yaml
  content/zh/examples/podpreset/proxy.yaml
  content/zh/examples/podpreset/replicaset-merged.yaml
  content/zh/examples/podpreset/replicaset.yaml
  content/zh/examples/pods/commands.yaml
  content/zh/examples/pods/config/redis-pod.yaml
  content/zh/examples/pods/init-containers.yaml
  content/zh/examples/pods/inject/dapi-envars-container.yaml
  content/zh/examples/pods/inject/dapi-envars-pod.yaml
  content/zh/examples/pods/inject/dapi-volume-resources.yaml
  content/zh/examples/pods/inject/dapi-volume.yaml
  content/zh/examples/pods/inject/envars.yaml
  content/zh/examples/pods/inject/secret-envars-pod.yaml
  content/zh/examples/pods/inject/secret-pod.yaml
  content/zh/examples/pods/inject/secret.yaml
  content/zh/examples/pods/lifecycle-events.yaml
  content/zh/examples/pods/pod-with-node-affinity.yaml
  content/zh/examples/pods/pod-with-pod-affinity.yaml
  content/zh/examples/pods/private-reg-pod.yaml
  content/zh/examples/pods/probe/exec-liveness.yaml
  content/zh/examples/pods/probe/http-liveness.yaml
  content/zh/examples/pods/probe/pod-with-http-healthcheck.yaml
  content/zh/examples/pods/probe/pod-with-tcp-socket-healthcheck.yaml
  content/zh/examples/pods/probe/tcp-liveness-readiness.yaml
  content/zh/examples/pods/qos/qos-pod-2.yaml
  content/zh/examples/pods/qos/qos-pod-3.yaml
  content/zh/examples/pods/qos/qos-pod-4.yaml
  content/zh/examples/pods/qos/qos-pod.yaml
  content/zh/examples/pods/resource/cpu-request-limit-2.yaml
  content/zh/examples/pods/resource/cpu-request-limit.yaml
  content/zh/examples/pods/resource/extended-resource-pod-2.yaml
  content/zh/examples/pods/resource/extended-resource-pod.yaml
  content/zh/examples/pods/resource/memory-request-limit-2.yaml
  content/zh/examples/pods/resource/memory-request-limit-3.yaml
  content/zh/examples/pods/resource/memory-request-limit.yaml
  content/zh/examples/pods/security/hello-apparmor.yaml
  content/zh/examples/pods/security/security-context-2.yaml
  content/zh/examples/pods/security/security-context-3.yaml
  content/zh/examples/pods/security/security-context-4.yaml
  content/zh/examples/pods/security/security-context.yaml
  content/zh/examples/pods/share-process-namespace.yaml
  content/zh/examples/pods/storage/projected.yaml
  content/zh/examples/pods/storage/pv-claim.yaml
  content/zh/examples/pods/storage/pv-pod.yaml
  content/zh/examples/pods/storage/pv-volume.yaml
  content/zh/examples/pods/two-container-pod.yaml
Labels: cncf-cla: yes, language/zh, size/XXL

#11482 zh-trans: add examples/{policy,service,windows}/ yaml files
  content/zh/examples/policy/example-psp.yaml
  content/zh/examples/policy/privileged-psp.yaml
  content/zh/examples/policy/restricted-psp.yaml
  content/zh/examples/service/access/frontend.yaml
  content/zh/examples/service/access/hello-service.yaml
  content/zh/examples/service/access/hello.yaml
  content/zh/examples/service/networking/curlpod.yaml
  content/zh/examples/service/networking/custom-dns.yaml
  content/zh/examples/service/networking/hostaliases-pod.yaml
  content/zh/examples/service/networking/ingress.yaml
  content/zh/examples/service/networking/nginx-secure-app.yaml
  content/zh/examples/service/networking/nginx-svc.yaml
  content/zh/examples/service/networking/run-my-nginx.yaml
  content/zh/examples/service/nginx-service.yaml
  content/zh/examples/windows/configmap-pod.yaml
  content/zh/examples/windows/daemonset.yaml
  content/zh/examples/windows/deploy-hyperv.yaml
  content/zh/examples/windows/deploy-resource.yaml
  content/zh/examples/windows/emptydir-pod.yaml
  content/zh/examples/windows/hostpath-volume-pod.yaml
  content/zh/examples/windows/secret-pod.yaml
  content/zh/examples/windows/simple-pod.yaml
Labels: cncf-cla: yes, language/zh, size/XL

#11453 Add temporary owners for 1.13 release
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/S

#11491 Add generated federation API Reference
  content/en/docs/reference/command-line-tools-reference/federation-apiserver.md
  content/en/docs/reference/command-line-tools-reference/federation-controller-manager.md
  content/en/docs/reference/federation/extensions/v1beta1/definitions.html
  content/en/docs/reference/federation/extensions/v1beta1/operations.html
  content/en/docs/reference/federation/federation/v1beta1/definitions.html
  content/en/docs/reference/federation/federation/v1beta1/operations.html
  content/en/docs/reference/federation/v1/definitions.html
  content/en/docs/reference/federation/v1/operations.html
  content/en/docs/reference/setup-tools/kubefed/kubefed-init.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-join.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-options.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-unjoin.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-version.md
  content/en/docs/reference/setup-tools/kubefed/kubefed.md
  content/en/docs/reference/setup-tools/kubefed/kubefed_init.md
  content/en/docs/reference/setup-tools/kubefed/kubefed_join.md
  content/en/docs/reference/setup-tools/kubefed/kubefed_options.md
  content/en/docs/reference/setup-tools/kubefed/kubefed_unjoin.md
  content/en/docs/reference/setup-tools/kubefed/kubefed_version.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XXL

#11487 Generate kubectl reference docs 1.13
  content/en/docs/reference/kubectl/kubectl.md
  static/docs/reference/generated/kubectl/kubectl-commands.html
  static/docs/reference/generated/kubectl/navData.js
  static/docs/reference/generated/kubectl/node_modules/jquery/dist/jquery.min.js
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XL

#11489 Add 1.13 API Reference
  content/en/docs/reference/_index.md
  content/en/docs/reference/kubernetes-api/index.md
  static/docs/reference/generated/kubernetes-api/v1.13/css/bootstrap.min.css
  static/docs/reference/generated/kubernetes-api/v1.13/css/font-awesome.min.css
  static/docs/reference/generated/kubernetes-api/v1.13/css/stylesheet.css
  static/docs/reference/generated/kubernetes-api/v1.13/fonts/FontAwesome.otf
  static/docs/reference/generated/kubernetes-api/v1.13/fonts/fontawesome-webfont.eot
  static/docs/reference/generated/kubernetes-api/v1.13/fonts/fontawesome-webfont.svg
  static/docs/reference/generated/kubernetes-api/v1.13/fonts/fontawesome-webfont.ttf
  static/docs/reference/generated/kubernetes-api/v1.13/fonts/fontawesome-webfont.woff
  static/docs/reference/generated/kubernetes-api/v1.13/fonts/fontawesome-webfont.woff2
  static/docs/reference/generated/kubernetes-api/v1.13/index.html
  static/docs/reference/generated/kubernetes-api/v1.13/jquery.scrollTo.min.js
  static/docs/reference/generated/kubernetes-api/v1.13/navData.js
  static/docs/reference/generated/kubernetes-api/v1.13/scroll.js
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XXL

#11497 modified config.toml for 1.13 release
  config.toml
Labels: approved, cncf-cla: yes, lgtm, size/M

#11495 modified config.toml for 1.13 release
  config.toml
Labels: approved, cncf-cla: yes, lgtm, size/M

#11496 modified config.toml for 1.13 release
  config.toml
Labels: approved, cncf-cla: yes, lgtm, size/M

#11493 modified for 1.13 release
  _config.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#11503 adding .Site. to Params.currentUrl
  layouts/shortcodes/deprecationwarning.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#11499 Add 1.13.0 Release notes
  content/en/docs/setup/release/notes.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XXL

#11498 Update federation-content-moved.md
  content/zh/includes/federation-content-moved.md
  content/zh/includes/federation-current-state.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#11476 Fix some grammar errors in custom-resources.md
  content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11508 zh-trans: add docs/search.md, /docs/tutorials/configuration/_index.md
  content/zh/docs/search.md
  content/zh/docs/tutorials/configuration/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11462 kubeadm GA blog post
  Makefile
  content/en/blog/_posts/2018-12-04-kubeadm-ga-release.md
  netlify.toml
  sass/_base.sass
  static/css/case-study-styles.css
  static/css/case-study-styles.css.map
  static/css/styles.css
  static/css/styles.css.map
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L

#11517 Fix coredns link
  content/en/docs/tasks/administer-cluster/coredns.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11454 Remove 1.13 reviewers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, sig/docs, size/XS

#11507 Updated Adform logo
  content/en/case-studies/adform/adform_featured_logo.png
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11452 zh-trans: add concepts/configuration/scheduler-perf-tuning
  content/zh/docs/concepts/configuration/scheduler-perf-tuning.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11523 Fix a typo in pod priority and preemption doc
  content/en/docs/concepts/configuration/pod-priority-preemption.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/scheduling, size/S

#11525 Update pod ready++ link
  content/en/docs/concepts/workloads/pods/pod-lifecycle.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11533 ko-trans: Fix duplicated overview index for concepts page
  content/ko/docs/concepts/overview/_index.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/XS

#11537 zh-trans: add getting-started-guides/...
  content/zh/docs/getting-started-guides/windows/OVN_OVS_Windows_Installer.png
  content/zh/docs/getting-started-guides/windows/UpstreamRouting.png
  content/zh/docs/getting-started-guides/windows/ovn_kubernetes.png
  content/zh/docs/getting-started-guides/windows/sample-l2bridge-wincni-config.json
  content/zh/docs/getting-started-guides/windows/windows-setup.png
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#11301 zh-trans: add case-studies/squarespace
  content/zh/case-studies/squarespace/index.html
  content/zh/case-studies/squarespace/squarespace_featured_logo.png
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11518 #11431 Remove load balance access task
  content/en/docs/tasks/access-application-cluster/load-balance-access-application-cluster.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L

#11527 change default enabled plugin from PersistentVolumeLabel to PersistentVolumeClaimResize
  content/en/docs/reference/access-authn-authz/admission-controllers.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11546 Fix references to patchMergeKey and patchStrategy in types.go
  content/en/docs/concepts/overview/object-management-kubectl/declarative-config.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11543 kube-apiserver: remove merge conflict marker
  content/en/docs/reference/command-line-tools-reference/kube-apiserver.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11540 Minor improvements on upgrade for kubeadm
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-12.md
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-13.md
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-ha-1-12.md
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-ha-1-13.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/S

#11441 Blog post about Shanghai NCW. Submitting for website.
  content/en/blog/_posts/2018-12-05-new-contributor-shanghai.md
  static/images/blog/2018-12-05-new-contributor-shanghai/attendees.png
  static/images/blog/2018-12-05-new-contributor-shanghai/noahabrahams.png
  static/images/blog/2018-12-05-new-contributor-shanghai/panel.png
  static/images/blog/2018-12-05-new-contributor-shanghai/yangli.png
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#11547 Update kubelet-tls-bootstrapping.md
  content/en/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11432 zh-trans: add pod.md
  content/zh/docs/reference/glossary/pod.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11550 Shanghai ncw post
  content/en/blog/_posts/2018-12-05-new-contributor-shanghai.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11534 kubeadm-ts-guide: add entry about centos and docker 1.13.87
  content/en/docs/setup/independent/troubleshooting-kubeadm.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/S

#11548 Fix link to k8s CoCC
  content/en/community/code-of-conduct.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11504 zh-trans: add /tutorials/_index.md
  content/zh/docs/tutorials/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11556 fixed typo and clarified mitigation steps.
  content/en/docs/setup/independent/troubleshooting-kubeadm.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11530 zh-trans: /docs/getting-started-guides/ubuntu/_index.md
  content/zh/docs/getting-started-guides/ubuntu/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11506 zh-trans content/en/docs/setup/independent/setup-ha-etcd-with-kubeadm.md
  content/zh/docs/setup/independent/setup-ha-etcd-with-kubeadm.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11516 fix the example for dns-pod-service
  content/en/docs/concepts/services-networking/dns-pod-service.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11475 Updated the word from "you" to "your"
  content/en/docs/tasks/administer-cluster/configure-multiple-schedulers.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11573 ja-trans: Translate setup/independent/_index.md
  content/ja/docs/setup/independent/_index.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS

#11569 Translate content/ja/docs/home/_index.md in Japanese
  content/ja/docs/home/_index.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/S

#11572 Translate content/ja/docs/setup/custom-cloud/_index.md in Japanese
  content/ja/docs/setup/custom-cloud/_index.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS

#11574 Translate content/en/docs/setup/on-premises-vm/_index.md in Japanese
  content/ja/docs/setup/on-premises-vm/_index.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS

#11576 Translate content/ja/docs/setup/release/_index.md in Japanese
  content/ja/docs/setup/release/_index.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS

#11580 ja-trans: Translate content/ja/docs/tutorials/kubernetes-basics/explore/_index.md in Japanese
  content/ja/docs/tutorials/kubernetes-basics/explore/_index.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS

#11582 Translate content/ja/docs/setup/turnkey/_index.md
  content/ja/docs/setup/turnkey/_index.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS

#11579 Translate content/ja/docs/tutorials/kubernetes-basics/update/_index.m…
  content/ja/docs/tutorials/kubernetes-basics/update/_index.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS

#11583 Translated Tutorials/Learn Kubenetes Basics/Deploy an App in Japanese.
  content/ja/docs/tutorials/kubernetes-basics/deploy-app/_index.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS

#11584 trans-jp: tutorials/kubernetes-basics/expose/_index.md
  content/ja/docs/tutorials/kubernetes-basics/expose/_index.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS

#11577 Dev 1.13 ja.1 tutorials kubernetes basics scale
  content/ja/docs/tutorials/kubernetes-basics/scale/_index.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS

#11427 zh_trans: docs/setup/independent/create-cluster-kubeadm.md & docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_addon.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_addon.md
  content/zh/docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XXL

#11429 zh-trans: add replica-set.md
  content/zh/docs/reference/glossary/replica-set.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11509 zh-trans: add controller-metrics.md
  content/zh/docs/concepts/cluster-administration/controller-metrics.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#11449 zh-trans: add concepts/workloads/pods/pod.md
  content/zh/docs/concepts/workloads/pods/pod.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11559 zh-trans: content/zh/docs/reference/glossary/kubelet.md
  content/zh/docs/reference/glossary/kubelet.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11590 Blog NCW Shanghai: image captions and copyediting
  content/en/blog/_posts/2018-12-05-new-contributor-shanghai.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#11593 Remove distracting, superfluous links from Learn Kubernetes Basics
  content/en/docs/tutorials/kubernetes-basics/_index.html
  content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
  content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
  content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S, team/google

#11437 [korean] replacing "run" with "create deployment"
  content/ko/docs/tutorials/hello-minikube.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/XS

#11544 ko-trans: Update outdated files in dev-1.13-ko.4
  content/ko/docs/concepts/overview/what-is-kubernetes.md
  content/ko/docs/concepts/workloads/_index.md
  content/ko/docs/concepts/workloads/pods/pod-overview.md
  content/ko/docs/home/_index.md
  content/ko/docs/reference/_index.md
  content/ko/docs/setup/pick-right-solution.md
  content/ko/docs/setup/release/_index.md
  content/ko/docs/setup/release/building-from-source.md
  content/ko/docs/setup/scratch.md
  content/ko/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
  content/ko/docs/tutorials/kubernetes-basics/_index.html
  content/ko/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
  content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
  content/ko/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/explore/explore-intro.html
  content/ko/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
  content/ko/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/scale/scale-intro.html
  content/ko/docs/tutorials/kubernetes-basics/update/update-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#11604 Update storage-classes.md
  content/en/docs/concepts/storage/storage-classes.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11599 zh-trans: add access-authn-authz/_index.md command-line-tools-reference/_index.md
  content/zh/docs/reference/access-authn-authz/_index.md
  content/zh/docs/reference/command-line-tools-reference/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11430 zh-trans: add podreset.md
  content/zh/docs/reference/glossary/podpreset.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11442 zh-trans: add kube-proxy.md
  content/zh/docs/reference/glossary/kube-proxy.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11444 zh-trans: add volume-plugin.md
  content/zh/docs/reference/glossary/volume-plugin.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11446 zh-trans: add job.md
  content/zh/docs/reference/glossary/job.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11459 zh-trans: add platform-developer.md
  content/zh/docs/reference/glossary/platform-developer.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11602 zh-trans: /docs/tasks/configure-pod-container/configure-volume-storage.md
  content/zh/docs/tasks/configure-pod-container/configure-volume-storage.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11448 zh-trans: add cri.md
  content/zh/docs/setup/cri.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11558 zh-trans: add docs/concepts/overview/working-with-objects/annotations.md
  content/zh/docs/concepts/overview/working-with-objects/annotations.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11557 zh-trans: add docs/concepts/overview/working-with-objects/names.md
  content/zh/docs/concepts/overview/working-with-objects/names.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#11597 zh-trans: add docs/getting-started-guides/alternatives.md
  content/zh/docs/getting-started-guides/alternatives.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11494 Update docs for taints and their version promotions
  content/en/docs/concepts/configuration/taint-and-toleration.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11060 Add information on supported version skew and upgrade order
  content/en/docs/reference/using-api/deprecation-policy.md
  content/en/docs/setup/independent/create-cluster-kubeadm.md
  content/en/docs/setup/independent/install-kubeadm.md
  content/en/docs/setup/version-skew-policy.md
  content/en/docs/user-journeys/users/cluster-operator/foundational.md
  data/setup.yml
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/api-machinery, sig/architecture, sig/cli, sig/cluster-lifecycle, sig/network, sig/node, sig/pm, sig/release, sig/scheduling, size/L

#11628 Fix page error : /zh/docs/
  content/zh/docs/doc-contributor-tools/README.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#11611 zh-trans:/docs/tasks/administer-federation/namespaces.md
  content/zh/docs/tasks/administer-federation/namespaces.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11633 zh-trans: add docs/getting-started-guides/ubuntu/upgrades.md
  content/zh/docs/getting-started-guides/ubuntu/upgrades.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11636 zh-trans: add /zh/docs/concepts/workloads/pods/podpreset.md
  content/zh/docs/concepts/workloads/pods/podpreset.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11624 zh-trans: add docs/getting-started-guides/ubuntu/installation.md
  content/zh/docs/getting-started-guides/ubuntu/installation.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XL

#11621 zh-trans: add docs/getting-started-guides/ubuntu/logging.md
  content/zh/docs/getting-started-guides/ubuntu/logging.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#11606 zh-trans: add kubeadm/generated/...
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_upload_from-file.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_upload_from-flags.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_view.md
Labels: cncf-cla: yes, language/zh, lgtm, size/L

#11601 zh-trans: add docs/reference/glossary/container-lifecycle-hooks.md
  content/zh/docs/reference/glossary/container-lifecycle-hooks.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#11566 zh-trans content/en/docs/setup/certificates.md
  content/zh/docs/setup/certificates.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11565 zh-trans: add docs/concepts/overview/working-with-objects/field-selectors.md
  content/zh/docs/concepts/overview/working-with-objects/field-selectors.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11563 zh-trans: add _index.md
  content/zh/docs/getting-started-guides/windows/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XL

#11510 zh-trans: add docs/concepts/cluster-administration/kubelet-garbage-collection.md
  content/zh/docs/concepts/cluster-administration/kubelet-garbage-collection.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11455 zh-trans: add statefulset.md
  content/zh/docs/concepts/workloads/controllers/statefulset.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11647 zh-trans: add docs/getting-started-guides/ubuntu/rancher.md
  content/zh/docs/getting-started-guides/ubuntu/rancher.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XL

#11652 update PULL_REQUEST_TEMPLATE to include zh-i18n info
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#11474 zh-trans: add includes/default-storage-class-prereqs.md
  content/zh/includes/default-storage-class-prereqs.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#11674 ZH-trans： Update kubeadm_config.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#11673 ZH-trans: Update kubeadm_config_view.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_view.md
Labels: cncf-cla: yes, do-not-merge/hold, language/zh, size/XS

#11609 Fix the build doesn't pass at dev-1.13-ja.1
  content/ja/case-studies/_index.html
  content/ja/docs/tutorials/clusters/_index.md
  content/ja/docs/tutorials/clusters/apparmor.md
  content/ja/docs/tutorials/clusters/deny-write.profile
  content/ja/docs/tutorials/configuration/_index.md
  content/ja/docs/tutorials/configuration/configure-redis-using-configmap.md
  content/ja/docs/tutorials/online-training/_index.md
  content/ja/docs/tutorials/online-training/overview.md
  content/ja/docs/tutorials/services/_index.md
  content/ja/docs/tutorials/services/source-ip.md
  content/ja/docs/tutorials/stateful-application/_index.md
  content/ja/docs/tutorials/stateful-application/basic-stateful-set.md
  content/ja/docs/tutorials/stateful-application/cassandra.md
  content/ja/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md
  content/ja/docs/tutorials/stateful-application/zookeeper.md
  content/ja/docs/tutorials/stateless-application/_index.md
  content/ja/docs/tutorials/stateless-application/expose-external-ip-address.md
  content/ja/docs/tutorials/stateless-application/guestbook.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XXL

#11639 Fix typos in add-entries-to-pod-etc-hosts-with-host-aliases
  content/en/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11678 fix typo in high-availabilty
  content/en/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11667 Typo fix：control plan-> control plane
  content/en/docs/tasks/administer-federation/secret.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11682 ZH-trans：Update _index.md
  content/zh/docs/getting-started-guides/windows/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#11640 Typo: repeated words
  content/en/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11524 blog: add etcd post for December 11, 2018
  content/en/blog/_posts/2018-12-11-current-status-and-future-roadmap.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#11651 zh-trans: add docs/getting-started-guides/ubuntu/storage.md
  content/zh/docs/getting-started-guides/ubuntu/storage.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11626 zh-trans: add docs/getting-started-guides/ubuntu/networking.md
  content/zh/docs/getting-started-guides/ubuntu/networking.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#11447 Remove duplicated content.
  content/en/docs/tasks/inject-data-application/distribute-credentials-secure.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11451 Typo fixed: Kuberentes -> Kubernetes
  content/en/blog/_posts/2016-07-00-Kubernetes-In-Rancher-Further-Evolution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11535 fix audit backends decription
  content/en/docs/tasks/debug-application-cluster/audit.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11598 Update the version in the example
  content/en/docs/tasks/configure-pod-container/assign-pods-nodes.md
  content/en/docs/tasks/debug-application-cluster/debug-application-introspection.md
  content/en/docs/tutorials/services/source-ip.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#11603 fix the command for checking dns pod
  content/en/docs/tasks/administer-cluster/dns-debugging-resolution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11630 modified confusion of cert and key.
  content/en/docs/setup/certificates.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#11436 OpenContrail -> Tungsten Fabric
  content/en/docs/concepts/cluster-administration/networking.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11697 Fix Wrong document
  content/en/docs/tasks/tools/install-kubectl.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11679 Typo fix: federation control plan->federation control plane
  content/en/docs/tasks/administer-federation/namespaces.md
  content/en/docs/tasks/administer-federation/secret.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11683 zh-trans: add some _index.md files
  content/zh/docs/setup/custom-cloud/_index.md
  content/zh/docs/setup/on-premises-vm/_index.md
  content/zh/docs/setup/release/_index.md
Labels: cncf-cla: yes, language/zh, size/M

#11660 zh-trans: add some template files
  content/zh/docs/templates/feature-state-deprecated.txt
  content/zh/docs/templates/feature-state-stable.txt
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#11701 zh-trans: update docs/_index.md
  content/zh/docs/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#11659 ZH-trans: add /kubeadm/generated/...
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_pull.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_migrate.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print-default.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11691 zh_trans:/blog/_posts/2018-06-07-dynamic-ingress-kubernetes.md
  content/cn/blog/_posts/2018-06-07-dynamic-ingress-kubernetes.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#11706 ADD content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_u…
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_plan.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11700 kubeadm-ha: fix variables under "initial-cluster"
  content/en/docs/setup/independent/setup-ha-etcd-with-kubeadm.md
Labels: approved, cncf-cla: yes, kind/bug, language/en, lgtm, priority/important-longterm, sig/cluster-lifecycle, size/XS

#11714 zh-trans: move files from cn to zh dir
  content/zh/blog/_posts/2018-06-07-dynamic-ingress-kubernetes.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#11641 zh_trans: docs/reference/_index.md
  content/zh/docs/reference/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11695 zh-trans: add docs/tasks/tools/install-minikube.md
  content/zh/docs/tasks/tools/install-minikube.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11658 zh-trans: add docs/concepts/overview/working-with-objects/namespaces.md
  content/zh/docs/concepts/overview/working-with-objects/namespaces.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11649 zh-trans: /docs/getting started guides/ubuntu/troubleshooting.md
  content/zh/docs/getting-started-guides/ubuntu/troubleshooting.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11644 zh-trans update-daemon-set.md
  content/zh/docs/tasks/manage-daemon/update-daemon-set.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11625 zh-trans: add docs/getting-started-guides/ubuntu/decommissioning.md
  content/zh/docs/getting-started-guides/ubuntu/decommissioning.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11637 zh-trans force-delete-stateful-set-pod.md
  content/zh/docs/tasks/run-application/force-delete-stateful-set-pod.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11585 ja-trans: translate content/ja/_index.html
  content/ja/_index.html
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/S

#11690 zh-trans /docs/tasks/debug-application-cluster/monitor-node-health.md
  content/zh/docs/tasks/debug-application-cluster/monitor-node-health.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11732 ZH-trans: In v1.12 version update install-kubeadm
  content/zh/docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11731 ZH-trans: Update install-kubeadm.md
  content/zh/docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11721 ja-trans: add docs/_index.md (cherry-pick from dev-1.12-ja.1)
  content/ja/docs/_index.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS

#11735 Remove copied docs/index.md by mistake.
  content/ja/docs/index.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS

#11614 Add flexVolume to list and add anchor.
  content/en/docs/concepts/storage/volumes.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11736 fix link in reconfigure-kubelet
  content/en/docs/tasks/administer-cluster/reconfigure-kubelet.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11726 zh_trans: Fix the page errors of contribute
  content/zh/docs/contribute/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S
