Repository kubernetes/website, pull requests merged in 2018-10, with the labels that each got.

#10393 blog: health-checking-grpc
  content/en/blog/_posts/2018-10-01-health-checking-grpc.md
  static/images/blog/2019-09-30-health-checking-grpc/grpc_health_probe.png
  static/images/blog/2019-09-30-health-checking-grpc/options.png
Labels: approved, cncf-cla: yes, lgtm, size/M

#10215 Move sass OWNERS to source instead of output
  assets/sass/OWNERS
Labels: cncf-cla: yes, lgtm, size/XS

#10355 Merge missing translations
  Makefile
  config.toml
  content/no/blog/_index.md
  content/no/blog/_posts/2018-09-06-2018-steering-committee-election-cycle-kicks-off.md
  content/no/case-studies/_index.md
  content/no/case-studies/adform/index.html
  content/no/docs/_index.md
  content/no/docs/contribute/_index.md
  content/no/docs/home/_index.md
  content/no/docs/reference/_index.md
  content/no/docs/reference/glossary/container.md
  content/no/docs/reference/glossary/index.md
  content/no/docs/setup/_index.md
  content/no/docs/setup/pick-right-solution.md
  content/no/docs/tutorials/kubernetes-basics/_index.md
  i18n/en.toml
  i18n/no.toml
  layouts/blog/list.html
  layouts/case-studies/list.html
  layouts/docs/docsportal_home.html
  layouts/docs/glossary.html
  layouts/partials/blog/archive.html
  layouts/partials/docs/browse.html
  layouts/partials/docs/glossary-terms.html
  layouts/partials/tree.html
  layouts/shortcodes/glossary_tooltip.html
  netlify.toml
  resources/_gen/assets/sass/sass/styles.sass_a6e533854c4de092afe9278041939937.content
  resources/_gen/assets/sass/sass/styles.sass_a6e533854c4de092afe9278041939937.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#10373 Temporarily remove Hugo Pipes Sass conversion
  Makefile
  content/en/docs/contribute/intermediate.md
  layouts/partials/css.html
  layouts/shortcodes/hugoVersion.html
  resources/_gen/assets/sass/sass/case_study_styles.sass_cb957da2191fde4902dd41b139c8069d.content
  resources/_gen/assets/sass/sass/case_study_styles.sass_cb957da2191fde4902dd41b139c8069d.json
  resources/_gen/assets/sass/sass/styles.sass_cb957da2191fde4902dd41b139c8069d.content
  resources/_gen/assets/sass/sass/styles.sass_cb957da2191fde4902dd41b139c8069d.json
  sass/OWNERS
  sass/_base.sass
  sass/_case-studies.sass
  sass/_desktop.sass
  sass/_reset.sass
  sass/_size.sass
  sass/_skin.sass
  sass/_tablet.sass
  sass/case-study-styles.sass
  sass/styles.sass
  scripts/sass.sh
  static/css/case-study-styles.css
  static/css/case-study-styles.css.map
  static/css/case_study_styles.css
  static/css/case_study_styles.sass
  static/css/styles.css
  static/css/styles.css.map
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#9696 Added api version in authn and authz example.
  content/en/docs/reference/access-authn-authz/authentication.md
  content/en/docs/reference/access-authn-authz/webhook.md
Labels: Docs LGTM, Tech Review: Open Issues, approved, cncf-cla: yes, lgtm, sig/auth, size/XS

#10458 Remove Dynatrace per PR 9504
  content/en/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10459 kubeadm-init: update link about v1alpha3 example
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, sig/cluster-lifecycle, sig/docs, size/XS

#10464 Remove Sass assets from repo
  assets/sass/OWNERS
  assets/sass/_base.sass
  assets/sass/_case-studies.sass
  assets/sass/_desktop.sass
  assets/sass/_reset.sass
  assets/sass/_size.sass
  assets/sass/_skin.sass
  assets/sass/_tablet.sass
  assets/sass/case_study_styles.sass
  assets/sass/styles.sass
  resources/_gen/assets/sass/sass/case_study_styles.sass_ba3494e18e2339acfc9f811090f8a3d1.content
  resources/_gen/assets/sass/sass/case_study_styles.sass_ba3494e18e2339acfc9f811090f8a3d1.json
  resources/_gen/assets/sass/sass/styles.sass_146085a92036d31fa476cb2cbb0682ce.content
  resources/_gen/assets/sass/sass/styles.sass_146085a92036d31fa476cb2cbb0682ce.json
  resources/_gen/assets/sass/sass/styles.sass_a6e533854c4de092afe9278041939937.content
  resources/_gen/assets/sass/sass/styles.sass_a6e533854c4de092afe9278041939937.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#10457 Fix typo: folllowing -> following
  content/en/docs/tutorials/stateful-application/cassandra.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10467 Blog post: KubeDirector
  content/en/blog/_posts/2018-10-03-kubedirector.md
  static/images/blog/2018-10-03-kubedirector/kubedirector.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#10409 update version info
  content/en/docs/tutorials/services/source-ip.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10185 Update overview.md
  content/en/docs/tutorials/online-training/overview.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10206 Warn LXD users with an IPv6-enabed bridge
  content/en/docs/getting-started-guides/ubuntu/local.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9880 Add header-checking function
  .gitignore
  Makefile
  functions-src/deploy-succeeded.js
  netlify.toml
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#10336 Added cron job monitoring
  content/en/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10478 Fix CSS generation error
  sass/_base.sass
  static/css/case-study-styles.css
  static/css/case-study-styles.css.map
  static/css/styles.css
  static/css/styles.css.map
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10461 Fix links to featured case studies
  layouts/case-studies/list.html
Labels: approved, cncf-cla: yes, kind/bug, kind/cleanup, language/en, lgtm, size/XS

#10463 Fix CSS for case study pages
  static/css/style_case_studies.css
Labels: approved, cncf-cla: yes, kind/bug, kind/design, language/en, lgtm, size/M

#10475 fix the CRI-installation in install-kubuadm
  content/en/docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/docs, size/XS

#10456 Fix "compared compared"
  content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10442 Update nginx-deployment.yaml
  content/en/examples/controllers/nginx-deployment.yaml
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10441 Update Dockerfile
  content/en/examples/minikube/Dockerfile
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10443 Update deployment.md
  content/en/docs/concepts/workloads/controllers/deployment.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10481 Fix typos in concept pages
  content/en/docs/concepts/configuration/manage-compute-resources-container.md
  content/en/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
  content/en/docs/concepts/extend-kubernetes/extend-cluster.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10112 Update and reorder sub contents
  content/en/docs/tasks/administer-cluster/coredns.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10122 Fix broken link, fix & add redirects
  content/en/docs/tasks/tls/certificate-rotation.md
  static/_redirects
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10150 install-kubeadm: Extend set SELinux in permissive mode
  content/en/docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/docs, size/XS

#10191 bump version of event-exporter
  content/en/examples/debug/event-exporter.yaml
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10286 Add pointer to k8s community site
  content/en/docs/contribute/_index.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10287 fix some links with 404 error
  content/en/docs/setup/minikube.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10290 Update update-daemon-set.md
  content/en/docs/tasks/manage-daemon/update-daemon-set.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10297 Cancel the invalid hyperlink
  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/XS

#10327 Clarify pod.md
  content/en/docs/concepts/workloads/pods/pod.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10372 Fix link to deploy node.js app
  content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10380 Update description of StatefulSet behavior on delete
  content/en/docs/concepts/workloads/controllers/statefulset.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10386 Trivial typo fixes
  content/en/docs/contribute/start.md
  content/en/docs/setup/_index.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10406 Modified version information
  content/en/docs/tasks/administer-cluster/sysctl-cluster.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10408 update version info
  content/en/docs/tasks/debug-application-cluster/debug-application-introspection.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10421 Fix misspelled plugin configuration option
  content/en/docs/tasks/administer-cluster/dns-custom-nameservers.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10423 Remove reference to minikube `get-k8s-versions`
  content/en/docs/setup/minikube.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10427 Removed "touch" on sources.list.d
  content/en/docs/tasks/tools/install-kubectl.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10412 minimum spell error
  content/en/docs/setup/scratch.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10429 add Jaguar project description
  content/en/docs/concepts/cluster-administration/networking.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10417 fix the command output
  content/en/docs/concepts/services-networking/connect-applications-service.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10435 update link for cri-containerd on kubeadm install page
  content/en/docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10440 Update hello-minikube.md
  content/en/docs/tutorials/hello-minikube.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10453 Add kubectl cheatsheet link from the community
  content/en/docs/reference/kubectl/cheatsheet.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10199 Capitalized "Pod" in multiple locations
  content/en/docs/contribute/style/style-guide.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10209 Rewrite links for environment-variable-expose-pod-information to new location
  content/cn/docs/tasks/inject-data-application/define-environment-variable-container.md
  content/cn/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
  content/en/docs/tasks/inject-data-application/define-environment-variable-container.md
  content/en/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
  data/tasks.yml
Labels: approved, cncf-cla: yes, kind/bug, language/en, lgtm, size/S

#10256 resolve some semantics around ABAC and RBAC
  content/en/docs/reference/access-authn-authz/abac.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10307 fix the command output
  content/en/docs/concepts/cluster-administration/manage-deployment.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10407 The version information displayed on the page is outdated
  content/en/docs/tasks/configure-pod-container/assign-pods-nodes.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10424 Fix link formatting
  content/en/docs/concepts/containers/runtime-class.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10175 improved and updated rollout history information
  content/en/docs/concepts/workloads/controllers/deployment.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10182 Update hello-minikube.md
  content/en/docs/tutorials/hello-minikube.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10439 Update minikube.md
  content/en/docs/setup/minikube.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10436 Add support information for AMD GPUs
  content/en/docs/tasks/manage-gpus/scheduling-gpus.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10304 Newsletter Signup
  content/en/_index.html
  resources/_gen/assets/sass/cn/sass/styles.sass_a6e533854c4de092afe9278041939937.content
  resources/_gen/assets/sass/cn/sass/styles.sass_a6e533854c4de092afe9278041939937.json
  resources/_gen/assets/sass/sass/styles.sass_a6e533854c4de092afe9278041939937.content
  resources/_gen/assets/sass/sass/styles.sass_a6e533854c4de092afe9278041939937.json
  sass/_base.sass
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XXL

#10422 Followup to PR#10259
  content/en/docs/tasks/extend-kubectl/kubectl-plugins.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10411 Change the version information in the page to v1.12.0
  content/en/docs/setup/multiple-zones.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10487 fix typo
  content/en/blog/_posts/2018-09-18-2018-linkerd-2.0.md
Labels: approved, cncf-cla: yes, kind/cleanup, language/en, lgtm, size/XS

#10490 fix typo in runtime class
  content/en/docs/concepts/containers/runtime-class.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10484 Adding Non-Code Contributions blog post
  content/en/blog/_posts/2018-10-04-non-code-contributors-guide.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10376 fixed a typo in docs/concepts/configuration/pod-priority-preemption.md
  content/en/docs/concepts/configuration/pod-priority-preemption.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#9980 Update resource-usage-monitoring.md
  content/en/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10494 fix capitalization
  content/en/blog/_posts/2018-10-03-kubedirector.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10495 add myself and remove Jared from security contacts
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10499 Update to newsletter signup
  content/en/_index.html
  i18n/en.toml
  layouts/index.html
  sass/_base.sass
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10506 fix typo: remove duplicate words
  content/ko/docs/setup/_index.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/XS

#10474 Fixes typo
  content/en/docs/concepts/workloads/controllers/garbage-collection.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10505 fix typo: remove duplicate 'the'
  content/en/blog/_posts/2018-10-04-non-code-contributors-guide.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10508 fix typo: remove duplicate words
  content/en/includes/partner-script.js
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10455 fix typo: remove redundant space
  content/en/case-studies/capital-one/index.html
  content/en/case-studies/peardeck/index.html
  content/en/case-studies/wink/index.html
Labels: approved, cncf-cla: yes, kind/cleanup, language/en, lgtm, size/XS

#10497 Add jaredbhatti as an approver
  OWNERS
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10513 Fix doc issues
  content/en/docs/reference/federation/extensions/v1beta1/definitions.html
  content/en/docs/reference/federation/v1/definitions.html
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10517 Fix edit page buttons
  layouts/docs/baseof.html
  layouts/partials/docs/content_page.html
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS, team/google

#10183 update description about cron jobs
  content/en/docs/tasks/job/automated-tasks-with-cron-jobs.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10433 add Jaguar project description
  content/en/docs/concepts/cluster-administration/networking.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10538 Blog post for 5 Days of K8s: Azure VMSS
  content/en/blog/_posts/2018-10-08-support-for-azure-vmss.md
  static/images/blog/2018-10-08-support-for-azure-vmss/ca-functionality.png
  static/images/blog/2018-10-08-support-for-azure-vmss/cloud-provider-components.png
  static/images/blog/2018-10-08-support-for-azure-vmss/cluster-autoscaler.png
  static/images/blog/2018-10-08-support-for-azure-vmss/sample-azure-cluster.png
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L

#10542 Add microk8s to pick-right-solution.md
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10543 Add microk8s to foundational.md
  content/en/docs/user-journeys/users/application-developer/foundational.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10550 Fix the kubectl subcommands links.
  content/en/docs/reference/kubectl/kubectl.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10515 Fix command issues of apply-resource-quota-limit
  content/cn/docs/tasks/administer-cluster/apply-resource-quota-limit.md
Labels: approved, cncf-cla: yes, language/cn, lgtm, size/XS

#10501 remove imported community files per issue 10184
  content/en/docs/community/_index.md
  content/en/docs/community/devel.md
  content/en/docs/community/guide.md
  content/en/docs/community/keps.md
  content/en/docs/community/mentoring.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XL

#10498 networking.md: Markdown fix
  content/en/docs/concepts/cluster-administration/networking.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10500 Fix front matter, federation tools ref
  content/en/docs/reference/command-line-tools-reference/federation-apiserver.md
  content/en/docs/reference/command-line-tools-reference/federation-controller-manager.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10399 Glossary container env
  content/en/docs/reference/glossary/container-env-variables.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10536 update slack link
  content/en/blog/_posts/2018-10-03-kubedirector.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10558 typo in StatefulSet docs
  content/en/docs/concepts/workloads/controllers/statefulset.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10557 fix discription about horizontal pod autoscale
  content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10556 Remove redundant symbols
  static/css/blog.css
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10554 Fix issue #10520 (kubectl comond link in cluster-management)
  content/en/docs/tasks/administer-cluster/cluster-management.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10534 Update api-concepts.md
  content/en/docs/reference/using-api/api-concepts.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10559 Revert "Fix command issues of apply-resource-quota-limit"
  content/cn/docs/tasks/administer-cluster/apply-resource-quota-limit.md
Labels: cncf-cla: yes, language/cn, size/XS

#10530 Update memory-constraint-namespace.md
  content/en/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10562 Blog: Introducing Volume Snapshot Alpha for Kubernetes
  content/en/blog/_posts/2018-10-09-volume-snapshot-alpha.md
  static/images/blog/2018-10-09-volume-snapshot-alpha/snapshot.png
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L

#10566 Clean up OWNERS* files with permissions by alias
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10567 Minor typo fix
  content/en/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10563 Remove unneeded move page
  content/en/docs/concepts/extend-kubernetes/extend-cluster.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10537 Update README instructions and Docker image
  Dockerfile
  README.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10539 address additional comments from pr #10259
  content/en/docs/tasks/extend-kubectl/kubectl-plugins.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10516 security: use security@kubernetes.io alias
  content/en/docs/reference/issues-security/security.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10568 Remove duplication of `spec:`
  content/en/docs/concepts/workloads/controllers/jobs-run-to-completion.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10480 Additional Documentation
  content/en/docs/tutorials/online-training/overview.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10576 Blog Post: RuntimeClass
  content/en/blog/_posts/2018-10-10-runtimeclass.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10575 Fixes typo in resource-quotas.md
  content/en/docs/concepts/policy/resource-quotas.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10571 Update Flannel manifest URL
  content/en/docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10523 Remove links for older versions of kubernetes
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-upgrade.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/docs, size/XS

#10586 Blog Post: Topology Aware Volume Provisioning
  content/en/blog/_posts/2018-10-11-topology-aware-volume-provisioning.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L

#10587 adding jimangel as reviewer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10580 Fix ingress class annotation example links
  content/en/docs/concepts/services-networking/ingress.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10593 Fix a typo in OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10596 Tweak Horizontal Pod Autoscaler documentation
  content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10603 Update PR template for 1.13 release
  .github/PULL_REQUEST_TEMPLATE.md
  content/en/docs/contribute/start.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10605 Fix Hugo config.toml as valid
  config.toml
Labels: approved, cncf-cla: yes, kind/bug, language/en, lgtm, size/XS

#10610 Fix build failure by adding example and include files
  content/zh/docs/reference/tools.md
  content/zh/examples/application/job/redis/job.yaml
  content/zh/examples/application/job/redis/worker.py
  content/zh/examples/audit/audit-policy.yaml
  content/zh/examples/pods/pod-nginx.yaml
  content/zh/includes/task-tutorial-prereqs.md
  content/zh/includes/user-guide-content-moved.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#10598 reference missing ('kubelet config annotate-cri') phase on additional controller nodes
  content/en/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/XS

#10570 Add stewart-yu into sig-docs-en-owners group
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10592 Add idealhack as a reviewer
  OWNERS_ALIASES
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, language/en, lgtm, size/XS

#10615 Update deployment.md
  content/en/docs/concepts/workloads/controllers/deployment.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10600 adding missing step for additional control plane nodes
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-ha.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/XS

#10616 Blog Post: 2018 Steering Committee Election Results
  content/en/blog/_posts/2018-10-15-steering-election-results.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10620 Typo Fix
  content/en/blog/_posts/2018-10-15-Steering-Election-Results.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10614 fix some typos
  content/en/blog/_posts/2018-07-16-kubernetes-1.11-release-interview.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10169 Added CSS height property to #oceanNodes main to fix spacing in Firefox
  resources/_gen/assets/sass/sass/styles.sass_a6e533854c4de092afe9278041939937.content
  sass/_tablet.sass
  static/css/styles.css
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10519 Fix broken links for Korean tutorial pages
  content/ko/docs/tutorials/kubernetes-basics/_index.html
  content/ko/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
  content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
  content/ko/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/explore/explore-intro.html
  content/ko/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
  content/ko/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/scale/scale-intro.html
  content/ko/docs/tutorials/kubernetes-basics/update/update-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/M

#10621 Use CoCC email for reporting CoC violations
  CONTRIBUTING.md
  content/en/community/_index.html
  content/en/community/code-of-conduct.md
  content/en/community/static/cncf-code-of-conduct.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10193 Added Giant Swarm to On-Prem and Turnkey
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10392 Fixing a small issue
  content/en/docs/getting-started-guides/ubuntu/backups.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10425 Fixed typo
  content/en/blog/_posts/2017-01-00-Running-Mongodb-On-Kubernetes-With-Statefulsets.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10553 Fix javascript reference in API docs
  static/docs/reference/generated/kubernetes-api/v1.12/index.html
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10572 fix typo
  content/en/blog/_posts/2018-10-08-support-for-azure-vmss.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10624 Revert "Typo Fix"
  content/en/blog/_posts/2018-10-15-Steering-Election-Results.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10544 Use masked white logo for ancestry
  content/en/case-studies/ancestry/index.html
  static/images/ancestry_logo.png
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10173 Change deb repo from http to https
  content/en/docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10626 Fix a typo in implementation-details.md
  content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10072 Improve mobile user experience on pages under /docs
  resources/_gen/assets/sass/sass/styles.sass_a6e533854c4de092afe9278041939937.content
  sass/_base.sass
  static/css/case-study-styles.css
  static/css/case-study-styles.css.map
  static/css/styles.css
  static/css/styles.css.map
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10630 Add NA contributor Summit Blog Post
  content/en/blog/_posts/2018-10-16-kubernetes-2018-north-american-contributor-summit.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10640 Correct KubeCon + CloudNativeCon event name in contrib summit blog post
  content/en/blog/_posts/2018-10-16-kubernetes-2018-north-american-contributor-summit.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10647 audit api version has been updated to v1
  content/en/examples/audit/audit-policy.yaml
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10642 Fix tryKubernetes button
  sass/_base.sass
  static/css/case-study-styles.css
  static/css/case-study-styles.css.map
  static/css/styles.css
  static/css/styles.css.map
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10118 Adding Kubernetes Kubeadm + Digital Rebar integration for On-Prem installs
  content/en/docs/setup/on-premises-metal/krib.md
  content/en/docs/setup/pick-right-solution.md
  content/en/docs/tasks/administer-cluster/cluster-management.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/M

#10540 tasks-with-cron-jobs: explain the steps expression
  content/en/docs/tasks/job/automated-tasks-with-cron-jobs.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10466 Blog Post: Network bootable servers farm with LTSP (some fixes)
  content/en/blog/_posts/2018-10-02-network-bootable-farm-with-ltsp.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10653 fix glossary entry for quantity
  content/en/docs/reference/glossary/quantity.md
  content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10663 Show clusterIP in Services diagrams instead of ServiceIP
  content/en/docs/concepts/services-networking/service.md
  static/images/docs/services-iptables-overview.png
  static/images/docs/services-iptables-overview.svg
  static/images/docs/services-ipvs-overview.png
  static/images/docs/services-ipvs-overview.svg
  static/images/docs/services-userspace-overview.png
  static/images/docs/services-userspace-overview.svg
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10597 fix the output for rolling back a deployment
  content/en/docs/concepts/workloads/controllers/deployment.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#10509 Blog Post: Tips first KubeCon Presentation (Pt. 1)
  content/en/blog/_posts/2018-10-18-tips-for-first-kubecon-presentation-part-1.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10649 update Deployment.md
  content/en/docs/concepts/workloads/controllers/deployment.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#10693 Fix a broken link in /docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-ha/
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-ha.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/docs, size/XS
