Repository kubernetes/website, pull requests merged in 2018-03, with the labels that each got.

#7224 Rename network-plugin-dir kubelet flag to cni-bin-dir
  docs/concepts/cluster-administration/network-plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7569 fix golang version
  docs/home/contribute/generated-reference/federation-api.md
  docs/home/contribute/generated-reference/kubectl.md
  docs/home/contribute/generated-reference/kubernetes-api.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7571 Adding cri-containerd to supported cri runtimes
  docs/reference/setup-tools/kubeadm/kubeadm-init.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7572 fix case study description
  case-studies/blackrock.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7574 remove description kubectl --show-all
  docs/concepts/workloads/controllers/jobs-run-to-completion.md
  docs/tasks/job/parallel-processing-expansion.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7579 Moved more recent info to the top, fixed a typo
  docs/tasks/manage-gpus/scheduling-gpus.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#7592 fix description about contribute style guide
  docs/home/contribute/style-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7589 fix description about KUBECONFIG
  docs/concepts/configuration/organize-cluster-access-kubeconfig.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7588 fix description about cni
  docs/concepts/cluster-administration/networking.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7585 Remove no longer existing log message in kubeadm.
  docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7587 fix description about MutatingAdmissionWebhook and ValidatingAdmissionWebhook
  docs/admin/admission-controllers.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7590 fix description about persistent volume binding
  docs/concepts/storage/persistent-volumes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7613 Update MacOS instructions to use curl
  docs/getting-started-guides/kops.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7603 Fixed typo
  docs/concepts/workloads/controllers/cron-jobs.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7609 Fix indentation for local StorageClass
  docs/concepts/storage/storage-classes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7611 Doc change for configurable pod resolv.conf Beta
  docs/concepts/services-networking/custom-dns.yaml
  docs/concepts/services-networking/dns-pod-service.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7601 Update kubespray docs
  docs/getting-started-guides/kubespray.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7597 fix description about out of resource handling
  docs/tasks/administer-cluster/out-of-resource.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7598 fix description about zookeeper
  docs/tutorials/stateful-application/zookeeper.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7594 fix description about kubeadm
  docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7593 fix description about kubeadm
  docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7595 fix description about kubeadm implementation details
  docs/reference/setup-tools/kubeadm/implementation-details.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7596 fix description about api concepts
  docs/reference/api-concepts.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7582 Use standard stress utility in examples
  docs/tasks/configure-pod-container/assign-memory-resource.md
  docs/tasks/configure-pod-container/memory-request-limit-2.yaml
  docs/tasks/configure-pod-container/memory-request-limit-3.yaml
  docs/tasks/configure-pod-container/memory-request-limit.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#7576 Storage Protection was renamed to Storage Object in Use Protection
  docs/admin/admission-controllers.md
  docs/concepts/storage/persistent-volumes.md
  docs/tasks/administer-cluster/pvc-protection.md
Labels: approved, cncf-cla: yes, lgtm, sig/storage, size/S

#7578 Update networking.md
  docs/concepts/cluster-administration/networking.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7564 Moving CSI to Out of Tree section; linking to out of tree plugin FAQ
  docs/concepts/storage/volumes.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7562 Use PSP from policy API group
  docs/admin/authorization/index.md
  docs/concepts/policy/example-psp.yaml
  docs/concepts/policy/pod-security-policy.md
  docs/concepts/policy/privileged-psp.yaml
  docs/concepts/policy/restricted-psp.yaml
  docs/tutorials/clusters/apparmor.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7561 update kubeletconfig docs for v1.10, beta
  docs/tasks/administer-cluster/kubelet-config-file.md
  docs/tasks/administer-cluster/reconfigure-kubelet.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#7553 Please note N/A's meaning
  _plugins/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7503 Increase consistency, and style guide compliance
  docs/concepts/policy/resource-quotas.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7078 Add a section about routing errors
  docs/setup/independent/troubleshooting-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#6410 Remove "design docs" from /docs/reference sidebar
  _data/reference.yml
  docs/admin/ovs-networking.md
  docs/reference/design-docs/overview.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7014 adding how-to for making glossary tooltips
  docs/home/contribute/includes.md
  docs/home/contribute/style-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#6777 Add section in tasks => configmaps with examples for --from-env-file
  docs/tasks/configure-pod-container/configure-pod-configmap.md
  docs/tasks/configure-pod-container/game-env-file.properties
  docs/tasks/configure-pod-container/ui-env-file.properties
Labels: approved, cncf-cla: yes, lgtm, size/M

#6922 Update minikube.md
  docs/getting-started-guides/minikube.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7629 (azure): change default location, add info
  docs/getting-started-guides/ubuntu/installation.md
  docs/getting-started-guides/ubuntu/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7627 Add a note on availability of tcp_syncookies syctl
  docs/concepts/cluster-administration/sysctl-cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7624 Added TOC for HPA document for better reference.
  docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
  docs/tasks/run-application/horizontal-pod-autoscale.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7630 (ubuntu): fix broken etcd snapshot command
  docs/getting-started-guides/ubuntu/backups.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7607 Added Rancher <-> Ubuntu k8s integration documentation
  _data/setup.yml
  docs/getting-started-guides/ubuntu/index.md
  docs/getting-started-guides/ubuntu/installation.md
  docs/getting-started-guides/ubuntu/rancher.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#7575 Update port-forwarding docs
  docs/tasks/access-application-cluster/port-forward-access-application-cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7626 Fixed Issue with k8s.io/docs/getting-started-guides/fedora/fedora_manual_config/
  docs/getting-started-guides/fedora/fedora_manual_config.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7104 refactor setting up cluster using kubeadm
  docs/setup/independent/install-kubeadm.md
  docs/setup/independent/troubleshooting-kubeadm.md
Labels: Needs Tech Review, approved, cncf-cla: yes, lgtm, size/M

#7620 PV protection description
  _data/tasks.yml
  docs/admin/authorization/rbac.md
  docs/concepts/storage/persistent-volumes.md
  docs/tasks/administer-cluster/storage-object-in-use-protection.md
Labels: Needs Tech Review, approved, cncf-cla: yes, lgtm, sig/storage, size/L

#7606 IPv6: Updating doc related to IPv6.
  docs/concepts/services-networking/service.md
  docs/getting-started-guides/scratch.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7634 fix description about client library
  docs/reference/index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7631 Add docs on configuring NodePort IP
  docs/concepts/services-networking/service.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7637 Typo fix some "pod to schedule on"->"pod to be scheduled on"
  docs/concepts/configuration/assign-pod-node.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7635 Document that LocalStorageCapacityIsolation is beta
  docs/reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7608 adding PKS solution description and link
  docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7638 Update CoreDNS docs for beta
  docs/tasks/administer-cluster/coredns.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7645 erp, typo'd myself
  docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7642 Fix typo
  docs/tasks/administer-cluster/reconfigure-kubelet.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7641 Fix typo
  docs/tasks/administer-cluster/reconfigure-kubelet.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7640 Fix typo
  docs/tasks/administer-cluster/reconfigure-kubelet.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7605 Add RDMA device plugin
  docs/concepts/cluster-administration/device-plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7600 fix sysctl miss in podsecuritypolicy descriptions.
  docs/concepts/cluster-administration/sysctl-cluster.md
  docs/concepts/policy/pod-security-policy.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7643 Remove/hide cluster operator advanced user journey
  _data/setup.yml
  docs/user-journeys/users/cluster-operator/_advanced.md
  skip_toc_check.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7660 Adding missing quote to command line example
  docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7665 Remove reference to OVS as a called-out option for on-prem networking model
  docs/concepts/cluster-administration/cluster-administration-overview.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7661 Updates documentation pertaining to VMware
  _data/setup.yml
  _data/user-personas/migrators/vmware-openstack.yaml
  _redirects
  docs/concepts/storage/volumes.md
  docs/getting-started-guides/minikube.md
  docs/getting-started-guides/ubuntu/index.md
  docs/getting-started-guides/ubuntu/installation.md
  docs/getting-started-guides/vsphere.md
  docs/getting-started-guides/windows/index.md
  docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#7662 Update local persistent storage and volume scheduling feature gates move to beta
  docs/reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7670 Fix broken URL
  docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7449 admission-control flag replaced by enable/disable-admission-plugins flags
  docs/admin/admission-controllers.md
  docs/admin/authorization/node.md
  docs/admin/extensible-admission-controllers.md
  docs/admin/high-availability/kube-apiserver.yaml
  docs/concepts/configuration/pod-priority-preemption.md
  docs/concepts/policy/resource-quotas.md
  docs/concepts/storage/persistent-volumes.md
  docs/concepts/workloads/pods/podpreset.md
  docs/getting-started-guides/coreos/cloud-configs/master.yaml
  docs/getting-started-guides/scratch.md
  docs/reference/setup-tools/kubeadm/implementation-details.md
  docs/tasks/administer-cluster/running-cloud-controller.md
  docs/tasks/federation/set-up-placement-policies-federation.md
  docs/tutorials/clusters/apparmor.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7655 Documentation for MountPropagation beta
  docs/concepts/storage/volumes.md
  docs/reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7684 Remove job's scale-related operations
  docs/concepts/workloads/controllers/jobs-run-to-completion.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7648 authentication: document client-go exec plugins
  docs/admin/authentication.md
Labels: approved, cncf-cla: yes, lgtm, sig/auth, size/L

#7683 Removed doc line descibing invocation of swagger UI
  docs/concepts/overview/kubernetes-api.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7615 Adding glossary item for Cloud Providers
  _data/glossary/cloud-provider.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7685 Update local ephemeral storage feature to beta
  docs/concepts/configuration/manage-compute-resources-container.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7687 Fix the reference to the glossary in the include guide
  docs/home/contribute/includes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7653 Update docs for windows container resources
  docs/getting-started-guides/windows/index.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7666 fix a desription error in sysctl file.
  docs/concepts/cluster-administration/sysctl-cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7671 add server-side print docs
  docs/reference/api-concepts.md
  docs/reference/kubectl/overview.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7489 Create task for alpha feature Share Process Namespace
  _data/tasks.yml
  docs/reference/feature-gates.md
  docs/tasks/configure-pod-container/share-process-namespace.md
  docs/tasks/configure-pod-container/share-process-namespace.yaml
  test/examples_test.go
Labels: Needs Tech Review, approved, cncf-cla: yes, lgtm, size/L

#7715 Typo fix "these command"->"these commands"
  docs/tutorials/stateless-application/hello-minikube.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7710 fix typos
  docs/update-user-guide-links.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7664 Add external metrics to HPA docs
  docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
  docs/tasks/run-application/horizontal-pod-autoscale.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7716 Fix outdated links
  docs/reference/security.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7707 Update ingress.md | yaml annotation in example
  docs/concepts/services-networking/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7712 remove description about "scale jobs"
  docs/concepts/workloads/controllers/jobs-run-to-completion.md
  docs/tasks/job/parallel-processing-expansion.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7728 Update weave-network-policy.md
  docs/tasks/administer-cluster/weave-network-policy.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7698 CSI Docs for K8s v1.10
  docs/concepts/storage/volumes.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#7729 Move @bradtopol from SIG Docs reviewer to approver
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7725 Add a warning about increased memory consumption for audit logging
  docs/tasks/debug-application-cluster/audit.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7679 Update Audit Logging documentation for 1.10
  docs/tasks/debug-application-cluster/audit.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7746 Fix stage names in audit logging documentation
  docs/tasks/debug-application-cluster/audit.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7557 Guide for upgrading kubeadm HA clusters.
  _data/tasks.yml
  docs/reference/setup-tools/kubeadm/kubeadm-upgrade.md
  docs/setup/independent/create-cluster-kubeadm.md
  docs/tasks/administer-cluster/kubeadm-upgrade-ha.md
Labels: Tech Review: Open Issues, approved, cncf-cla: yes, lgtm, size/L

#7696 Update KubeletConfig doc to reference the release-1.9 code base
  docs/tasks/administer-cluster/kubelet-config-file.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7680 Fix js error in homepage
  _includes/footer-scripts.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7733 Update admission webhook doc
  docs/admin/extensible-admission-controllers.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#7697 Remove page that only contains placeholder text
  _data/setup.yml
  docs/setup/hosted-solutions/overview.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7756 Added details for scaling node count on AKS
  docs/tasks/administer-cluster/cluster-management.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7754 Fix a typo related to LimitRanger admission controller
  docs/concepts/policy/resource-quotas.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7752 Update device-plugins.md
  docs/concepts/cluster-administration/device-plugins.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7751 Add step to docs/getting-started-guides/ubuntu/upgrades.md to ensure kubeapi-load-balancer is updated before master & workers
  docs/getting-started-guides/ubuntu/upgrades.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7750 Reference ahmetb's recipes repo for more scenarios enabled by NetworkPolicy
  docs/concepts/services-networking/network-policies.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7738 It's better to be "behavior"
  docs/admin/admission-controllers.md
  docs/admin/authentication.md
  docs/admin/high-availability/building.md
  docs/admin/multiple-zones.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7727 fixes common name and organization and base64
  docs/concepts/services-networking/connect-applications-service.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7720 Remove the redundant "`" in pick-right-solution.md
  docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7723 Update Kubespray documents
  docs/getting-started-guides/kubespray.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7719 Use the international standard for punctuation
  docs/concepts/configuration/assign-pod-node.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7718 Remove reference to the deprecated OVS document
  docs/concepts/cluster-administration/networking.md
  docs/concepts/services-networking/ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7677 Naming clarification
  docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7495 Refreshing installation instructions
  docs/getting-started-guides/ubuntu/installation.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#7768 Fixed image value version typo
  docs/concepts/overview/object-management-kubectl/declarative-config.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7784 Update flocker reference to the github repo
  docs/concepts/storage/volumes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7778 an user -> a user
  docs/concepts/storage/persistent-volumes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7767 Events are namespaced
  docs/concepts/overview/working-with-objects/namespaces.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7764 fix 'monitoring' link lose efficacy problem'
  docs/getting-started-guides/gce.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7742 Feature gate update for release 1.10
  docs/reference/feature-gates.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7659 pod-security-policy.md: minor fix
  docs/concepts/policy/pod-security-policy.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7771 Update downward-api-volume-expose-pod-information.md
  docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7783 Add Amadeus Case Study
  case-studies/amadeus.html
  css/style_amadeus.css
  images/CaseStudy_amadeus_banner1.jpg
  images/CaseStudy_amadeus_banner3.jpg
  images/CaseStudy_amadeus_banner4.jpg
  images/CaseStudy_amadeus_banner_mobile.jpg
  images/amadeus.png
  images/amadeus_logo.png
Labels: Needs Docs Review, approved, cncf-cla: yes, lgtm, size/XL

#7787 Fixed Cyrillic с in 'kube-proxy-cm'
  docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7705 install-kubectl: choose one installation method
  docs/tasks/tools/install-kubectl.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7781 Update install-kubeadm.md
  docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#7788 repair failure link
  docs/reference/kubectl/cheatsheet.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/XS

#7777 Update k8s201.md
  docs/user-guide/walkthrough/k8s201.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/S

#7792 Gramatical fix to kompose introduction
  docs/tools/kompose/user-guide.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7794 State in the docs that the value of default Node labels are not reliable.
  docs/concepts/configuration/assign-pod-node.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, sig/scheduling, size/XS

#7755 Kill the reference to --admission-control option
  docs/admin/extensible-admission-controllers.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/XS

#7800 update amadeus.html
  case-studies/amadeus.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#7804 Fix a missing word in endpoint reconciler section
  docs/admin/high-availability/building.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7802 Partners page updates
  _includes/partner-script.js
  images/square-logos/asag.png
  images/square-logos/baidu.png
  images/square-logos/circulo.png
  images/square-logos/componentsoft.png
  images/square-logos/devopsguru.png
  images/square-logos/ein.png
  images/square-logos/google.png
  images/square-logos/guardicore.png
  images/square-logos/hedvig.png
  images/square-logos/hpe.png
  images/square-logos/jetbrains.png
  images/square-logos/kong.png
  images/square-logos/mobilise.png
  images/square-logos/opensense.png
  images/square-logos/spotinst.png
  images/square-logos/superorbital.png
  images/square-logos/woqutech.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#7807 Pvcprotection toc
  _data/setup.yml
  case-studies/amadeus.html
  css/style_amadeus.css
  docs/admin/high-availability/building.md
  docs/concepts/overview/object-management-kubectl/declarative-config.md
  docs/concepts/overview/working-with-objects/namespaces.md
  docs/concepts/policy/pod-security-policy.md
  docs/concepts/storage/persistent-volumes.md
  docs/concepts/storage/volumes.md
  docs/getting-started-guides/gce.md
  docs/getting-started-guides/ubuntu/installation.md
  docs/reference/kubectl/cheatsheet.md
  docs/setup/independent/high-availability.md
  docs/setup/independent/install-kubeadm.md
  docs/tasks/federation/set-up-cluster-federation-kubefed.md
  docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
  docs/tasks/tools/install-kubectl.md
  docs/tools/kompose/user-guide.md
  docs/user-guide/walkthrough/k8s201.md
  images/CaseStudy_amadeus_banner1.jpg
  images/CaseStudy_amadeus_banner3.jpg
  images/CaseStudy_amadeus_banner4.jpg
  images/CaseStudy_amadeus_banner_mobile.jpg
  images/amadeus.png
  images/amadeus_logo.png
Labels: approved, cncf-cla: yes, lgtm, size/XL

#6808 Make using sysctls a task instead of a concept
  _data/concepts.yml
  _data/tasks.yml
  _redirects
  docs/tasks/administer-cluster/sysctl-cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#7745 add a note when mount a configmap to pod
  docs/tasks/configure-pod-container/configure-pod-configmap.md
Labels: Needs Tech Review, approved, cncf-cla: yes, lgtm, size/XS

#7812 adjust a note format
  docs/concepts/overview/working-with-objects/labels.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7748 Update docker-cli-to-kubectl.md
  docs/reference/kubectl/docker-cli-to-kubectl.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, lgtm, size/M

#7818 Release 1.10
  _data/concepts.yml
  _data/tasks.yml
  _includes/partner-script.js
  _redirects
  docs/concepts/overview/working-with-objects/labels.md
  docs/reference/kubectl/docker-cli-to-kubectl.md
  docs/tasks/administer-cluster/sysctl-cluster.md
  docs/tasks/configure-pod-container/configure-pod-configmap.md
  images/square-logos/asag.png
  images/square-logos/baidu.png
  images/square-logos/circulo.png
  images/square-logos/componentsoft.png
  images/square-logos/devopsguru.png
  images/square-logos/ein.png
  images/square-logos/google.png
  images/square-logos/guardicore.png
  images/square-logos/hedvig.png
  images/square-logos/hpe.png
  images/square-logos/jetbrains.png
  images/square-logos/kong.png
  images/square-logos/mobilise.png
  images/square-logos/opensense.png
  images/square-logos/spotinst.png
  images/square-logos/superorbital.png
  images/square-logos/woqutech.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#7762 "Nagions" should be "Nagios“
  docs/getting-started-guides/ubuntu/monitoring.md
Labels: Tech Review: Open Issues, approved, cncf-cla: yes, lgtm, size/XS

#7821 Remove CoreOS guide that use Kubernetes v0.15.0
  _data/setup.yml
  cn/docs/getting-started-guides/coreos/bare_metal_offline.md
  docs/getting-started-guides/coreos/bare_metal_offline.md
  docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#7816 Add Amadeus feature image
  images/case_studies/amadeus_feature.png
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7813 fix flag
  docs/tasks/administer-cluster/configure-upgrade-etcd.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7814 fix flag
  docs/tasks/administer-cluster/configure-upgrade-etcd.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7769 Add the OCI runtime description.
  docs/concepts/overview/components.md
Labels: Needs Tech Review, approved, cncf-cla: yes, lgtm, size/XS

#7774 Update manage-deployment.md
  docs/concepts/cluster-administration/manage-deployment.md
Labels: Needs Tech Review, approved, cncf-cla: yes, lgtm, size/XS

#7699 Update imperative-command.md
  docs/concepts/overview/object-management-kubectl/imperative-command.md
Labels: Needs Tech Review, approved, cncf-cla: yes, lgtm, size/XS

#7675 Update outdated documentation about secret key validation.
  docs/concepts/configuration/secret.md
Labels: Needs Tech Review, approved, cncf-cla: yes, lgtm, size/XS

#7826 Adding Tenxcloud as KCSP and Hedvig typo
  _includes/partner-script.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7668 Update conventions.md
  docs/reference/kubectl/conventions.md
Labels: Needs Docs Review, approved, cncf-cla: yes, lgtm, sig/cli, size/M

#7810 Update service.md
  docs/concepts/services-networking/service.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7854 Mount propagation update to include docker config
  docs/concepts/storage/volumes.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7847 update overridden config for 1.10
  _config.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7759 Update Extended Resource doc wrt cluster-level resources
  docs/concepts/configuration/manage-compute-resources-container.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#7845 add generated docs for tools and components
  docs/reference/generated/cloud-controller-manager.md
  docs/reference/generated/federation-apiserver.md
  docs/reference/generated/federation-controller-manager.md
  docs/reference/generated/kube-apiserver.md
  docs/reference/generated/kube-controller-manager.md
  docs/reference/generated/kube-proxy.md
  docs/reference/generated/kube-scheduler.md
  docs/reference/generated/kubectl/kubectl.md
  docs/reference/generated/kubefed.md
  docs/reference/generated/kubefed_init.md
  docs/reference/generated/kubefed_join.md
  docs/reference/generated/kubefed_options.md
  docs/reference/generated/kubefed_unjoin.md
  docs/reference/generated/kubefed_version.md
  docs/reference/generated/kubelet.md
  update-imported-docs/release.yml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#7866 add generated docs for tools and components (#7845)
  docs/reference/generated/cloud-controller-manager.md
  docs/reference/generated/federation-apiserver.md
  docs/reference/generated/federation-controller-manager.md
  docs/reference/generated/kube-apiserver.md
  docs/reference/generated/kube-controller-manager.md
  docs/reference/generated/kube-proxy.md
  docs/reference/generated/kube-scheduler.md
  docs/reference/generated/kubectl/kubectl.md
  docs/reference/generated/kubefed.md
  docs/reference/generated/kubefed_init.md
  docs/reference/generated/kubefed_join.md
  docs/reference/generated/kubefed_options.md
  docs/reference/generated/kubefed_unjoin.md
  docs/reference/generated/kubefed_version.md
  docs/reference/generated/kubelet.md
  update-imported-docs/release.yml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#7735 Consolidate all upgrade/downgrade admin tasks
  _data/tasks.yml
  _redirects
  docs/tasks/administer-cluster/upgrade-downgrade/kubeadm-upgrade-1-7.md
  docs/tasks/administer-cluster/upgrade-downgrade/kubeadm-upgrade-1-8.md
  docs/tasks/administer-cluster/upgrade-downgrade/kubeadm-upgrade-1-9.md
  docs/tasks/administer-cluster/upgrade-downgrade/kubeadm-upgrade-ha.md
  docs/tasks/administer-cluster/upgrade-downgrade/upgrade-1-6.md
Labels: approved, cncf-cla: yes, lgtm, size/S
