Repository kubernetes/website, pull requests merged in 2019-03, with the labels that each got.

#12789 docs-fr | Website Homepage
  content/fr/_index.html
  content/fr/case-studies/_index.html
  i18n/fr.toml
Labels: approved, cncf-cla: yes, language/fr, lgtm, size/M

#12906 fix typo in start contributing
  content/en/docs/contribute/start.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12854 ko: Translate tutorials/online-training/overview.md in Korean
  content/ko/docs/tutorials/online-training/overview.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/S

#12939 ZH-trans: update encrypt-data.md
  content/zh/docs/tasks/administer-cluster/encrypt-data.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#12940 ZH-trans: add example-task-template.md
  content/zh/docs/tasks/example-task-template.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12903 zh-trans: translate kubeweekly block
  i18n/zh.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#12972 Update CVE-2019-5736 blog post with kops fixes
  content/en/blog/_posts/2019-02-11-runc-CVE-2019-5736.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12850 ko: Translate contribute/_index.md in Korean
  content/ko/docs/contribute/_index.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#12882 Translate architecture concepts in French
  content/fr/docs/concepts/architecture/_index.md
  content/fr/docs/concepts/architecture/master-node-communication.md
  content/fr/docs/concepts/architecture/nodes.md
Labels: approved, cncf-cla: yes, language/fr, lgtm, size/L

#12860 docs-fr | concepts | container runtime class page
  content/fr/docs/concepts/containers/runtime-class.md
Labels: approved, cncf-cla: yes, language/fr, lgtm, size/L

#12981 Seventh Korean l10n work for release-1.13
  content/ko/docs/concepts/architecture/cloud-controller.md
  content/ko/docs/concepts/configuration/_index.md
  content/ko/docs/concepts/configuration/scheduler-perf-tuning.md
  content/ko/docs/concepts/containers/container-lifecycle-hooks.md
  content/ko/docs/concepts/containers/images.md
  content/ko/docs/concepts/overview/components.md
  content/ko/docs/concepts/overview/object-management-kubectl/_index.md
  content/ko/docs/concepts/overview/object-management-kubectl/overview.md
  content/ko/docs/concepts/overview/working-with-objects/kubernetes-objects.md
  content/ko/docs/concepts/workloads/pods/init-containers.md
  content/ko/docs/concepts/workloads/pods/pod-lifecycle.md
  content/ko/docs/concepts/workloads/pods/pod-overview.md
  content/ko/docs/contribute/_index.md
  content/ko/docs/contribute/localization_ko.md
  content/ko/docs/home/_index.md
  content/ko/docs/setup/cri.md
  content/ko/docs/setup/minikube.md
  content/ko/docs/setup/pick-right-solution.md
  content/ko/docs/setup/release/building-from-source.md
  content/ko/docs/tasks/run-application/horizontal-pod-autoscale.md
  content/ko/docs/tasks/tools/install-minikube.md
  content/ko/docs/tutorials/hello-minikube.md
  content/ko/docs/tutorials/online-training/overview.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/XL

#12982 Fix broken links for Taint and Toleration
  content/en/docs/reference/glossary/taint.md
  content/en/docs/reference/glossary/toleration.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/docs, size/XS

#12974 Fix broken link in Ingress documentation
  content/en/docs/concepts/services-networking/ingress.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12978 Added Instana to tools
  content/zh/docs/concepts/workloads/controllers/daemonset.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#12971 Update pick-right-solution.md
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12354 update title for "kubernetes-basics" index page
  content/zh/docs/tutorials/kubernetes-basics/_index.html
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#12951 Translated docs/setup/turnkey/azure.md.
  content/ja/docs/setup/turnkey/azure.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/M

#12986 ko-trans: Update outdated contents in dev-1.13-ko.8 branch partly
  content/ko/docs/concepts/overview/components.md
  content/ko/docs/concepts/overview/kubernetes-api.md
  content/ko/docs/concepts/overview/what-is-kubernetes.md
  content/ko/docs/concepts/overview/working-with-objects/kubernetes-objects.md
  content/ko/docs/concepts/workloads/pods/pod-overview.md
  content/ko/docs/home/_index.md
  content/ko/docs/reference/glossary/index.md
  content/ko/docs/setup/pick-right-solution.md
  content/ko/docs/setup/release/building-from-source.md
  content/ko/docs/tasks/tools/install-minikube.md
  content/ko/docs/tutorials/hello-minikube.md
  content/ko/docs/tutorials/kubernetes-basics/_index.html
  content/ko/docs/tutorials/online-training/overview.md
  content/ko/docs/tutorials/stateless-application/guestbook.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#13000 ko: Update outdated files in dev-1.13-ko.8
  content/ko/docs/concepts/architecture/master-node-communication.md
  content/ko/docs/concepts/containers/images.md
  content/ko/docs/setup/cri.md
  content/ko/docs/setup/multiple-zones.md
  content/ko/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#12779 Code snippets shouldn't include the command prompt
  content/en/docs/concepts/cluster-administration/certificates.md
  content/en/docs/concepts/cluster-administration/logging.md
  content/en/docs/concepts/cluster-administration/manage-deployment.md
  content/en/docs/concepts/configuration/manage-compute-resources-container.md
  content/en/docs/concepts/configuration/secret.md
  content/en/docs/concepts/overview/working-with-objects/field-selectors.md
  content/en/docs/concepts/overview/working-with-objects/kubernetes-objects.md
  content/en/docs/concepts/overview/working-with-objects/labels.md
  content/en/docs/concepts/overview/working-with-objects/namespaces.md
  content/en/docs/concepts/services-networking/connect-applications-service.md
  content/en/docs/concepts/workloads/controllers/deployment.md
  content/en/docs/concepts/workloads/controllers/jobs-run-to-completion.md
  content/en/docs/concepts/workloads/controllers/replicationcontroller.md
  content/en/docs/concepts/workloads/pods/init-containers.md
  content/en/docs/getting-started-guides/ubuntu/networking.md
  content/en/docs/reference/access-authn-authz/authorization.md
  content/en/docs/reference/kubectl/docker-cli-to-kubectl.md
  content/en/docs/reference/kubectl/jsonpath.md
  content/en/docs/reference/kubectl/overview.md
  content/en/docs/setup/minikube.md
  content/en/docs/tasks/administer-cluster/configure-multiple-schedulers.md
  content/en/docs/tasks/administer-cluster/highly-available-master.md
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
  content/en/docs/tasks/administer-cluster/namespaces-walkthrough.md
  content/en/docs/tasks/administer-cluster/namespaces.md
  content/en/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md
  content/en/docs/tasks/administer-cluster/safely-drain-node.md
  content/en/docs/tasks/administer-cluster/sysctl-cluster.md
  content/en/docs/tasks/debug-application-cluster/debug-application.md
  content/en/docs/tasks/debug-application-cluster/logging-elasticsearch-kibana.md
  content/en/docs/tasks/debug-application-cluster/logging-stackdriver.md
  content/en/docs/tasks/extend-kubectl/kubectl-plugins.md
  content/en/docs/tasks/federation/federation-service-discovery.md
  content/en/docs/tasks/inject-data-application/podpreset.md
  content/en/docs/tasks/job/automated-tasks-with-cron-jobs.md
  content/en/docs/tasks/job/coarse-parallel-processing-work-queue.md
  content/en/docs/tasks/run-application/configure-pdb.md
  content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
  content/en/docs/tasks/run-application/rolling-update-replication-controller.md
  content/en/docs/tutorials/clusters/apparmor.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/docs, size/XXL

#13011 Raw block storage blog post
  content/en/blog/_posts/2019-03-07-raw-block-volume-support-to-beta.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L

#12611 Add “app container” to glossary
  content/en/docs/reference/glossary/app-container.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12561 Fix #11761 - Provide clear explanation of Kubernetes deployments
  content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12701 Issue #12533 - Update k8s.io/docs/tutorials/services/source-ip/
  content/en/docs/tutorials/services/source-ip.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12717 Fix broken link in CSI glossary entry
  content/en/docs/reference/glossary/csi.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13023 Switch CNI glossary entry to recommended style
  content/en/docs/reference/glossary/cni.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12718 Clarified step of getting Kubernetes cluster name; fixed quoting in c…
  content/en/docs/tasks/administer-cluster/access-cluster-api.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, language/en, lgtm, size/S

#12768 pod-security-policy.md: update to use PSP from policy/v1beta1
  content/en/docs/concepts/policy/pod-security-policy.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12797 Update debug-pod-replication-controller task file and and fix the kubectl grep
  content/en/docs/tasks/debug-application-cluster/debug-pod-replication-controller.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/docs, size/XS

#12924 Update connect-applications-service.md
  content/en/docs/concepts/services-networking/connect-applications-service.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12783 Add code fencing example in the style guidlines
  content/en/docs/contribute/style/style-guide.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/docs, size/XS

#12886 Update Link to .spec details
  content/en/docs/concepts/workloads/controllers/jobs-run-to-completion.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12831 Change in Storage Value in Example Scenario
  content/en/docs/tasks/administer-cluster/reserve-compute-resources.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12858 Fix Powershell script issue
  content/en/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12862 Updated link to page
  content/en/docs/reference/access-authn-authz/authentication.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/auth, size/XS

#12876 Fix indentation of EncryptionConfiguration sample
  content/en/docs/tasks/administer-cluster/kms-provider.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12945 doc: remove extra used in job document
  content/en/docs/tasks/job/coarse-parallel-processing-work-queue.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12946 Update building-from-source.md
  content/en/docs/setup/release/building-from-source.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12957 Update deprecated link to Container Runtime Interface
  content/en/docs/concepts/overview/components.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12969 Changing k8s -> K8s on homepage
  content/en/_index.html
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12979 Tweaks to write K8s as proper noun
  content/en/docs/tasks/access-application-cluster/create-external-load-balancer.md
  content/en/docs/tasks/federation/set-up-cluster-federation-kubefed.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12984 Fix broken links for CSI docs
  content/en/docs/reference/glossary/csi.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/docs, size/XS

#12977 Added Instana links to the documentation
  content/en/docs/concepts/workloads/controllers/daemonset.md
  content/en/docs/user-journeys/users/cluster-operator/intermediate.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12988 Included link to official Datadog Docs
  content/en/docs/concepts/workloads/controllers/daemonset.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12997 Update feature-gates.md
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12989 Revert "Add s390x platforms for calico"
  content/en/docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, kind/bug, language/en, lgtm, sig/cluster-lifecycle, size/XS

#13003 Add VMware Enterprise PKS and VMware Essential PKS
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13005 fix minor typo (missing "to") in custom resources doc
  content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13008 Add Quobyte's CSI plug-in reference in place of in-tree plug-in
  content/en/docs/concepts/storage/volumes.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13013 Fix markdown
  content/en/docs/setup/minikube.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13018 Update secret.md
  content/en/docs/concepts/configuration/secret.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13029 Fix codeblock in update deployment section
  content/en/docs/concepts/workloads/controllers/deployment.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12893 fix indentaion in hpa deployment
  content/en/examples/admin/dns/dns-horizontal-autoscaler.yaml
Labels: Docs LGTM, Needs Tech Review, approved, cncf-cla: yes, language/en, lgtm, sig/autoscaling, size/S

#12965 ZH-trans: add expose-interactive.html
  content/zh/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#13032 Update /ja/ (2019-03)
  content/ja/_index.html
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS

#13019 Add Linode to list of implemented CCMs
  content/en/docs/concepts/architecture/cloud-controller.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12749 Minikube: Cleanup everything to start new machine
  content/en/docs/tasks/tools/install-minikube.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, language/en, lgtm, size/S

#13009 Clarify the blue/green upgrade example.
  content/en/docs/getting-started-guides/ubuntu/upgrades.md
Labels: Docs LGTM, approved, cncf-cla: yes, language/en, lgtm, size/XS

#12961 update section `pods are preempted unneccessarily`
  content/en/docs/concepts/configuration/pod-priority-preemption.md
Labels: Docs LGTM, Needs Tech Review, approved, cncf-cla: yes, language/en, lgtm, size/XS

#13039 Update secret.md
  content/en/docs/concepts/configuration/secret.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13045 fix short_description field in glossary files
  content/en/docs/reference/glossary/pod-disruption-budget.md
  content/en/docs/reference/glossary/pod-lifecycle.md
  layouts/shortcodes/glossary_definition.html
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12967 ZH-trans: add cloudstack.md
  content/zh/docs/setup/on-premises-vm/cloudstack.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12941 ZH-trans: add container-lifecycle-hooks.md
  content/zh/docs/concepts/containers/container-lifecycle-hooks.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12955 ZH-trans: add expose-external-ip-address.md
  content/zh/docs/tutorials/stateless-application/expose-external-ip-address.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12987 docs-fr | concepts | cluster-administration section
  content/fr/docs/concepts/cluster-administration/_index.md
  content/fr/docs/concepts/cluster-administration/certificates.md
  content/fr/docs/concepts/cluster-administration/cluster-administration-overview.md
Labels: approved, cncf-cla: yes, language/fr, lgtm, size/L

#12847 Update kubectl plugins to stable
  content/en/docs/tasks/extend-kubectl/kubectl-plugins.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13058 docs-fr | Reference | Support de JSONPath
  content/fr/docs/reference/kubectl/jsonpath.md
Labels: approved, cncf-cla: yes, language/fr, lgtm, size/M

#12875 i18n/ko.toml added kubeweekly's contents
  i18n/ko.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#13062 Stop having double static netlify redirection
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/XS

#12889 documentation for CSI topology beta
  content/en/docs/concepts/storage/storage-classes.md
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, language/en, lgtm, size/S

#11555 Cache example_test results with travis
  .travis.yml
Labels: Docs LGTM, Tech Review: Open Issues, approved, cncf-cla: yes, lgtm, sig/docs, size/XS

#12888 Document changes to default RBAC discovery ClusterRole(Binding)s
  content/en/docs/reference/access-authn-authz/rbac.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/docs, size/S

#12689 add feature state labels to admission controllers
  content/en/docs/reference/access-authn-authz/admission-controllers.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#12948 ZH-trans: add dns-horizontal-autoscaling.md
  content/zh/docs/tasks/dns-horizontal-autoscaling.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#13078 Add codenew shortcode to configure-pod-configmap task file and saniti…
  content/en/docs/tasks/configure-pod-container/configure-pod-configmap.md
  content/en/examples/configmap/configmap-multikeys.yaml
  content/en/examples/configmap/configmaps.yaml
  content/en/examples/configmap/game-env-file.properties
  content/en/examples/configmap/game.properties
  content/en/examples/configmap/ui-env-file.properties
  content/en/examples/configmap/ui.properties
  content/en/examples/examples_test.go
  content/en/examples/pods/pod-configmap-env-var-valueFrom.yaml
  content/en/examples/pods/pod-configmap-envFrom.yaml
  content/en/examples/pods/pod-configmap-volume-specific-key.yaml
  content/en/examples/pods/pod-configmap-volume.yaml
  content/en/examples/pods/pod-multiple-configmap-env-variable.yaml
  content/en/examples/pods/pod-single-configmap-env-variable.yaml
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XL

#12863 docs-fr | Reference | kubectl overview
  content/fr/docs/reference/kubectl/overview.md
Labels: approved, cncf-cla: yes, language/fr, lgtm, size/L

#13071 Fix busybox `nslookup` example
  content/en/docs/tutorials/stateful-application/basic-stateful-set.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13108 Add link to Portworx site
  content/en/docs/concepts/storage/volumes.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13112 docs|en: Fix typo in deployment concept
  content/en/docs/concepts/workloads/controllers/deployment.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13068 Update kubeadm-init.md
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/XS

#13120 Fix typos
  content/en/docs/tasks/administer-cluster/out-of-resource.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12771 Update command outputs to k8s 1.13 based
  content/en/docs/tasks/job/automated-tasks-with-cron-jobs.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#13037 Update assign-memory-resource.md
  content/en/docs/tasks/configure-pod-container/assign-memory-resource.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12931 CSI raw block to beta
  content/en/docs/concepts/storage/volumes.md
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#13040 update links to the vSphere docs
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13056 Modify indent from 3 to 2 spaces
  content/en/examples/podpreset/allow-db-merged.yaml
  content/en/examples/podpreset/allow-db.yaml
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13134 Adds a section for OKE cluster upgrades
  content/en/docs/tasks/administer-cluster/cluster-management.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13012 Revise some places
  content/en/docs/reference/access-authn-authz/rbac.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13051 Fix typo in `dns-horizontal-autoscaling.md`
  content/en/docs/tasks/administer-cluster/dns-horizontal-autoscaling.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13136 added K8s training materials
  content/en/docs/tutorials/online-training/overview.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13065 Update configure-service-account task file to reference pod spec file…
  content/en/docs/tasks/configure-pod-container/configure-service-account.md
  content/en/examples/examples_test.go
  content/en/examples/pods/pod-projected-svc-token.yaml
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, language/en, lgtm, size/L

#13137 Fixes naming for OKE service
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12900 Reorganize Federation tasks so we have it group and under one topic
  content/en/docs/concepts/cluster-administration/federation.md
  content/en/docs/contribute/style/content-organization.md
  content/en/docs/contribute/style/style-guide.md
  content/en/docs/tasks/administer-federation/_index.md
  content/en/docs/tasks/federation/_index.md
  content/en/docs/tasks/federation/administer-federation/_index.md
  content/en/docs/tasks/federation/administer-federation/cluster.md
  content/en/docs/tasks/federation/administer-federation/configmap.md
  content/en/docs/tasks/federation/administer-federation/daemonset.md
  content/en/docs/tasks/federation/administer-federation/deployment.md
  content/en/docs/tasks/federation/administer-federation/events.md
  content/en/docs/tasks/federation/administer-federation/hpa.md
  content/en/docs/tasks/federation/administer-federation/ingress.md
  content/en/docs/tasks/federation/administer-federation/job.md
  content/en/docs/tasks/federation/administer-federation/namespaces.md
  content/en/docs/tasks/federation/administer-federation/replicaset.md
  content/en/docs/tasks/federation/administer-federation/secret.md
  content/en/docs/tasks/federation/federation-service-discovery.md
  content/en/docs/tasks/federation/set-up-cluster-federation-kubefed.md
  content/en/docs/tasks/federation/set-up-coredns-provider-federation.md
  content/en/docs/tasks/federation/set-up-placement-policies-federation.md
  content/en/docs/test.md
  content/en/includes/federated-task-tutorial-prereqs.md
  content/en/includes/federation-content-moved.md
  content/en/includes/federation-current-state.md
  content/en/includes/federation-deprecation-warning-note.md
  i18n/en.toml
  layouts/shortcodes/deprecationfilewarning.html
  static/css/callouts.css
Labels: Docs Review: Open Issues, approved, cncf-cla: yes, language/en, lgtm, sig/multicluster, size/L

#13126 Add French translation for i18n tags
  i18n/fr.toml
Labels: approved, cncf-cla: yes, lgtm, size/S

#13075 add NetEase case study
  content/en/case-studies/netease/index.html
  content/en/case-studies/netease/netease_featured_logo.png
  static/images/CaseStudy_netease_banner1.jpg
  static/images/CaseStudy_netease_banner3.jpg
  static/images/CaseStudy_netease_banner4.jpg
  static/images/netease_logo.png
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#13144 Fixed issue with ```shell being displayed
  content/en/docs/reference/kubectl/docker-cli-to-kubectl.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13141 Alphabetized, and made linux academy consistent
  content/en/docs/tutorials/online-training/overview.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12937 kubeadm-troubleshooting: add entry about multi-valued args
  content/en/docs/setup/independent/troubleshooting-kubeadm.md
Labels: approved, cncf-cla: yes, kind/bug, language/en, lgtm, sig/cluster-lifecycle, size/S

#13146 Remove the old setup from scratch documentation
  content/en/docs/setup/pick-right-solution.md
  content/en/docs/setup/scratch.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/XL

#13059 docs-fr | Reference | kubectl
  content/fr/docs/reference/kubectl/kubectl.md
Labels: approved, cncf-cla: yes, language/fr, lgtm, size/L

#13142 docs-fr | Reference | kubectl misc
  content/fr/docs/reference/kubectl/_index.md
  content/fr/docs/reference/kubectl/conventions.md
  content/fr/docs/reference/kubectl/kubectl-cmds.md
Labels: approved, cncf-cla: yes, language/fr, lgtm, size/M

#13150 removes extra /configmap from ui.properties path
  content/en/docs/tasks/configure-pod-container/configure-pod-configmap.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13152 fix certificate command
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/XS

#13154 Update assign-cpu-resource.md
  content/en/docs/tasks/configure-pod-container/assign-cpu-resource.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13155 Fix typos
  content/en/docs/setup/minikube.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13157 Added link to New Relic agent install doc
  content/en/docs/concepts/workloads/controllers/daemonset.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13162 Update to remove coreos specific instructions.
  content/en/docs/setup/custom-cloud/coreos.md
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, kind/cleanup, language/en, lgtm, sig/cluster-lifecycle, size/L

#13145 Fix Travis example tests for release-1.13
  .travis.yml
  content/en/examples/examples_test.go
  content/en/examples/pods/pod-projected-svc-token.yaml
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L

#13153 ja-trans: update cluster-intro.html
  content/ja/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS

#13161 [ja] Translate Hello Minikube in tutorials (#13100)
  content/ja/docs/tutorials/hello-minikube.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/S

#13168 Add @xichengliudui to sig-docs-zh-owners (master)
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#13128 Test examples files in configmap directory
  content/en/examples/configmap/configmaps.yaml
  content/en/examples/examples_test.go
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13182 zh-trans: update content/zh/docs/concepts/_index.md
  content/zh/docs/concepts/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#13181 zh-trans: update content/zh/docs/reference/access-authn-authz/node.md
  content/zh/docs/reference/access-authn-authz/node.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#13133 Remove --ignoreCache flag from local serve
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#13197 ZH-trans: update docker-cli-to-kubectl.md
  content/zh/docs/user-guide/docker-cli-to-kubectl.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#13185 Use correct kubelet config name
  content/en/docs/tasks/administer-cluster/sysctl-cluster.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13186 ja-trans: update supported-doc-versions.md (#13081)
  content/ja/docs/home/supported-doc-versions.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS

#13187 [ja] Update /concepts/overview/what-is-kubernetes.md (#13079)
  content/ja/docs/concepts/overview/what-is-kubernetes.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS

#13119 Update dns-horizontal-autoscaling.md
  content/zh/docs/tasks/dns-horizontal-autoscaling.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#13048 ZH-trans: add 2018-10-03-kubedirector.md
  content/zh/blog/_posts/2018-10-03-kubedirector.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12953 ZH-trans: add guestbook.md
  content/zh/docs/tutorials/stateless-application/guestbook.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XL

#12947 ZH-trans: add set-up-placement-policies-federation.md
  content/zh/docs/tasks/federation/set-up-placement-policies-federation.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#13047 ZH-trans: add service-accounts-admin.md
  content/zh/docs/reference/access-authn-authz/service-accounts-admin.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12943 ZH-trans: add update-api-object-kubectl-patch.md
  content/zh/docs/tasks/run-application/update-api-object-kubectl-patch.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XL

#12944 ZH-trans: add parallel-processing-expansion.md
  content/zh/docs/tasks/job/parallel-processing-expansion.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12778 zh-trans: add 2018-12-05-new-contributor-shanghai.md
  content/zh/blog/_posts/2018-12-05-new-contributor-shanghai.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12836 Fix typo in yml examples
  content/zh/docs/tasks/administer-cluster/dns-custom-nameservers.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#12572 zh-trans: /docs/contribute/style/write-new-topic.md
  content/zh/docs/contribute/style/write-new-topic.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#13205 zh-trans: update content/zh/docs/reference/kubectl/kubectl.md
  content/zh/docs/reference/kubectl/kubectl.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#13202 zh-trans: update content/zh/docs/setup/salt.md
  content/zh/docs/setup/salt.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#13198 zh-trans: add docs/reference/setup-tools/kubeadm/generated/kubeadm_token.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_token.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#13170 ZH-trans: add kubeadm_upgrade_diff.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_diff.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#13180 zh-trans: update docs/reference/access-authn-authz/authorization.md
  content/zh/docs/reference/access-authn-authz/authorization.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#13179 zh-trans: update docs/reference/setup-tools/kubeadm/kubeadm-config.md
  content/zh/docs/reference/setup-tools/kubeadm/kubeadm-config.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#13171 zh-trans: add docs/concepts/storage/dynamic-provisioning.md
  content/zh/docs/concepts/storage/dynamic-provisioning.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#13149 ZH-trans: add 2015-05-00-Kubernetes-On-Openstack.md
  content/zh/blog/_posts/2015-05-00-Kubernetes-On-Openstack.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#13131 ZH-trans: add 2015-03-00-Welcome-To-Kubernetes-Blog.md
  content/zh/blog/_posts/2015-03-00-Welcome-To-Kubernetes-Blog.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#13123 ZH-trans: add 2015-06-00-Slides-Cluster-Management-With.md
  content/zh/blog/_posts/2015-06-00-Slides-Cluster-Management-With.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#13124 ZH-trans: add 2015-03-00-Kubernetes-Gathering-Videos.md
  content/zh/blog/_posts/2015-03-00-Kubernetes-Gathering-Videos.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#13129 ZH-trans: add 2015-03-00-Weekly-Kubernetes-Community-Hangout.md
  content/zh/blog/_posts/2015-03-00-Weekly-Kubernetes-Community-Hangout.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#13130 ZH-trans: add 2015-04-00-Kubernetes-Release-0150.md
  content/zh/blog/_posts/2015-04-00-Kubernetes-Release-0150.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#13132 ZH-trans: add 2015-04-00-Weekly-Kubernetes-Community-Hangout_17.md
  content/zh/blog/_posts/2015-04-00-Weekly-Kubernetes-Community-Hangout_17.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#13147 ZH-trans: add 2015-04-00-Weekly-Kubernetes-Community-Hangout_29.md
  content/zh/blog/_posts/2015-04-00-Weekly-Kubernetes-Community-Hangout_29.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#13148 ZH-trans: add 2015-05-00-Weekly-Kubernetes-Community-Hangout.md
  content/zh/blog/_posts/2015-05-00-Weekly-Kubernetes-Community-Hangout.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#13195 ZH-trans: add flannel_multi_node_cluster.md
  content/zh/docs/getting-started-guides/fedora/flannel_multi_node_cluster.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#13200 zh-trans: add docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
  content/zh/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#13015 Remove command prompts and split command outputs
  content/en/docs/tasks/access-application-cluster/access-cluster.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#13196 Fix typos
  content/en/docs/tasks/debug-application-cluster/logging-stackdriver.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#13163 re-alphabetize list of Local ecosystem tools
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS
