Repository kubernetes/website, pull requests merged in 2019-01, with the labels that each got.

#11907 ko-trans: Translate node-conformance.md
  content/ko/docs/setup/node-conformance.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/M

#11994 ko-trans: content/ko/docs/reference/glossary/controller.md
  content/ko/docs/reference/glossary/controller.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/XS

#12011 fix Typo "##" -> "## "
  content/zh/docs/tutorials/stateful-application/basic-stateful-set.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#12010 fix web style error
  content/zh/docs/tutorials/k8s101.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#12006 ZH-trans: add kubeadm_alpha_phase_selfhosting.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_selfhosting.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#12005 ZH-trans: add kubeadm_alpha_phase_controlplane_apiserver.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_controlplane_apiserver.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11995 zh-trans:/docs/tasks/debug-application-cluster/resource-usage-monitor…
  content/zh/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11990 zh-trans:/docs/tasks/debug-application-cluster/core-metrics-pipeline.md
  content/zh/docs/tasks/debug-application-cluster/core-metrics-pipeline.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11989 zh-trans:/docs/tasks/debug-application-cluster/troubleshooting.md
  content/zh/docs/tasks/debug-application-cluster/troubleshooting.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11969 Create kubeadm_alpha_phase_certs_renew_apiserver-kubelet-client.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_renew_apiserver-kubelet-client.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11962 zh-trans: /docs/tasks/debug-application-cluster/debug-init-containers.md
  content/zh/docs/tasks/debug-application-cluster/debug-init-containers.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11930 zh-trans: docs/reference/glossary/horizontal-pod-autoscaler.md
  content/zh/docs/reference/glossary/horizontal-pod-autoscaler.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11911 zh-trans: add /docs/tasks/configure-pod-container/configure-projected…
  content/zh/docs/tasks/configure-pod-container/configure-projected-volume-storage.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11918 zh-trans: /docs/tasks/configure-pod-container/extended-resource.md
  content/zh/docs/tasks/configure-pod-container/extended-resource.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11910 zh-trans: add translate-compose-kubernetes.md
  content/zh/docs/tasks/configure-pod-container/translate-compose-kubernetes.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XL

#11925 zh-trans: zh/docs/reference/glossary/flexvolume.md
  content/zh/docs/reference/glossary/flexvolume.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#11947 zh_trans: kubeadm_alpha_phase_bootstrap-token_create.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_bootstrap-token_create.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11896 zh-trans: Added the blog post about NCW Shanghai
  content/zh/blog/_posts/2018-12-05-new-contributor-shanghai.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11959 zh-trans:add docs/setup/turnkey/alibaba-cloud.md
  content/zh/docs/setup/turnkey/alibaba-cloud.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#11895 zh_trans: kubeadm_completion.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_completion.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11961 zh-trans: add /zh/ docs/tasks/debug-application-cluster/crictl.md
  content/zh/docs/tasks/debug-application-cluster/crictl.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11968 ZH-trans: add kubeadm_alpha_phase_certs_front-proxy-ca.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_front-proxy-ca.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11970 ZH-trans: add kubeadm_alpha_phase_controlplane_all.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_controlplane_all.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11971 ZH-trans: add kubeadm_alpha_phase_upload-config.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_upload-config.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11417 Update Minikube installation docs
  content/en/docs/tasks/tools/install-minikube.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#11699 docs (access-cluster-api.md): uses mostly kubectl
  content/en/docs/tasks/administer-cluster/access-cluster-api.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#11983 Fix #11982
  content/en/docs/concepts/workloads/controllers/deployment.md
  content/en/examples/controllers/nginx-deployment.yaml
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11821 Clarify preStop hooks in Termination of Pods
  content/en/docs/concepts/workloads/pods/pod.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11629 kubeadm: fix some issues in the upgrade-1.13 doc
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-13.md
Labels: approved, cncf-cla: yes, language/en, lgtm, priority/critical-urgent, sig/cluster-lifecycle, sig/docs, size/L

#11581 [ja] add ja section
  config.toml
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/S

#11613 Update proposal for configure-liveness-readiness-probes.md
  content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-probes.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11929 add cni-ipvlan-vpc-k8s
  content/en/docs/concepts/cluster-administration/networking.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12025 add Jim Angel to approvers list
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#12062 [ja] fix home content
  content/ja/docs/concepts/_index.md
  content/ja/docs/concepts/overview/_index.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/M

#12059 ja-trans: Translate content/ja/docs/tutorials/kubernetes-basics/create-cluster/_index.md in Japanese
  content/ja/docs/tutorials/kubernetes-basics/create-cluster/_index.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS

#12008 Translate tutorials/stateless-application/ in Korean
  content/ko/docs/tutorials/stateless-application/_index.md
  content/ko/docs/tutorials/stateless-application/expose-external-ip-address.md
  content/ko/docs/tutorials/stateless-application/guestbook.md
  content/ko/examples/application/guestbook/frontend-deployment.yaml
  content/ko/examples/application/guestbook/frontend-service.yaml
  content/ko/examples/application/guestbook/redis-master-deployment.yaml
  content/ko/examples/application/guestbook/redis-master-service.yaml
  content/ko/examples/application/guestbook/redis-slave-deployment.yaml
  content/ko/examples/application/guestbook/redis-slave-service.yaml
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/XL

#11720 update PULL_REQUEST_TEMPLATE to include ko-i18n info
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#11988 zh-trans: /docs/tasks/debug-application-cluster/local-debugging.md
  content/zh/docs/tasks/debug-application-cluster/local-debugging.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11996 zh-trans:/docs/tasks/debug-application-cluster/events-stackdriver.md
  content/zh/docs/tasks/debug-application-cluster/events-stackdriver.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11998 zh-trans:/docs/tasks/debug-application-cluster/get-shell-running-cont…
  content/zh/docs/tasks/debug-application-cluster/get-shell-running-container.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12001 zh-trans:/docs/tasks/debug-application-cluster/logging-elasticsearch-…
  content/zh/docs/tasks/debug-application-cluster/logging-elasticsearch-kibana.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12004 ZH-trans: ad kubeadm_alpha_phase_kubelet_config_write-to-disk.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_kubelet_config_write-to-disk.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12093 zh-trans: Remove old-generated kubefed docs (generated on 25-march-2018)
  content/en/docs/reference/setup-tools/kubefed/kubefed-init.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-join.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-options.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-unjoin.md
  content/en/docs/reference/setup-tools/kubefed/kubefed-version.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L

#11917 Remove `--experimental-server-print` flag docs
  content/en/docs/reference/kubectl/overview.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12061 ZH-trans: update _index.md
  content/zh/docs/tasks/inject-data-application/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#12047 ZH-trans: update kubeadm_reset.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#12032 ZH-trasn: add kubeadm_alpha_phase_kubeconfig_controller-manager.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_kubeconfig_controller-manager.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12035 ZH-trans: add kubeadm_alpha_phase_preflight_node.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_preflight_node.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12031 ZH-trans: add kubeadm_alpha_phase_controlplane_scheduler.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_controlplane_scheduler.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12039 ZH-trans: add kubeadm_alpha_phase_bootstrap-token_node_allow-post-csrs.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_bootstrap-token_node_allow-post-csrs.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#12034 ZH-trans: add kubeadm_alpha_phase_kubelet_write-env-file.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_kubelet_write-env-file.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12036 ZH-trans: add kubeadm_upgrade_node_experimental-control-plane.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_experimental-control-plane.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12038 ZH-trans: add kubeadm_alpha_phase_bootstrap-token_node_allow-auto-approve.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_bootstrap-token_node_allow-auto-approve.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#12040 ZH-trans: add kubeadm_alpha_phase_etcd.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_etcd.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#12041 ZH-trans: add kubeadm_alpha_phase_certs_renew_etcd-server.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_renew_etcd-server.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12044 ZH-trans: update advanced.md
  content/zh/docs/contribute/advanced.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#12042 ZH-trans: add kubeadm_alpha_phase_certs_renew_etcd-healthcheck-client.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_renew_etcd-healthcheck-client.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12046 ZH-trans: update kubeadm_version.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_version.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#12063 ZH-trans: update _index.md
  content/zh/docs/tasks/administer-federation/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#12085 zh-trans:/docs/reference/setup-tools/kubefed/kubefed_version.md
  content/zh/docs/reference/setup-tools/kubefed/kubefed_version.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12037 ZH-trans: add kubeadm_alpha_phase_certs_etcd-peer.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_etcd-peer.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12033 ZH-trans: add kubeadm_alpha_phase_kubelet_config_download.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_kubelet_config_download.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11978 patch-reset
  content/en/docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, kind/cleanup, language/en, lgtm, sig/cluster-lifecycle, size/XS

#12049 Typo fix: 'kubadm init'->'kubeadm init'
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/XS

#12048 zh-trans: add docs/tasks/access-application-cluster/_index.md
  content/zh/docs/tasks/access-application-cluster/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#11793 Add base64 encoded data configuration
  content/en/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11845 fix link color in ui-widget-content
  sass/_base.sass
  static/css/case-study-styles.css
  static/css/case-study-styles.css.map
  static/css/styles.css
  static/css/styles.css.map
Labels: approved, cncf-cla: yes, lgtm, size/S

#12106 zh-trans: update cpu-constraint-namespace.md and cpu-default-namespace.md
  content/zh/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace.md
  content/zh/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#12110 ZH-trans: update kubeadm_alpha_phase_upload-config.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_upload-config.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#12022 zh-tran: /docs/reference/setup-tools/kubefed/kubefed_unjoin.md
  content/zh/docs/reference/setup-tools/kubefed/kubefed_unjoin.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12113 fix spelling mistake
  content/en/docs/concepts/configuration/organize-cluster-access-kubeconfig.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12096 Removed a redundant sentence.
  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11618 Add template for tool reference docs
  layouts/partials/templates/tool-reference.html
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12080 Updating pick-right-solution.md with Nirmata
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12114 zh-trans:/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_…
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_apiserver.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12111 zh-trans: add 2018-10-26-tips-for-first-kubecon-presentation-part-2.md
  content/zh/blog/_posts/2018-10-26-tips-for-first-kubecon-presentation-part-2.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12088 zh-trans:/docs/reference/kubectl/docker-cli-to-kubectl.md
  content/zh/docs/reference/kubectl/docker-cli-to-kubectl.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12089 zh-trans: /docs/reference/kubectl/conventions.md
  content/zh/docs/reference/kubectl/conventions.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12094 zh-trans organize-cluster-access-kubeconfig.md
  content/zh/docs/concepts/configuration/organize-cluster-access-kubeconfig.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12086 zh-trans:/docs/reference/setup-tools/kubefed/kubefed.md
  content/zh/docs/reference/setup-tools/kubefed/kubefed.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12029 zh-trans:/docs/reference/setup-tools/kubefed/kubefed_join.md
  content/zh/docs/reference/setup-tools/kubefed/kubefed_join.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12020 zh-trans: /docs/reference/setup-tools/kubefed/kubefed_init.md
  content/zh/docs/reference/setup-tools/kubefed/kubefed_init.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12043 zh-trans: add docs/setup/independent/control-plane-flags.md
  content/zh/docs/setup/independent/control-plane-flags.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11992 zh-trans:/docs/tasks/tools/install-kubectl.md
  content/zh/docs/tasks/tools/install-kubectl.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XL

#11899 zh-trans: add /docs/concepts/cluster-administration/manage-deployment.md
  content/zh/docs/concepts/cluster-administration/manage-deployment.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XL

#12122 Revert "zh-trans: add 2018-10-26-tips-for-first-kubecon-presentation-part-2.md"
  content/zh/blog/_posts/2018-10-26-tips-for-first-kubecon-presentation-part-2.md
Labels: cncf-cla: yes, language/zh, size/L

#12054 Translate concepts/workloads/pods/pod-lifecycle in Korean
  content/ko/docs/concepts/workloads/pods/pod-lifecycle.md
  content/ko/docs/templates/feature-state-beta.txt
  content/ko/docs/templates/index.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#12084 Fix a typos in persistent-volumes.md
  content/en/docs/concepts/storage/persistent-volumes.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12057 format cmd in prereq section
  content/en/docs/tasks/access-kubernetes-api/http-proxy-access-api.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12087 zh-trans:/docs/reference/setup-tools/kubefed/kubefed_options.md
  content/zh/docs/reference/setup-tools/kubefed/kubefed_options.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#11855 Update storage-classes.md
  content/en/docs/concepts/storage/storage-classes.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12119 Update kubeadm-certs.md - remove prow link
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12012 Update dns-debugging-resolution.md
  content/en/docs/tasks/administer-cluster/dns-debugging-resolution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12026 Fix mismatched hostnames in documentation
  content/en/docs/concepts/services-networking/ingress.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12073 Fix CronJob's timezone information
  content/en/docs/concepts/workloads/controllers/cron-jobs.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12055 Correct ResourceQuota PriorityClass-related admission control configuration example
  content/en/docs/concepts/policy/resource-quotas.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#11984 Removed colon and made description consistent
  content/en/docs/tutorials/hello-minikube.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11923 fix a typo
  content/en/docs/concepts/workloads/pods/pod.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11979 chore(doc): Add DigitalOcean to list
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12115 zh-trans: Fix some blog links issue
  content/zh/blog/_posts/2016-04-00-Kubernetes-Network-Policy-APIs.md
  content/zh/blog/_posts/2016-04-00-Kubernetes-On-Aws_15.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#12126 Translate tasks/_index.md in Korean
  content/ko/docs/tasks/_index.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/M

#12123 Move sample YAML files to the correct place
  content/en/docs/tasks/inject-data-application/distribute-credentials-secure.md
  content/zh/docs/tasks/inject-data-application/distribute-credentials-secure.md
  content/zh/examples/pods/inject/secret-envars-pod.yaml
  content/zh/examples/pods/inject/secret-pod.yaml
  content/zh/examples/pods/inject/secret.yaml
Labels: cncf-cla: yes, language/en, language/zh, lgtm, size/M

#12124 Fix broken download URL in k8s.io/docs/tasks/tools/install-minikube
  content/en/docs/tasks/tools/install-minikube.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12137 Update for pull request #12124 (merged)
  content/en/docs/tasks/tools/install-minikube.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12134 adding feature state snip
  content/en/docs/setup/independent/control-plane-flags.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11957 fix a typo
  content/en/docs/setup/independent/setup-ha-etcd-with-kubeadm.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12150 update Set Kubelet parameters via a config file
  content/zh/docs/tasks/administer-cluster/kubelet-config-file.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12145 kubeadm-upgrade-1.13: add workaround for join control-plane
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-13.md
Labels: approved, cncf-cla: yes, kind/cleanup, language/en, lgtm, priority/important-soon, sig/cluster-lifecycle, size/XS

#11836 Add Containership to pick-right-solution.md
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12107 Correction on command
  content/en/docs/reference/setup-tools/kubeadm/kubeadm-join.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/XS

#12154 Update daemonset.md
  content/en/docs/concepts/workloads/controllers/daemonset.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12147 Fix issue with k8s.io/docs/concepts/workloads/controllers/replicaset/
  content/en/docs/concepts/workloads/controllers/replicaset.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12023 Translate beta state description
  content/ja/docs/templates/feature-state-beta.txt
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/S

#12070 [ja] translate setup
  content/ja/docs/setup/_index.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/M

#12155 Update status of CRD-related feature gates
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12169 zh-update: kubeadm-overview
  content/zh/docs/reference/setup-tools/kubeadm/kubeadm.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#12067 Translate setup/_index.md in Korean
  content/ko/docs/setup/_index.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/M

#11758 ko-trans: concepts/overview/working-with-objects/names
  content/ko/docs/concepts/overview/working-with-objects/names.md
  content/ko/docs/reference/glossary/name.md
  content/ko/docs/reference/glossary/uid.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/M

#11773 ko-trans: concepts/overview/working-with-objects/namespaces.md
  content/ko/docs/concepts/overview/working-with-objects/namespaces.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#12065 [ja] translate what-is-kubernetes
  content/ja/docs/concepts/overview/what-is-kubernetes.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/L

#12071 [ja] tutorials/index
  content/ja/docs/tutorials/_index.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/M

#12192 Fixed formatting for markdown file
  content/zh/docs/tasks/inject-data-application/define-environment-variable-container.md
  content/zh/docs/tasks/inject-data-application/distribute-credentials-secure.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12191 Fixed broken link
  content/en/docs/concepts/services-networking/ingress.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12189 Patch 1
  content/en/docs/setup/independent/high-availability.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12183 Fix some typos
  content/en/docs/setup/multiple-zones.md
  content/en/docs/tasks/job/coarse-parallel-processing-work-queue.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12159 Update assign-pod-node.md
  content/en/docs/concepts/configuration/assign-pod-node.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12184 zh-trans:/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_…
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_etcd_local.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12130 zh-trans: kubeadm/generated/kubeadm_alpha_phase_kubelet_config_upload.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_kubelet_config_upload.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12131 zh-trans: kubeadm/generated/kubeadm_alpha_phase_kubeconfig_admin.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_kubeconfig_admin.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12141 zh-trans: /docs/contribute/generate-ref-docs/kubernetes-api.md
  content/zh/docs/contribute/generate-ref-docs/kubectl.md
  content/zh/docs/contribute/generate-ref-docs/kubernetes-api.md
  content/zh/docs/contribute/generate-ref-docs/kubernetes-components.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XL

#12151 zh-trans:/docs/concepts/overview/object-management-kubectl/imperative…
  content/zh/docs/concepts/overview/object-management-kubectl/imperative-config.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12009 ZH-trans: added a blog post Chinese translation: 2018-05-01-developing-on-kubernetes.md
  content/zh/blog/_posts/2018-05-01-developing-on-kubernetes.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XL

#12178 Fix broken links in reference/setup-tools/kubefed/kubefed.md
  content/en/docs/reference/setup-tools/kubefed/kubefed.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12198 Fixed broken redirect
  static/_redirects
Labels: approved, cncf-cla: yes, lgtm, size/XS

#12174 Translate setup/cri.md in Korean
  content/ko/docs/setup/cri.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#12176 Translate tasks/tools/install-minikube in Korean
  content/ko/docs/tasks/tools/_index.md
  content/ko/docs/tasks/tools/install-minikube.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/M

#12143 Fix issue with k8s.io/docs/reference/kubectl/cheatsheet/
  content/en/docs/reference/kubectl/cheatsheet.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12193 Improvements for markdown formatting
  content/en/docs/tasks/access-application-cluster/access-cluster.md
  content/en/docs/tasks/inject-data-application/define-command-argument-container.md
  content/en/docs/tasks/inject-data-application/define-environment-variable-container.md
  content/en/docs/tasks/inject-data-application/distribute-credentials-secure.md
  content/en/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
  content/en/docs/tasks/inject-data-application/environment-variable-expose-pod-information.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L

#12200 Access Cluster: failed to grep on MacOS
  content/en/docs/tasks/access-application-cluster/access-cluster.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12135 Create apiserver-dry-run-and-kubectl-diff
  content/en/blog/_posts/apiserver-dry-run-and-kubectl-diff.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#11552 Upgrade Hugo to 0.52
  .travis.yml
  Makefile
  config.toml
  netlify.toml
  scripts/hugo-version-check.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#12230 Edit button on translated pages working as well now
  layouts/partials/docs/content-page.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#12209 ZH-trans: add kubeadm_alpha_phase_kubelet_config_enable-dynamic.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_kubelet_config_enable-dynamic.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12210 ZH-trans: add kubeadm_alpha_phase_certs_renew_apiserver.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_renew_apiserver.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12103 line 77 '，' -> ','
  content/en/docs/concepts/architecture/nodes.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12212 ZH-trans: add kubeadm_alpha_phase_certs_front-proxy-client.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_front-proxy-client.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#10788 Update dns-pod-service.md
  content/en/docs/concepts/services-networking/dns-pod-service.md
Labels: approved, cncf-cla: yes, lgtm, sig/network, size/XS

#12225 fix docs style
  content/zh/docs/tasks/administer-cluster/change-default-storage-class.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#12237 Fix the version state of BlockVolume
  content/en/docs/concepts/storage/persistent-volumes.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12232 Adding CSI blog post
  content/en/blog/_posts/2019-01-14-apiserver-dry-run-and-kubectl-diff.md
  content/en/blog/_posts/2019-01-15-container-storage-interface-ga.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L
