Repository kubernetes/website, pull requests merged in 2019-02, with the labels that each got.

#12456 ko: Update outdated files in dev-1.13-ko.6
  content/ko/case-studies/ibm/ibm_featured_logo.png
  content/ko/docs/concepts/overview/kubernetes-api.md
  content/ko/docs/concepts/workloads/pods/podpreset.md
  content/ko/docs/home/_index.md
  content/ko/docs/setup/cri.md
  content/ko/docs/setup/minikube.md
  content/ko/docs/setup/pick-right-solution.md
  content/ko/docs/tasks/tools/install-minikube.md
  content/ko/docs/tutorials/hello-minikube.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/M

#12459 Translate concepts/containers/runtime-class.md in Korean
  content/ko/docs/concepts/containers/runtime-class.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#12417 Update missing section in federation blog
  content/en/blog/_posts/2018-12-11-Kubernetes-Federation-Evolution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12460 Add Preemption to Glossary page
  content/en/docs/concepts/configuration/pod-priority-preemption.md
  content/en/docs/reference/glossary/Preemption.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12435 Fix #12434 - Empty continuation line warning while building docker image
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#12470 Add Extension to Glossary page
  content/en/docs/reference/glossary/extensions.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12464 Updated 18.09 as available
  content/en/docs/setup/cri.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/XS

#12504 Minor line-break change
  content/en/docs/tasks/configure-pod-container/configure-projected-volume-storage.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#11919 Add the code of conduct
  README.md
  code-of-conduct.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#12495 Typo fix in running-cloud-controller.md
  content/en/docs/tasks/administer-cluster/running-cloud-controller.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12508 Clarify step 6 for generating the API keys with cfssl regaring json filenames
  content/en/docs/concepts/cluster-administration/certificates.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12079 Update to Hugo 0.53 and remove all .Site references
  Makefile
  layouts/blog/baseof.html
  layouts/blog/list.html
  layouts/blog/post.html
  layouts/case-studies/list.html
  layouts/docs/docsportal_home.html
  layouts/docs/glossary.html
  layouts/index.headers
  layouts/index.html
  layouts/index.rss.xml
  layouts/partials/blog/archive.html
  layouts/partials/deprecation-warning.html
  layouts/partials/docs/browse.html
  layouts/partials/docs/glossary-terms.html
  layouts/partials/docs/side-menu.html
  layouts/partials/docs/top-menu.html
  layouts/partials/footer.html
  layouts/partials/git-info.html
  layouts/partials/head.html
  layouts/partials/header.html
  layouts/partials/templates/feature-state.html
  layouts/partials/tree.html
  layouts/shortcodes/blocks/__common.html
  layouts/shortcodes/blocks/case-studies.html
  layouts/shortcodes/blocks/kubernetes-features.html
  layouts/shortcodes/code.html
  layouts/shortcodes/codenew.html
  layouts/shortcodes/deprecationwarning.html
  layouts/shortcodes/glossary_definition.html
  layouts/shortcodes/glossary_tooltip.html
  layouts/shortcodes/include.html
  layouts/shortcodes/latest-version.html
  layouts/shortcodes/reference_docs.html
  layouts/shortcodes/release-branch.html
  layouts/shortcodes/tab.html
  layouts/shortcodes/tabs.html
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/L

#12505 Adjust button text size
  sass/_base.sass
  static/css/case-study-styles.css
  static/css/case-study-styles.css.map
  static/css/styles.css
  static/css/styles.css.map
Labels: approved, cncf-cla: yes, lgtm, size/XS

#12074 [ja]translate tutorials/kubernetes-basics
  content/ja/docs/tutorials/kubernetes-basics/_index.html
  content/ja/docs/tutorials/kubernetes-basics/create-cluster/_index.md
  content/ja/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
  content/ja/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
  content/ja/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
  content/ja/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
  content/ja/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
  content/ja/docs/tutorials/kubernetes-basics/explore/explore-intro.html
  content/ja/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
  content/ja/docs/tutorials/kubernetes-basics/expose/expose-intro.html
  content/ja/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
  content/ja/docs/tutorials/kubernetes-basics/scale/scale-intro.html
  content/ja/docs/tutorials/kubernetes-basics/update/update-interactive.html
  content/ja/docs/tutorials/kubernetes-basics/update/update-intro.html
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/L

#12516 Fixes #12515 - Update latest hyperlink for Juju controllers ha
  content/en/docs/getting-started-guides/ubuntu/scaling.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12491 Blog post for Poseidon-Firmament Scheduler
  content/en/blog/_posts/2019-02-06-poseidon-firmament-scheduler-announcement.md
  static/images/blog/2019-02-03-poseidon-firmament-scheduler/example-of-a-flow-network.png
  static/images/blog/2019-02-03-poseidon-firmament-scheduler/firmament-kubernetes-integration-overview.png
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#12522 Simplify JavaScript used for embedded landscapes
  content/en/partners/_index.html
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12409 Trying to update ReplicaSet Docs as per issue 12081
  content/en/docs/concepts/workloads/controllers/replicaset.md
  content/en/examples/controllers/frontend.yaml
  content/en/examples/examples_test.go
  content/en/examples/pods/pod-rs.yaml
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L

#12518 Fix 12497 - Update links for additional resources in apparmor doc
  content/en/docs/tutorials/clusters/apparmor.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12480 Link to Baidu's CCM implementation
  content/en/docs/concepts/architecture/cloud-controller.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12532 Add README badge for build status and latest release
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#12535 Fix alignment in command output example in container-lifecycle-hooks
  content/en/docs/concepts/containers/container-lifecycle-hooks.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#11648 ja-trans: tutorials/hello-minikube.md
  content/ja/docs/tutorials/hello-minikube.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/L

#12539 fix cloudprovider link error
  content/en/docs/tasks/administer-cluster/developing-cloud-controller-manager.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12544 [Doc/HPA] Correcting default HPA sync period
  content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12377 windows: Add windows prefix for windows services
  content/en/docs/getting-started-guides/windows/_index.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/windows, size/XS

#12462 kubeadm: Document CRI auto detection functionality
  content/en/docs/setup/independent/create-cluster-kubeadm.md
  content/en/docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/S

#12512 Adding container state details to documentation
  content/en/docs/concepts/workloads/pods/pod-lifecycle.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#12555 Typo resolved
  layouts/shortcodes/include.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#12568 docs: fix typo
  content/en/docs/setup/independent/setup-ha-etcd-with-kubeadm.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/XS

#12591 Updated Recommended docker version
  content/en/docs/setup/cri.md
Labels: approved, cncf-cla: yes, kind/bug, language/en, lgtm, priority/critical-urgent, sig/cluster-lifecycle, size/S

#12592 First pass on a blog post about CVE-2019-5736.
  content/en/blog/_posts/2019-02-11-runc-CVE-2019-5736.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#12514 Minor doc change for GAing Pod DNS Config
  content/en/docs/concepts/services-networking/dns-pod-service.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12580 Update krib.md
  content/en/docs/setup/on-premises-metal/krib.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12590 pod-security-policy.md: fix a broken link
  content/en/docs/concepts/policy/pod-security-policy.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12576 Minor space issue
  content/en/docs/tasks/configure-pod-container/assign-memory-resource.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12527 fix typo in install-kubeadm.md
  content/en/docs/setup/independent/install-kubeadm.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/XS

#12404 Adding proposed blog post for building-a-kubernetes-edge-control-plane
  content/en/blog/_posts/2019-02-11-building-a-kubernetes-edge-control-plane-for-envoy-v2.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L

#12553 Fix a misleading word in containers/images.md
  content/en/docs/concepts/containers/images.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12604 Add ICP to Pick Right Solutions table
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12605 Some corrections to the runc CVE blog post
  content/en/blog/_posts/2019-02-11-runc-CVE-2019-5736.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12606 Updating ICP page with new AWS quick start and latest links
  content/en/docs/setup/turnkey/icp.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#12613 Fix capitalization for CronJob entry in glossary
  content/en/docs/reference/glossary/cronjob.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12359 Add option to install kubectl on Windows via scoop
  content/en/docs/tasks/tools/install-kubectl.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12486 Device Plugin to Glossary page
  content/en/docs/reference/glossary/device-plugin.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12471 Update authorization.md
  content/en/docs/reference/access-authn-authz/authorization.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#10574 Graduate ExpandInUsePersistentVolumes feature to beta
  content/en/docs/reference/command-line-tools-reference/feature-gates.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12598 Updating link
  content/en/blog/_posts/2019-02-12-building-a-kubernetes-edge-control-plane-for-envoy-v2.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12589 Small cleanup of L10n guidelines
  content/en/docs/contribute/localization.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/docs, size/S

#11698 Fix ingress.md
  content/en/docs/concepts/services-networking/ingress.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12615 Fix #12574: update link to SSH tunneling
  content/zh/docs/concepts/architecture/master-node-communication.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#12348 Add Ambassador in list of ingress controller solutions
  content/en/docs/concepts/services-networking/ingress.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12358 Optimize Linux shell installation-command of minikube
  content/en/docs/tasks/tools/install-minikube.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12360 change docker cgroupdriver to its default cgroupfs
  content/en/docs/setup/cri.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12422 Update deployment.md
  content/en/docs/concepts/workloads/controllers/deployment.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12446 Correction in docs/concepts/services-networking/network-policies/
  content/en/docs/concepts/services-networking/network-policies.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12493 create-cluster-kubeadm: update flannel to 0.11.0
  content/en/docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, kind/cleanup, language/en, lgtm, sig/cluster-lifecycle, size/XS

#12536 Add oidc-required-claim
  content/en/docs/reference/access-authn-authz/authentication.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12545 Change typo in `kubectl` output from ClusterIP to LoadBalancer
  content/en/docs/tasks/access-application-cluster/connecting-frontend-backend.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12564 Improve stateful set dns docs
  content/en/docs/concepts/workloads/controllers/statefulset.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12569 Add two training courses from Coursera
  content/en/docs/tutorials/online-training/overview.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12581 Adds link to official docs for LDAP support
  content/en/docs/getting-started-guides/ubuntu/_index.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12594 Rename 2018-11-07-grpc-load-balancing-with-linkerd.md.md file
  content/en/blog/_posts/2018-11-07-grpc-load-balancing-with-linkerd.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12593 Update links of apparmor doc
  content/en/docs/tutorials/clusters/apparmor.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12595 Update kubernetes-objects.md - fix link
  content/en/docs/concepts/overview/working-with-objects/kubernetes-objects.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12599 typo fix in debug-service.md for log level
  content/en/docs/tasks/debug-application-cluster/debug-service.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12600 Add cheat sheet example for listing object labels
  content/en/docs/reference/kubectl/cheatsheet.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12614 Fix broken link in Pod overview page
  content/en/docs/concepts/workloads/pods/pod-overview.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12616 Add s390x platforms for calico
  content/en/docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/XS

#12621 Remove extra occurance of container in the container lifecycle hook definition
  content/en/docs/reference/glossary/container-lifecycle-hooks.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12523 Fix #9805 - Correct tags to avoid HTML encoding issue
  content/en/docs/concepts/overview/object-management-kubectl/imperative-command.md
  content/en/docs/concepts/workloads/pods/init-containers.md
  content/en/docs/tasks/administer-cluster/dns-horizontal-autoscaling.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12557 Update fluentd 0.12 to 1.0 in the example
  content/en/docs/tasks/debug-application-cluster/audit.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/apps, size/S

#12543 Document owner ref restrictions explicitly
  content/en/docs/concepts/workloads/controllers/garbage-collection.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12629 Correct Debian version in runc post, link to other CoreOS channels
  content/en/blog/_posts/2019-02-11-runc-CVE-2019-5736.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12548 Init French translation
  OWNERS_ALIASES
  README-fr.md
  config.toml
  content/fr/OWNERS
  content/fr/_common-resources/index.md
  content/fr/docs/_index.md
  content/fr/docs/tutorials/hello-minikube.md
  content/fr/examples/application/deployment.yaml
  content/fr/examples/application/guestbook/frontend-deployment.yaml
  content/fr/examples/application/guestbook/frontend-service.yaml
  content/fr/examples/application/guestbook/redis-master-deployment.yaml
  content/fr/examples/application/guestbook/redis-master-service.yaml
  content/fr/examples/application/guestbook/redis-slave-deployment.yaml
  content/fr/examples/application/guestbook/redis-slave-service.yaml
  content/fr/examples/application/hpa/php-apache.yaml
  content/fr/examples/minikube/Dockerfile
  content/fr/examples/minikube/server.js
  content/fr/examples/pods/config/redis-config
  content/fr/examples/pods/config/redis-pod.yaml
  i18n/fr.toml
Labels: approved, cncf-cla: yes, language/fr, lgtm, size/XL

#12628 Fix note as others
  content/en/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12635 update glossary id and rename filename
  content/en/docs/reference/glossary/preemption.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12626 Fix ko translation inconsistency for command-line-tool term
  content/ko/docs/concepts/_index.md
  content/ko/docs/concepts/overview/kubernetes-api.md
  content/ko/docs/concepts/overview/what-is-kubernetes.md
  content/ko/docs/tasks/_index.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/S

#12643 Translate the setup section to French
  content/fr/docs/setup/_index.md
Labels: approved, cncf-cla: yes, language/fr, lgtm, size/M

#12418 Substitute en.toml for pedefined english shortcodes for i18n translation
  i18n/en.toml
  i18n/ko.toml
  layouts/shortcodes/caution.html
  layouts/shortcodes/deprecationwarning.html
  layouts/shortcodes/note.html
  layouts/shortcodes/version-check.html
  layouts/shortcodes/warning.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#12620 zh-trans: update content/zh/docs/setup/certificates.md
  content/zh/docs/setup/certificates.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#12619 ZH-trans: add kubeadm_alpha_phase_certs_apiserver-kubelet-client.md
  content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_apiserver-kubelet-client.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12649 Removed junk character from the output
  content/en/docs/concepts/policy/pod-security-policy.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12627 network-policy-provider: updating cilium documentation for v1.4.0
  content/en/docs/setup/independent/create-cluster-kubeadm.md
  content/en/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#12648 Update download icon and add RSS label
  layouts/blog/baseof.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#12632 Update AKS mitigation link
  content/en/blog/_posts/2019-02-11-runc-CVE-2019-5736.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12602 Signpost CronJob docs from Job
  content/en/docs/concepts/workloads/controllers/jobs-run-to-completion.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12488 Fix some 404 links in Chinese docs
  content/zh/docs/user-guide/docker-cli-to-kubectl.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#12235 Add dynamic percentage of node scoring to user docs
  content/en/docs/concepts/configuration/scheduler-perf-tuning.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/scheduling, size/M

#12647 Sort list of training courses
  content/en/docs/tutorials/online-training/overview.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12642 Translate the feature state to French
  content/fr/docs/templates/feature-state-alpha.txt
  content/fr/docs/templates/feature-state-beta.txt
  content/fr/docs/templates/feature-state-deprecated.txt
  content/fr/docs/templates/feature-state-stable.txt
  content/fr/docs/templates/index.md
Labels: approved, cncf-cla: yes, language/fr, lgtm, size/M

#12663 Fix sentence about specifying a rollback version
  content/en/docs/concepts/workloads/controllers/deployment.md
  content/zh/docs/concepts/workloads/controllers/deployment.md
Labels: approved, cncf-cla: yes, language/en, language/zh, lgtm, size/XS

#12650 Update replicaset.md for Issue #12205 with k8s.io/docs/concepts/workloads/controllers/replicaset/
  content/en/docs/concepts/workloads/controllers/replicaset.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12597 Added Korean localization guide
  content/ko/docs/contribute/_index.md
  content/ko/docs/contribute/localization_ko.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#12672 Use # not // for comments in kubectl examples
  content/en/docs/reference/kubectl/overview.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#12356 zh-trans: node-conformance.md
  content/zh/docs/setup/node-conformance.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12353 zh-trans: translate docs/getting-started-guides/ubuntu/operational-co…
  content/zh/docs/getting-started-guides/ubuntu/operational-considerations.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12363 zh-trans: krib.md
  content/zh/docs/setup/on-premises-metal/krib.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#12411 zh-trans: /docs/tasks/administer-federation/events.md
  content/zh/docs/tasks/administer-federation/events.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#12445 delete special symbol for code style
  content/zh/docs/tutorials/stateful-application/basic-stateful-set.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#12412 zh-trans: /docs/setup/turnkey/azure.md
  content/zh/docs/setup/turnkey/azure.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#12549 Translate containers/images.md in Korean
  content/ko/docs/concepts/containers/images.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#12676 Fix a invalid jump link in hpa documentation
  content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12432 zh-trans:/docs/tasks/administer-federation/hpa.md & /docs/tasks/administer-cluster/extended-resource-node.md
  content/zh/docs/tasks/administer-cluster/extended-resource-node.md
  content/zh/docs/tasks/administer-federation/hpa.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XL

#12517 Alias for kubectl that works with completion
  content/en/docs/reference/kubectl/cheatsheet.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cli, size/XS

#11707 Update Container Runtime explanation
  content/en/docs/concepts/overview/components.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/node, size/XS

#11985 Note MicroK8s
  content/en/docs/setup/minikube.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/XS

#11619 Disruptions: make clearer not all voluntary disruptions are constrained by PDBs
  content/en/docs/concepts/workloads/pods/disruptions.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12255 Update http-liveness.yaml
  content/en/examples/pods/probe/http-liveness.yaml
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12498 Update container-lifecycle-hooks document for preStop hook
  content/en/docs/concepts/containers/container-lifecycle-hooks.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12542 Add service path to CRD webhook conversion example
  content/en/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12257 Update hello-minikube.md
  content/en/docs/tutorials/hello-minikube.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12563 Better example of a preStop hook for nginx
  content/en/examples/pods/lifecycle-events.yaml
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12577 Update building-from-source.md
  content/en/docs/setup/release/building-from-source.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12579 Add some details about certs
  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/cluster-lifecycle, size/XS

#12633 add KubeSail to pick-right-solution.md
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12667 Illustrate negative-exists selector in cheat sheet
  content/en/docs/reference/kubectl/cheatsheet.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12152 deprecate DenyExecOnPrivileged/DenyEscalatingExec
  content/en/blog/_posts/2016-08-00-Security-Best-Practices-Kubernetes-Deployment.md
  content/en/docs/reference/access-authn-authz/admission-controllers.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12361 add rkt to glossary
  content/en/docs/reference/glossary/rkt.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12375 remove cloud controller manager docs on using Initializers for PV labeling
  content/en/docs/tasks/administer-cluster/running-cloud-controller.md
  content/en/examples/admin/cloud/pvl-initializer-config.yaml
  content/en/examples/examples_test.go
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12607 Add sysctl to glossary
  content/en/docs/reference/glossary/sysctl.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12622 Add "workload" to glossary
  content/en/docs/reference/glossary/workload.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12638 setup/cri: add a section about cgroup drivers
  content/en/docs/setup/cri.md
Labels: approved, cncf-cla: yes, language/en, lgtm, priority/important-soon, sig/cluster-lifecycle, size/S

#12666 Fix #12575: Add arm64, ppc64le and s390x platforms for calico
  content/zh/docs/setup/independent/create-cluster-kubeadm.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#12182 Update network doc for ip-per-pod reqs
  content/en/docs/concepts/cluster-administration/networking.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#11967 Updated ReadMe
  content/en/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#12670 Reword /docs/concepts/configuration/secret/
  content/en/docs/concepts/configuration/secret.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#12603 Use consistent case for Job
  content/en/docs/concepts/workloads/controllers/jobs-run-to-completion.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L

#12305 Document proxy flows
  content/en/docs/tasks/access-kubernetes-api/configure-aggregation-layer.md
  static/images/docs/aggregation-api-auth-flow.png
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L

#11254 Improve RBAC documentation
  content/en/docs/reference/access-authn-authz/rbac.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/auth, size/L

#12646 Add Pod Disruption Budget to Glossary
  content/en/docs/reference/glossary/pod-disruption-budget.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#11512 Update cron-jobs.md
  content/en/docs/concepts/workloads/controllers/cron-jobs.md
  content/en/docs/concepts/workloads/controllers/jobs-run-to-completion.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12465 Updates to Ingress
  content/en/docs/concepts/services-networking/ingress-controllers.md
  content/en/docs/concepts/services-networking/ingress.md
  content/en/docs/tasks/access-application-cluster/ingress-minikube.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/L

#12645 Add Pod Lifecycle to glossary
  content/en/docs/reference/glossary/pod-lifecycle.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12477 Apply grammar fix
  content/en/docs/concepts/services-networking/connect-applications-service.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12530 Add AMD GPU node labeller to scheduling-gpus.md
  content/en/docs/tasks/manage-gpus/scheduling-gpus.md
Labels: approved, cncf-cla: yes, language/en, lgtm, sig/node, sig/scheduling, size/M

#12344 update _index.md for docs and fix translation
  content/zh/docs/_index.md
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#12654 docs-fr | setup | custom-cloud coreos
  content/fr/docs/setup/custom-cloud/_index.md
  content/fr/docs/setup/custom-cloud/coreos.md
Labels: approved, cncf-cla: yes, language/fr, lgtm, size/L

#12534 Translate container-lifecycle-hooks.md in Korean
  content/ko/docs/concepts/containers/container-lifecycle-hooks.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#12565 Translate tasks/run-application/horizontal-pod-autoscale in Korean
  content/ko/docs/tasks/run-application/horizontal-pod-autoscale.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#12686 Improve namespaces walkthroughs
  content/en/docs/tasks/administer-cluster/namespaces-walkthrough.md
  content/en/docs/tasks/administer-cluster/namespaces.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/M

#12679 fix minishift wording, remove broken link
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12693 Add Supergiant to Turnkey Cloud Solutions list
  content/en/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12702 Add Voyager to list of ingress controllers
  content/en/docs/concepts/services-networking/ingress.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12705 Sixth Korean l10n work for release-1.13
  content/ko/case-studies/ibm/ibm_featured_logo.png
  content/ko/docs/concepts/_index.md
  content/ko/docs/concepts/architecture/cloud-controller.md
  content/ko/docs/concepts/containers/container-lifecycle-hooks.md
  content/ko/docs/concepts/containers/images.md
  content/ko/docs/concepts/containers/runtime-class.md
  content/ko/docs/concepts/overview/kubernetes-api.md
  content/ko/docs/concepts/overview/what-is-kubernetes.md
  content/ko/docs/concepts/workloads/pods/podpreset.md
  content/ko/docs/contribute/_index.md
  content/ko/docs/contribute/localization_ko.md
  content/ko/docs/home/_index.md
  content/ko/docs/setup/certificates.md
  content/ko/docs/setup/cri.md
  content/ko/docs/setup/minikube.md
  content/ko/docs/setup/pick-right-solution.md
  content/ko/docs/tasks/_index.md
  content/ko/docs/tasks/run-application/horizontal-pod-autoscale.md
  content/ko/docs/tasks/tools/install-minikube.md
  content/ko/docs/tutorials/hello-minikube.md
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/XXL

#12658 docs-fr | setup | pick-right-solution
  content/fr/docs/setup/pick-right-solution.md
Labels: approved, cncf-cla: yes, language/fr, lgtm, size/L

#12712 Deployment documentation incorrectly describes how ReplicaSets are named
  content/en/docs/concepts/workloads/controllers/deployment.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/S

#12425 translate tutorials/kubernetes-basics/update/update-intro/ in Italian
  OWNERS_ALIASES
  config.toml
  content/it/OWNERS
  content/it/_common-resources/images/blocks.png
  content/it/_common-resources/images/flower.png
  content/it/_common-resources/images/kub_video_banner_homepage.jpg
  content/it/_common-resources/images/scalable.png
  content/it/_common-resources/images/suitcase.png
  content/it/_common-resources/index.md
  content/it/_index.html
  content/it/blog/_index.md
  content/it/case-studies/_index.md
  content/it/case-studies/comcast/comcast_logo.png
  content/it/case-studies/comcast/index.html
  content/it/community/_index.html
  content/it/community/code-of-conduct.md
  content/it/community/static/README.md
  content/it/community/static/cncf-code-of-conduct.md
  content/it/docs/concepts/overview/what-is-kubernetes.md
  content/it/includes/index.md
  i18n/it.toml
Labels: approved, cncf-cla: yes, language/it, lgtm, size/XL

#12711 New Linux Academy Content Added
  content/en/docs/tutorials/online-training/overview.md
Labels: approved, cncf-cla: yes, language/en, lgtm, size/XS

#12731 ja-trans: setup/custom-cloud/coreos/
  content/ja/docs/setup/custom-cloud/coreos.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/XS
