Repository kubernetes/website, pull requests merged in 2024-05, with the labels that each got.

#46098 Update style guide
  content/en/_index.html
  content/en/docs/contribute/style/style-guide.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/en

#46101 [zh]Update common-labels.md with corrected instance names
  content/zh-cn/docs/concepts/overview/working-with-objects/common-labels.md
Labels: cncf-cla: yes, size/M, lgtm, approved, language/zh, area/localization

#46103 Update 2021 blog content files to move author details in front-matter
  content/en/blog/_posts/2021-03-09-The-Evolution-of-Kubernetes-Dashboard/index.md
  content/en/blog/_posts/2021-04-06-PodSecurityPolicy-Past-Present-and-Future.md
  content/en/blog/_posts/2021-04-08-cronjob-reaches-ga/index.md
  content/en/blog/_posts/2021-04-08-kubernetes-release-1.21.md
  content/en/blog/_posts/2021-04-12-introducing-suspended-jobs.md
  content/en/blog/_posts/2021-04-13-kube-state-metrics-goes-v-2-0.md
  content/en/blog/_posts/2021-04-14-local-storage-features-go-beta.md
  content/en/blog/_posts/2021-04-15-Three-Tenancy-Models-for-Kubernetes.md
  content/en/blog/_posts/2021-04-16-volume-health-monitoring-alpha.md
  content/en/blog/_posts/2021-04-19-introducing-indexed-jobs.md
  content/en/blog/_posts/2021-04-20-Defining-NetworkPolicy-Conformance-For-CNIs.md
  content/en/blog/_posts/2021-04-20-annotating-k8s-for-humans.md
  content/en/blog/_posts/2021-04-21-Graceful-Node-Shutdown-Beta.md
  content/en/blog/_posts/2021-04-22-gateway-api/index.md
  content/en/blog/_posts/2021-04-23-metrics-stability-ga/index.md
  content/en/blog/_posts/2021-05-14-using-finalizers-to-control-deletion.md
  content/en/blog/_posts/2021-06-21-writing-a-controller-for-pod-labels.md
  content/en/blog/_posts/2021-06-28-announcing-kubernetes-community-group-annual-reports/index.md
  content/en/blog/_posts/2021-07-14-upcoming-changes-in-kubernetes-1-22/index.md
  content/en/blog/_posts/2021-07-15-SIG-Usability-Spotlight.md
  content/en/blog/_posts/2021-07-20-Kubernetes-Release-Cadence/index.md
  content/en/blog/_posts/2021-07-26-update-with-ingress-nginx.md
  content/en/blog/_posts/2021-07-29-kubernetes-1-21-release-interview.md
  content/en/blog/_posts/2021-08-04-kubernetes-release-1.22.md
  content/en/blog/_posts/2021-08-06-server-side-apply-ga.md
  content/en/blog/_posts/2021-08-09-alpha-swap-support.md
  content/en/blog/_posts/2021-08-09-csi-windows-support-with-csi-proxy-reaches-ga.md
  content/en/blog/_posts/2021-08-11-memory-manager-moves-to-beta.md
  content/en/blog/_posts/2021-08-16-support-for-hostprocess-containers/index.md
  content/en/blog/_posts/2021-08-25-seccomp-default.md
  content/en/blog/_posts/2021-08-27-minreadysecond-statefulsets.md
  content/en/blog/_posts/2021-08-30-volume-populators-alpha.md
  content/en/blog/_posts/2021-09-03-api-server-tracing.md
  content/en/blog/_posts/2021-09-13-read-write-once-pod-access-mode-alpha.md
  content/en/blog/_posts/2021-09-27-SIG-Node-Spotlight/index.md
  content/en/blog/_posts/2021-09-29-data-duplication-in-data-heavy-k8s-env.md
  content/en/blog/_posts/2021-10-05-nsa-cisa-hardening.md
  content/en/blog/_posts/2021-10-08-clusterclass-and-managed-topologies.md
  content/en/blog/_posts/2021-10-18-kpng-specialized-proxiers.md
  content/en/blog/_posts/2021-11-08-steering-committee-results-2021.md
  content/en/blog/_posts/2021-11-09-non-root-containers-and-devices.md
  content/en/blog/_posts/2021-11-12-are-you-ready-for-dockershim-removal/index.md
  content/en/blog/_posts/2021-11-26-memory-qos-cgroups-v2/index.md
  content/en/blog/_posts/2021-12-01-kubernetes-1.22-release-interview.md
  content/en/blog/_posts/2021-12-07-kubernetes-release-1.23.md
  content/en/blog/_posts/2021-12-08-dual-stack-networking-ga.md
  content/en/blog/_posts/2021-12-09-pod-security-admission-beta.md
  content/en/blog/_posts/2021-12-10-csi-migration-status.md
  content/en/blog/_posts/2021-12-15-prevent-persistentvolume-leaks-when-deleting-out-of-order.md
  content/en/blog/_posts/2021-12-16-StatefulSet-PVC-Auto-Deletion.md
  content/en/blog/_posts/2021-12-17-security-profiles-operator-v0.4.0/index.md
  content/en/blog/_posts/2021-12-21-admission-controllers-for-container-drift/index.md
  content/en/blog/_posts/2021-12-22-kubernetes-in-kubernetes-and-pxe-bootable-server-farm.md
Labels: cncf-cla: yes, size/L, lgtm, sig/docs, approved, language/en, area/blog

#46093 [zh-cn] minor sync docs/reference/access-authn-authz
  content/zh-cn/docs/reference/access-authn-authz/abac.md
  content/zh-cn/docs/reference/access-authn-authz/certificate-signing-requests.md
  content/zh-cn/docs/reference/access-authn-authz/kubelet-authn-authz.md
  content/zh-cn/docs/reference/access-authn-authz/node.md
  content/zh-cn/docs/reference/access-authn-authz/rbac.md
  content/zh-cn/docs/reference/access-authn-authz/validating-admission-policy.md
  content/zh-cn/docs/reference/access-authn-authz/webhook.md
Labels: cncf-cla: yes, size/M, lgtm, approved, language/zh, area/localization

#46115 Correction: More than four types are available
  content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/en

#46121 Fix mermaid syntax in CRI blog post
  content/en/blog/_posts/2024-05-01-cri-streaming-explained.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/en, area/blog

#46119 [zh-cn]sync extend-service-ip-ranges configure-pdb
  content/zh-cn/docs/tasks/network/extend-service-ip-ranges.md
  content/zh-cn/docs/tasks/run-application/configure-pdb.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/zh, area/localization

#46097 [zh-cn] sync pods/_index.md
  content/zh-cn/docs/concepts/workloads/pods/_index.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#45056 [ar] Translate index to arabic
  content/ar/docs/_index.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/ar

#45572 [ar] Localize setup/best-practices/_index.md
  content/ar/docs/setup/best-practices/_index.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/ar

#45574 [ar] Localize setup/production-environment/tools/_index.md
  content/ar/docs/setup/production-environment/tools/_index.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/ar

#46084 Use lowercases for some terms in kubectl/introduction.md
  content/en/docs/reference/kubectl/introduction.md
Labels: cncf-cla: yes, size/M, lgtm, sig/docs, approved, language/en

#45997 [ja] Translate content/en/docs/reference/glossary/container-env-variables.md into Japanese
  content/ja/docs/reference/glossary/container-env-variables.md
Labels: cncf-cla: yes, size/S, lgtm, approved, tide/merge-method-squash, language/ja, area/localization

#46134 Fix typo in security documentation
  content/en/docs/concepts/security/_index.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/en

#46126 [zh-cn] sync style-guide debug-cluster/_index
  content/zh-cn/docs/contribute/style/style-guide.md
  content/zh-cn/docs/tasks/debug/debug-cluster/_index.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/zh, area/localization

#46147 [zh] Add 4 feature-gates: r*.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/rotate-kubelet-client-certificate.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/rotate-kubelet-server-certificate.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/run-as-group.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/runtime-class.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46148 [zh] Sync 15 feature gates for reference
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/admission-webhook-match-conditions.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/api-self-subject-review.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/crd-validation-ratcheting.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/hpa-container-metrics.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/identify-pod-os.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/image-maximum-gc-age.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/legacy-service-account-token-clean-up.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/new-volume-manager-reconstruction.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/node-log-query.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-host-ips.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-account-token-jti.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/stable-load-balancer-node-set.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/structured-authentication-configuration.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/structured-authorization-configuration.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/translate-stream-close-websocket-requests.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46133 [zh-cn] sync kube-controller-manager-config.v1alpha1 kube-scheduler-config.v1
  content/zh-cn/docs/reference/config-api/kube-controller-manager-config.v1alpha1.md
  content/zh-cn/docs/reference/config-api/kube-scheduler-config.v1.md
Labels: cncf-cla: yes, size/S, lgtm, approved, language/zh, area/localization

#46149 [zh-cn] sync kubeadm_init_phase_certs_ca kubeadm_init_phase_control-plane_all
  content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_ca.md
  content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md
Labels: cncf-cla: yes, size/S, lgtm, approved, language/zh, area/localization

#46128 Update 2020 blog content files to move author details in front-matter
  content/en/blog/_posts/2020-01-08-csi-driver-testing.md
  content/en/blog/_posts/2020-01-10-Remembering-Brad-Childs.md
  content/en/blog/_posts/2020-01-15-Kubernetes-on-MIPS.md
  content/en/blog/_posts/2020-01-21-Docs-Review-2019.md
  content/en/blog/_posts/2020-01-21-csi-ephemeral-inline-volumes.md
  content/en/blog/_posts/2020-01-22-Gamified-Chaos-Engineering-Tool-for-Kubernetes.md
  content/en/blog/_posts/2020-02-18-Contributor-Summit-Amsterdam-Schedule-Announced.md
  content/en/blog/_posts/2020-02-28-bring-your-ideas-to-world-with-kubectl-plugins.md
  content/en/blog/_posts/2020-03-04-Contributor-Summit-Delayed.md
  content/en/blog/_posts/2020-03-18-Kong-Ingress-Controller-and-Service-Mesh.md
  content/en/blog/_posts/2020-03-19-kubernetes-the-hard-way.md
  content/en/blog/_posts/2020-03-25-kubernetes-1.18-release-announcement.md
  content/en/blog/_posts/2020-03-30-topology-manager-beta.md
  content/en/blog/_posts/2020-04-01-server-side-apply-beta2.md
  content/en/blog/_posts/2020-04-02-Improvements-to-the-Ingress-API-in-Kubernetes-1.18.md
  content/en/blog/_posts/2020-04-03-Introducing-Windows-CSI-support-alpha-for-Kubernetes.md
  content/en/blog/_posts/2020-04-06-API-Priority-and-Fairness-Alpha.md
  content/en/blog/_posts/2020-04-21-Cluster-API-v1alpha3-Delivers-New-Features-and-an-Improved-User-Experience.md
  content/en/blog/_posts/2020-04-21-contributor-communication-upstream-marketing.md
  content/en/blog/_posts/2020-05-05-introducing-podtopologyspread.md
  content/en/blog/_posts/2020-05-06-third-party-dual-sourced-content.md
  content/en/blog/_posts/2020-05-21-wsl2-dockerdesktop-k8s.md
  content/en/blog/_posts/2020-05-28-my-exciting-journey-into-kubernetes-history.md
  content/en/blog/_posts/2020-05-29-K8s-KPIs-with-Kuberhealthy.md
  content/en/blog/_posts/2020-06-05-Supporting-the-Evolving-Ingress-Specification-in-Kubernetes-1.18.md
  content/en/blog/_posts/2020-06-15-better-docs-ux-with-docsy.md
  content/en/blog/_posts/2020-06-29-working-with-terraform-and-kubernetes.md
  content/en/blog/_posts/2020-07-27-kubernetes-1-17-release-interview.md
  content/en/blog/_posts/2020-08-03-kubernetes-1-18-release-interview.md
  content/en/blog/_posts/2020-08-14-introducing-hierarchical-namespaces.md
  content/en/blog/_posts/2020-08-21-Moving-Forward-From-Beta/index.md
  content/en/blog/_posts/2020-08-26-kubernetes-release-1.19.md
  content/en/blog/_posts/2020-08-31-increase-kubernetes-support-one-year.md
  content/en/blog/_posts/2020-09-01-generic-ephemeral-volumes.md
  content/en/blog/_posts/2020-09-02-scaling-kubernetes-networking-endpointslices.md
  content/en/blog/_posts/2020-09-03-warnings/index.md
  content/en/blog/_posts/2020-09-04-introducing-structured-logs.md
  content/en/blog/_posts/2020-09-16-gsoc20-building-operators-for-cluster-addons.md
  content/en/blog/_posts/2020-09-30-writing-crl-scheduler/index.md
  content/en/blog/_posts/2020-10-12-steering-committee-results.md
  content/en/blog/_posts/2020-11-02-remembering-dan-kohn.md
  content/en/blog/_posts/2020-11-18-cloud-native-security-for-your-cluster/index.md
  content/en/blog/_posts/2020-12-02-dont-panic-kubernetes-and-docker.md
  content/en/blog/_posts/2020-12-04-gsod-2020-improving-api-reference-experience.md
  content/en/blog/_posts/2020-12-08-kubernetes-release-1.20.md
  content/en/blog/_posts/2020-12-10-Kubernetes-Volume-Snapshot-Moves-to-GA.md
  content/en/blog/_posts/2020-12-10-Pod-Impersonation-and-Short-lived-Volumes-in-CSI-Drivers.md
  content/en/blog/_posts/2020-12-14-Granular-Control-of-Volume-Permission-Changes.md
  content/en/blog/_posts/2020-12-16-third-party-device-metrics-hits-ga.md
Labels: cncf-cla: yes, size/L, lgtm, sig/docs, approved, language/en, area/blog

#45990 [zh] Add trans to api-extension/custom-resources.md
  content/zh-cn/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
  content/zh-cn/examples/customresourcedefinition/shirt-resource-definition.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46131 [zh-cn] sync pod-security-standards security-checklist service-accounts system-traces
  content/zh-cn/docs/concepts/cluster-administration/system-traces.md
  content/zh-cn/docs/concepts/security/pod-security-standards.md
  content/zh-cn/docs/concepts/security/security-checklist.md
  content/zh-cn/docs/concepts/security/service-accounts.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46132 [zh-cn] sync security/apparmor.md
  content/zh-cn/docs/tutorials/security/apparmor.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46153 [zh-cn]sync kube-apiserver.md
  content/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#44622 Revise callouts in encryption-at-rest task page
  content/en/docs/tasks/administer-cluster/encrypt-data.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/en, sig/security

#46168 [zh-cn] sync releases/_index.md
  content/zh-cn/releases/_index.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/zh, area/localization

#46162 [zh] sync services-networking/dual-stack.md
  content/zh-cn/docs/concepts/services-networking/dual-stack.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/zh, area/localization

#46152 [zh-cn] sync implementation-details.md
  content/zh-cn/docs/reference/setup-tools/kubeadm/implementation-details.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46154 [zh-cn] sync kube-proxy.md
  content/zh-cn/docs/reference/command-line-tools-reference/kube-proxy.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46156 [zh-cn]sync kubelet.md
  content/zh-cn/docs/reference/command-line-tools-reference/kubelet.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46159 [zh] Add 4 new feature gates: r*.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/recursive-read-only-mounts.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/relaxed-environment-variable-validation.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/retroactive-default-storage-class.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/root-ca-config-map.md
Labels: cncf-cla: yes, size/L, lgtm, approved, tide/merge-method-squash, language/zh, area/localization

#46120 [zh] Sync dynamic-resource-allocation.md
  content/zh-cn/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46122 [zh-cn]sync kubeadm-certs.md
  content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
Labels: cncf-cla: yes, size/XL, lgtm, approved, language/zh, area/localization

#46127 [zh-cn] Localization blog: 2024-04-23-recursive-read-only-mounts.md
  content/zh-cn/blog/_posts/2024-04-23-recursive-read-only-mounts.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46151 [zh-cn]sync kubeadm_upgrade_plan kubeadm-init kubeadm-join
  content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_plan.md
  content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init.md
  content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-join.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46056 [zh] Add kubectl/introduction.md
  content/zh-cn/docs/reference/kubectl/introduction.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#45999 Remove redundant closing spaces
  content/en/docs/concepts/services-networking/ingress.md
  content/en/docs/concepts/storage/persistent-volumes.md
  content/en/docs/concepts/storage/volumes.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/en

#46080 [zh] Add cluster-administration/node-shutdown.md
  content/zh-cn/docs/concepts/cluster-administration/node-shutdown.md
Labels: cncf-cla: yes, size/XL, lgtm, approved, language/zh, area/localization

#45915 Fixed selected search bar border styling
  assets/scss/_custom.scss
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, area/web-development

#45893 Fix documentation feedback button style
  assets/scss/_base.scss
  layouts/partials/feedback.html
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, area/web-development

#45819 Rename example pod-with-affinity-anti-affinity.yaml
  content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
  content/en/examples/examples_test.go
  content/en/examples/pods/pod-with-affinity-preferred-weight.yaml
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/en

#45530 Customizing with patches - Move suffix parameter to the second position
  content/en/docs/setup/production-environment/tools/kubeadm/control-plane-flags.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/api-machinery, sig/docs, approved, language/en

#45464 Update networking.md
  content/en/docs/concepts/cluster-administration/networking.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/en

#46160 [zh] Remove manage-deployment.md after relocation
  content/zh-cn/docs/concepts/cluster-administration/manage-deployment.md
Labels: cncf-cla: yes, size/XL, lgtm, approved, language/zh, area/localization

#45549 check-service-exists
  content/en/docs/tutorials/kubernetes-basics/update/update-intro.html
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/en, area/web-development

#46143 [hi] Ready training section for vanilla Docsy
  content/hi/training/_index.html
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/hi, area/localization

#45567 Add notes on etcd tracing problems to api-server-tracing blog post
  content/en/blog/_posts/2021-09-03-api-server-tracing.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/en, area/blog

#46173 [zh-cn]sync assign-pod-node persistent-volumes
  content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md
  content/zh-cn/docs/concepts/storage/persistent-volumes.md
  content/zh-cn/examples/pods/pod-with-affinity-preferred-weight.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, language/zh, area/localization

#46174 [zh-cn]sync ingress dynamic-provisioning
  content/zh-cn/docs/concepts/services-networking/ingress.md
  content/zh-cn/docs/concepts/storage/dynamic-provisioning.md
Labels: cncf-cla: yes, size/S, lgtm, approved, language/zh, area/localization

#46129 [zh-cn]Locatlization blog:2024-02-21-prevent-unauthorized-volume-mode-conversion-ga.md
  content/zh-cn/blog/_posts/2024-02-21-prevent-unauthorized-volume-mode-conversion-ga.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#45900 Update define-command-argument-container.md
  content/en/docs/tasks/inject-data-application/define-command-argument-container.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/en

#46029 [ja] Translate content/en/docs/tasks/tools/install-kubectl-linux.md
  content/ja/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
  content/ja/docs/tasks/tools/included/optional-kubectl-configs-fish.md
  content/ja/docs/tasks/tools/included/optional-kubectl-configs-zsh.md
  content/ja/docs/tasks/tools/install-kubectl-linux.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/ja, area/localization

#46030 [ja] Translate content/ja/docs/tasks/tools/_index.md
  content/ja/docs/tasks/tools/_index.md
Labels: cncf-cla: yes, size/M, lgtm, approved, tide/merge-method-squash, language/ja, area/localization

#46170 [ja] Localization of StatefulSet concept uses wrong term
  content/ja/docs/reference/glossary/statefulset.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, tide/merge-method-squash, language/ja, area/localization

#46182 [zh-cn] sync pods/_index.md ephemeral-containers.md
  content/zh-cn/docs/concepts/workloads/pods/_index.md
  content/zh-cn/docs/concepts/workloads/pods/ephemeral-containers.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/zh, area/localization

#46116 [ja] Add button for About the documentation in `content/ja/docs/home/_index.md`
  content/ja/docs/home/_index.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/ja, area/localization

#46194 [zh] update define-command-argument-container.md
  content/zh-cn/docs/tasks/inject-data-application/define-command-argument-container.md
Labels: cncf-cla: yes, size/S, lgtm, approved, language/zh, area/localization

#45823 [bn] Localization of ephemeral-container.md
  content/bn/docs/reference/glossary/ephemeral-container.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/bn

#46062 [bn] rename file reference glossary sidecar-container.md
  content/bn/docs/reference/glossary/sidecar-container.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/bn

#46067 [bn] localize cncf-code-of-conduct.md
  content/bn/community/static/cncf-code-of-conduct.md
Labels: cncf-cla: yes, size/M, lgtm, sig/docs, approved, language/bn

#46106 [bn] update commit hash no in /bn/community/code-of-conduct.md
  content/bn/community/code-of-conduct.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/bn

#46184 [bn] update case-studies /_index.html
  content/bn/case-studies/_index.html
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/bn

#46185 [bn] Update patch-releases.md
  content/bn/releases/patch-releases.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/bn

#46189 [bn] Localizing files in includes and small fixes
  content/bn/docs/concepts/_index.md
  content/bn/docs/concepts/extend-kubernetes/control-plane.png
  content/bn/docs/tasks/_index.md
  content/bn/docs/tutorials/configuration/configure-java-microservice/_index.md
  content/bn/docs/update-user-guide-links.py
  content/bn/includes/default-storage-class-prereqs.md
  content/bn/includes/task-tutorial-prereqs-node-upgrade.md
  content/bn/includes/task-tutorial-prereqs.md
  content/bn/includes/user-guide-content-moved.md
Labels: cncf-cla: yes, size/L, lgtm, sig/docs, approved, language/bn

#46190 [bn] Adding images in `docs /images/`
  content/bn/docs/images/diagram-guide-example-3.svg
  content/bn/docs/images/gateway-kind-relationships.svg
  content/bn/docs/images/gateway-request-flow.svg
  content/bn/docs/images/ingress.svg
  content/bn/docs/images/ingressFanOut.svg
  content/bn/docs/images/ingressNameBased.svg
  content/bn/docs/images/kubernetes-cluster-network.svg
  content/bn/docs/images/podSchedulingGates.svg
  content/bn/docs/images/tutor-service-nodePort-fig01.svg
  content/bn/docs/images/tutor-service-nodePort-fig02.svg
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/bn

#46191 [bn] Localizing ha-control-plane-(bn-version).svg
  content/bn/docs/images/ha-control-plane-(bn-version).svg
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/bn

#46193 [bn] Update bn/docs/contribute _index.md
  content/bn/docs/contribute/_index.md
Labels: cncf-cla: yes, size/L, lgtm, sig/docs, approved, language/bn

#46195 [bn] Update docs/home / index.md
  content/bn/docs/home/_index.md
  content/bn/docs/home/supported-doc-versions.md
Labels: cncf-cla: yes, size/M, lgtm, sig/docs, approved, language/bn

#46197 [bn] Localize training / index.html
  content/bn/training/_index.html
Labels: cncf-cla: yes, size/L, lgtm, sig/docs, approved, language/bn

#46199 [bn] Localize concepts/workloads/controllers / index.md
  content/bn/docs/concepts/workloads/controllers/_index.md
Labels: cncf-cla: yes, size/M, lgtm, sig/docs, approved, language/bn

#45031 [ar] Translate home index to arabic
  content/ar/docs/home/_index.md
Labels: cncf-cla: yes, size/M, lgtm, sig/docs, approved, language/ar

#46169 [it] Ready training section for vanilla Docsy
  content/it/training/_index.html
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/it, area/web-development, area/localization

#46201 Make the markdown prettier: storage-version-migration.md
  content/en/docs/tasks/manage-kubernetes-objects/storage-version-migration.md
Labels: cncf-cla: yes, size/L, lgtm, sig/docs, approved, kind/cleanup, language/en

#46206 [zh] Update networking.md
  content/zh-cn/docs/concepts/cluster-administration/networking.md
Labels: cncf-cla: yes, size/S, lgtm, approved, language/zh, area/localization

#46198 [zh] Add 5 new feature gates
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/custom-resource-field-selectors.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/runtime-class-in-image-cri-api.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/selinux-mount.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-traffic-distribution.md
  content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/storage-version-migrator.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46180 [zh-cn] sync user-namespaces.md
  content/zh-cn/docs/concepts/workloads/pods/user-namespaces.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46181 [zh-cn] sync disruptions init-containers pod-qos
  content/zh-cn/docs/concepts/workloads/pods/disruptions.md
  content/zh-cn/docs/concepts/workloads/pods/init-containers.md
  content/zh-cn/docs/concepts/workloads/pods/pod-qos.md
Labels: cncf-cla: yes, size/S, lgtm, approved, language/zh, area/localization

#46066 [bn] Adding example/job files in bn version
  content/bn/examples/application/job/cronjob.yaml
  content/bn/examples/application/job/indexed-job-vol.yaml
  content/bn/examples/application/job/indexed-job.yaml
  content/bn/examples/application/job/job-sidecar.yaml
  content/bn/examples/application/job/job-tmpl.yaml
Labels: cncf-cla: yes, size/L, lgtm, sig/docs, approved, language/bn

#44839 [ja] Translate `content/en/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md` into Japanese
  content/ja/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
Labels: cncf-cla: yes, size/L, lgtm, sig/docs, approved, tide/merge-method-squash, language/ja, area/localization

#46179 [zh-cn]sync services-networking/service
  content/zh-cn/docs/concepts/services-networking/service.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46211 [zh] Sync command-line-tools-reference/kube-scheduler.md
  content/zh-cn/docs/reference/command-line-tools-reference/kube-scheduler.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46209 [zh] Sync command-line-tools-reference/kube-controller-manager.md
  content/zh-cn/docs/reference/command-line-tools-reference/kube-controller-manager.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46208 [pl] Ready training section for vanilla Docsy
  content/pl/training/_index.html
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/pl, area/localization

#46214 Remove ConsistentHTTPGetHandlers feature-gate
  content/en/docs/reference/command-line-tools-reference/feature-gates/consistent-http-get-handlers.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/en

#46028 [zh-cn] Localize docs/concepts/workloads/management.md
  content/zh-cn/docs/concepts/workloads/management.md
Labels: cncf-cla: yes, size/XL, lgtm, approved, language/zh, area/localization

#46221 [zh] fix miss `Linux kernel: v5.12` in `2024-04-23-recursive-read-only-mounts.md`
  content/zh-cn/blog/_posts/2024-04-23-recursive-read-only-mounts.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/zh, area/localization

#46218 [release-1.29]: Fix userns example and add OCI runtime requirements
  content/en/docs/concepts/workloads/pods/user-namespaces.md
  content/en/docs/tasks/configure-pod-container/user-namespaces.md
Labels: cncf-cla: yes, size/M, lgtm, sig/docs, approved, language/en

#46216 [release-1.27]: Fix userns example and add OCI runtime requirements
  content/en/docs/concepts/workloads/pods/user-namespaces.md
  content/en/docs/tasks/configure-pod-container/user-namespaces.md
Labels: cncf-cla: yes, size/M, lgtm, sig/docs, approved, language/en

#46231 [zh] Ready training section for vanilla Docsy
  content/zh-cn/training/_index.html
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/zh, area/localization

#46200 [zh] Add storage-version-migration.md
  content/zh-cn/docs/tasks/manage-kubernetes-objects/storage-version-migration.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46233 Use correct shade of Kubernetes blue
  assets/scss/_base.scss
  assets/scss/_custom.scss
  assets/scss/_skin.scss
  assets/scss/_variables_project.scss
  static/css/glossary.css
  static/css/style_apiref.css
  static/css/training.css
Labels: cncf-cla: yes, size/M, lgtm, sig/docs, approved, area/web-development

#46235 Clean up kubeadm/implementation-details.md
  content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
Labels: cncf-cla: yes, size/L, lgtm, sig/docs, approved, kind/cleanup, language/en

#46239 Change the host for the ingress tutorial, to mitigate a security risk.
  content/en/docs/tasks/access-application-cluster/ingress-minikube.md
  content/en/examples/service/networking/example-ingress.yaml
Labels: cncf-cla: yes, size/M, lgtm, sig/docs, approved, language/en

#46224 [zh-cn]sync container-lifecycle-hooks configure-redis-using-configmap
  content/zh-cn/docs/concepts/containers/container-lifecycle-hooks.md
  content/zh-cn/docs/tutorials/configuration/configure-redis-using-configmap.md
Labels: cncf-cla: yes, size/S, lgtm, approved, language/zh, area/localization

#46245 Updating OWNERS_ALIASES with final changes
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved

#46242 [zh] sync control-plane-flags encrypt-data
  content/zh-cn/docs/setup/production-environment/tools/kubeadm/control-plane-flags.md
  content/zh-cn/docs/tasks/administer-cluster/encrypt-data.md
Labels: cncf-cla: yes, size/M, lgtm, approved, language/zh, area/localization

#46247 [ja] revise `content/ja/docs/contribute/localization.md`
  content/ja/docs/contribute/localization.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/ja, area/localization

#46192 [ja] Ready training section for vanilla Docsy
  content/ja/training/_index.html
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/ja, area/localization

#46207 [ja] Update content/ja/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
  content/ja/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/ja, area/localization

#46251 [zh-cn] sync apiserver-admission.v1 imagepolicy.v1alpha1
  content/zh-cn/docs/reference/config-api/apiserver-admission.v1.md
  content/zh-cn/docs/reference/config-api/imagepolicy.v1alpha1.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/zh, area/localization

#46238 [zh] Sync 9 reference files in setup-tools/kubeadm
  content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_check-expiration.md
  content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-etcd-client.md
  content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver.md
  content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-peer.md
  content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-server.md
  content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_front-proxy-ca.md
  content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_front-proxy-client.md
  content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_preflight.md
  content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-reset.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46078 [bn] Localize workload.md
  content/bn/docs/reference/glossary/workload.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/bn

#46094 [bn] localize kube-apiserver.md
  content/bn/docs/reference/glossary/kube-apiserver.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/bn

#46110 [bn] Localize configmap.md
  content/bn/docs/reference/glossary/configmap.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/bn

#46089 [bn] Localize glossary entry for "Node"
  content/bn/docs/reference/glossary/node.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, area/localization, language/bn

#46090 【bn] Localize annotation.md
  content/bn/docs/reference/glossary/annotation.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/bn

#46111 [bn] Localize secret.md
  content/bn/docs/reference/glossary/secret.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/bn

#46112 [bn] Create mirror-pod.md
  content/bn/docs/reference/glossary/mirror-pod.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/bn

#46117 [bn] Localize control-plane.md
  content/bn/docs/reference/glossary/control-plane.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/bn

#46135 [bn] localized app-container.md
  content/bn/docs/reference/glossary/app-container.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/bn

#46136 [bn] Localization of service-account.md
  content/bn/docs/reference/glossary/service-account.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/bn

#46139 [bn] Localize daemonset.md
  content/bn/docs/reference/glossary/daemonset.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/bn

#46264 [bn] Fix buil errors
  content/bn/docs/concepts/workloads/_index.md
  content/bn/docs/concepts/workloads/controllers/_index.md
  content/bn/releases/patch-releases.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/bn

#46252 [bn] Localize Glossary /object.md and ReplicationController.md
  content/bn/docs/reference/glossary/object.md
  content/bn/docs/reference/glossary/replication-controller.md
Labels: cncf-cla: yes, size/M, lgtm, sig/docs, approved, language/bn

#46255 [bn] add Readme files in bn/example
  content/bn/examples/README.md
  content/bn/examples/examples.go
  content/bn/examples/examples_test.go
Labels: cncf-cla: yes, size/XL, lgtm, sig/docs, approved, language/bn

#46249 [bn] Localization of Content/bn/releases/release.md
  content/bn/releases/release.md
Labels: cncf-cla: yes, size/L, lgtm, sig/docs, approved, language/bn

#46258 [bn] Localization of Content/bn/releases/version skew policy.md
  content/bn/releases/version-skew-policy.md
Labels: cncf-cla: yes, size/L, lgtm, sig/docs, approved, language/bn

#46256 [ja] Sync up README.md (ja) to en
  README-ja.md
Labels: cncf-cla: yes, size/L, lgtm, sig/docs, approved, language/ja

#46276 Fix link to 'Node heartbeats' section
  content/en/docs/concepts/architecture/leases.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/en

#45971 Add Gateway API v1.1 Blog Post
  content/en/blog/_posts/2024-05-09-gateway-api-v1.1/gateway-api-logo.svg
  content/en/blog/_posts/2024-05-09-gateway-api-v1.1/index.md
Labels: cncf-cla: yes, size/L, lgtm, sig/docs, approved, tide/merge-method-squash, language/en, area/blog

#46250 [zh-cn] sync ingress-minikube.md
  content/zh-cn/docs/tasks/access-application-cluster/ingress-minikube.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46266 Remove GA ServiceNodePortStaticSubrange feature gate
  content/en/docs/concepts/services-networking/service.md
  content/en/docs/reference/command-line-tools-reference/feature-gates/service-nodeport-static-subrange.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/en, area/localization

#46280 [bn] Minor fixes
  content/bn/_index.html
  content/bn/docs/concepts/architecture/_index.md
  content/bn/docs/concepts/services-networking/_index.md
  content/bn/docs/concepts/workloads/pods/_index.md
  content/bn/docs/concepts/workloads/pods/sidecar-containers.md
  content/bn/docs/setup/learning-environment/_index.md
  content/bn/docs/setup/production-environment/_index.md
  content/bn/docs/setup/production-environment/tools/_index.md
  content/bn/docs/setup/production-environment/turnkey-solutions.md
Labels: cncf-cla: yes, size/M, lgtm, sig/docs, approved, language/bn

#46281 Fix incorrect /security alias
  content/ru/docs/reference/issues-security/security.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/ru, area/localization

#46286 [zh] sync leases topology-aware-routing downward-api
  content/zh-cn/docs/concepts/architecture/leases.md
  content/zh-cn/docs/concepts/services-networking/topology-aware-routing.md
  content/zh-cn/docs/concepts/workloads/pods/downward-api.md
Labels: cncf-cla: yes, size/S, lgtm, approved, language/zh, area/localization

#46261 [zh]Update host in example-ingress.yaml to hello-world.example
  content/zh-cn/examples/service/networking/example-ingress.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/zh, area/localization

#46271 [bn] Localizing strings in bangla
  data/i18n/bn/bn.toml
Labels: cncf-cla: yes, size/L, lgtm, sig/docs, approved, language/bn

#46063 [bn] Updating README-bn.md and README.md
  README-bn.md
  README.md
Labels: cncf-cla: yes, size/L, lgtm, sig/docs, approved, language/bn

#46291 [bn] Replacing some words
  content/bn/_index.html
  content/bn/docs/concepts/containers/_index.md
  content/bn/docs/concepts/overview/_index.md
  content/bn/docs/tutorials/hello-minikube.md
  content/bn/docs/tutorials/kubernetes-basics/_index.html
  content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
  content/bn/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
  content/bn/docs/tutorials/kubernetes-basics/scale/scale-intro.html
  content/bn/docs/tutorials/kubernetes-basics/update/update-intro.html
  content/bn/training/_index.html
Labels: cncf-cla: yes, size/M, lgtm, sig/docs, approved, language/bn

#46290 Fix broken link in "Set Kubelet Parameters Via A Configuration File" page
  content/en/docs/tasks/administer-cluster/kubelet-config-file.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/en

#46293 Fix the incorrect /cve alias
  content/ru/docs/reference/issues-security/issues.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/ru, area/localization

#46297 [bn] Static/ redirects - minor fix
  static/_redirects
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, tide/merge-method-squash

#45457 [hi] Fix title mismatch in docs home for "Kubernetes Download"
  content/hi/docs/home/_index.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, language/hi

#46289 [zh-cn] Sync reference/setup-tools/kubeadm
  content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-certs.md
  content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init-phase.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/zh, area/localization

#46301 Fix lists in apparmor.md
  content/en/docs/tutorials/security/apparmor.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/en

#46304 update rbd volume
  content/en/docs/concepts/storage/persistent-volumes.md
  content/en/docs/concepts/storage/volumes.md
Labels: cncf-cla: yes, size/M, lgtm, sig/storage, sig/docs, approved, language/en

#46234 Update 2019 blog content files to move author details in front-matter
  content/en/blog/_posts/2019-01-14-apiserver-dry-run-and-kubectl-diff.md
  content/en/blog/_posts/2019-01-15-container-storage-interface-ga.md
  content/en/blog/_posts/2019-01-17-update-volume-snapshot-alpha.md
  content/en/blog/_posts/2019-02-06-poseidon-firmament-scheduler-announcement.md
  content/en/blog/_posts/2019-02-11-runc-CVE-2019-5736.md
  content/en/blog/_posts/2019-02-12-building-a-kubernetes-edge-control-plane-for-envoy-v2.md
  content/en/blog/_posts/2019-02-28-automate-operations-on-your-cluster-with-operatorhub.md
  content/en/blog/_posts/2019-03-07-raw-block-volume-support-to-beta.md
  content/en/blog/_posts/2019-03-15-Kubernetes-setup-using-Ansible-and-Vagrant.md
  content/en/blog/_posts/2019-03-19-kubeedge-k8s-based-edge-intro.md
  content/en/blog/_posts/2019-03-20-A-Look-Back-And-Whats-In-Store-For-Kubernetes-Contributor-Summits.md
  content/en/blog/_posts/2019-03-21-a-guide-to-kubernetes-admission-controllers.md
  content/en/blog/_posts/2019-03-22-e2e-testing-for-everyone.md
  content/en/blog/_posts/2019-03-25-1-14-release-announcement.md
  content/en/blog/_posts/2019-03-28-PID-Limiting.md
  content/en/blog/_posts/2019-03-28-running-kubernetes-locally-on-linux-with-minikube.md
  content/en/blog/_posts/2019-03-29-kube-proxy-subtleties-debugging-an-intermittent-connection-resets.md
  content/en/blog/_posts/2019-04-01-kubernetes-v1-14-delivers-production-level-support-for-nodes-and-windows-containers.md
  content/en/blog/_posts/2019-04-04-local-persistent-volumes-ga.md
  content/en/blog/_posts/2019-04-16-pod-priority-and-preemption-in-kubernetes.md
  content/en/blog/_posts/2019-04-17-future-of-cloud-providers.md
  content/en/blog/_posts/2019-04-19-Introducing-kube-iptables-tailer-Better-Networking-Visibility-in-Kubernetes-Clusters.md
  content/en/blog/_posts/2019-04-24-Hardware-Accelerated-SSLTLS-Termination-in-Ingress-Controllers-using-Kubernetes-Device-Plugins-and-RuntimeClass.md
  content/en/blog/_posts/2019-04-26-latest-on-localization.md
  content/en/blog/_posts/2019-05-02-kubecon-diversity-lunch-and-hack.md
  content/en/blog/_posts/2019-05-13-kubernetes-1-14-release-interview.md
  content/en/blog/_posts/2019-05-14-expanding-our-contributor-workshops.md
  content/en/blog/_posts/2019-05-17-Kubernetes-Cloud-Native-and-the-Future-of-Software.md
  content/en/blog/_posts/2019-05-23-Kyma-extend-and-build-on-kubernetes-with-ease.md
  content/en/blog/_posts/2019-06-12-contributor-summit-shanghai.md
  content/en/blog/_posts/2019-06-19-kubernetes-1-15-release-announcement.md
  content/en/blog/_posts/2019-06-20-Future-of-CRDs-Structural-Schemas.md
  content/en/blog/_posts/2019-06-21-volume-cloning-alpha.md
  content/en/blog/_posts/2019-06-24-kubeadm-ha-v115.md
  content/en/blog/_posts/2019-06-25-recap-of-contributor-summit-bcn-2019.md
  content/en/blog/_posts/2019-07-18-some-apis-are-being-deprecated.md
  content/en/blog/_posts/2019-07-23-get-started-with-kubernetes-using-python.md
  content/en/blog/_posts/2019-08-06-OPA-Gatekeeper-Policy-and-Governance-for-Kubernetes.md
  content/en/blog/_posts/2019-08-30-announcing-etcd-3.4.md
  content/en/blog/_posts/2019-09-18-kubernetes-1-16-release-announcement.md
  content/en/blog/_posts/2019-09-24-san-diego-contributor-summit.md
  content/en/blog/_posts/2019-10-03-2019-Steering-Committee-Election-Results.md
  content/en/blog/_posts/2019-10-10-contributor-summit-san-diego-schedule.md
  content/en/blog/_posts/2019-10-29-2019-sig-docs-survey.md
  content/en/blog/_posts/2019-11-05-grokkin-the-docs.md
  content/en/blog/_posts/2019-11-05-kubernetes-with-microk8s.md
  content/en/blog/_posts/2019-11-26-cloud-native-java-controller-sdk.md
  content/en/blog/_posts/2019-12-02-gardener-project-update.md
  content/en/blog/_posts/2019-12-06-kubernetes-1-16-release-interview.md
  content/en/blog/_posts/2019-12-09-csi-volume-migration-beta.md
  content/en/blog/_posts/2019-12-09-kubernetes-1.17-release-announcement.md
  content/en/blog/_posts/2019-12-09-volume-snapshot-beta.md
Labels: cncf-cla: yes, size/L, lgtm, sig/docs, approved, kind/cleanup, language/en, area/blog

#46302 remove PersistentVolumeLabel admission plugin
  content/en/docs/reference/access-authn-authz/admission-controllers.md
Labels: cncf-cla: yes, size/S, lgtm, sig/storage, sig/docs, approved, language/en

#46312 docs: add salaxander as SIG docs tech lead
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved

#46305 [zh-cn]sync kubeadm_init_phase_upload-certs kubeadm_join_phase_control-plane-prepare_all
  content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-certs.md
  content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_all.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/zh, area/localization

#46288 [zh] sync/pods/pod-lifecycle.md
  content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46300 [zh] Add two glossary: immutable-infrastructure and sidecar-container
  content/zh-cn/docs/reference/glossary/immutable-infrastructure.md
  content/zh-cn/docs/reference/glossary/sidecar-container.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46099 [de] Update controller definition for clarity and conciseness
  content/de/docs/reference/glossary/controller.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, language/de, area/localization

#46243 [zh] Sync kubeadm/implementation-details.md
  content/zh-cn/docs/reference/setup-tools/kubeadm/implementation-details.md
Labels: cncf-cla: yes, size/L, lgtm, approved, language/zh, area/localization

#46171 [ar] Add Arabic terms into localization glossary
  content/ar/docs/contribute/localization.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, language/ar

#46309 [bn] fixing links to the Bengali pages for Windows, macOS or Linux installs.
  content/bn/docs/tasks/tools/_index.md
Labels: cncf-cla: yes, size/S, lgtm, sig/docs, approved, tide/merge-method-squash, language/bn

#46186 [bn] Partners / index.html
  content/bn/includes/partner-style.css
  content/bn/partners/_index.html
Labels: cncf-cla: yes, size/L, lgtm, sig/docs, approved, tide/merge-method-squash, language/bn

#46333 [bn] Updating shortcode in download.md
  content/bn/releases/download.md
Labels: cncf-cla: yes, size/XS, lgtm, sig/docs, approved, tide/merge-method-squash, language/bn

#46329 [zh-cn]sync kubeadm_config_images_list kubeadm_config_images_pull
  content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
  content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_pull.md
Labels: cncf-cla: yes, size/S, lgtm, approved, language/zh, area/localization

#46330 [zh-cn]sync kubeadm_init kubeadm_init_phase_control-plane_apiserver
  content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md
  content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver.md
Labels: cncf-cla: yes, size/M, lgtm, approved, language/zh, area/localization
